<link type="text/css" rel="stylesheet" href="view/consultas/css/index.css" />
<script src="view/consultas/js/Tela.js"></script>
<script src="view/consultas/js/cliente.js"></script>
<script src="view/consultas/js/consultaCoracao.js"></script>
<script src="view/consultas/js/consultaLingua.js"></script>
<script src="view/consultas/js/consultaOlho.js"></script>
<script src="view/consultas/js/consultaOrelha1.js"></script>
<script src="view/consultas/js/consultaOrelha2.js"></script>
<script src="view/consultas/js/consultas.js"></script>
<script src="view/consultas/js/consulta.js"></script>
<script src="view/consultas/js/consultaAtestado.js"></script>
<script src="view/consultas/js/consultaHipotese.js"></script>
<script src="view/consultas/js/consultaPrestador.js"></script>
<script src="view/consultas/js/consultaRequisicaoServico.js"></script>
<script src="view/consultas/js/consultaPrescricao.js"></script>
<script src="view/consultas/js/clientePesquisa.js"></script>
<script src="http://tinymce.cachefly.net/4.0/tinymce.min.js"></script>
<script src="template/js/xdate.js"></script>

<script type="text/javascript">

    var atualAtestado = new ListaAtestado();
    var atualHipot = new ListaHipoteses();
    var atualPrest = new ListaPrestador();
    var atualReqs = new ListaRequisicaoServico();

    var printTag = "";

    function resetPrint(){
        $(".toprint").unbind().mousedown(function(e) {
            printTag = $(this);
        }).contextMenu({
            menu: 'list-print'
        });
    }

    function getAtestado(num) {
        atualAtestado.texAtestado = $("tr#IdAtestado[name='" + num + "']").attr('onclick');
        atualAtestado.titAtestado = $("tr#IdAtestado[name='" + num + "']").children('th').html();
        atualAtestado.texAtestado = atualAtestado.texAtestado.replace(/\\n/g, "\n");
        atualAtestado.texAtestado = atualAtestado.texAtestado.substring(17, atualAtestado.texAtestado.length - 3);
        console.log(atualAtestado);
    }

    function setIdAtestado() {

        $("tr#IdAtestado").unbind();
        $("tr#IdAtestado").off();
        //Verifica clique do botao direito
        $("tr#IdAtestado").contextMenu({
            menu: 'list-menu-atestado'
        });
        $("tr#IdAtestado").hover(
                function() {
                    $(this).css("background", "#C0D1E7");
                },
                function() {
                    $(this).css("background", "");
                }
        );
        //Verifica clique do botao direito
        $("tr#IdAtestado").mousedown(function(e) {
            if (e.which == 3) {
                var num = atualAtestado.idAtestado = parseInt($(this).attr('name'));
                getAtestado(num);
            }
        });

    }

    $(document).ready(function() {

        resetPrint();

        setIdAtestado();
        atualHipot.resetFunctions();
        atualPrest.resetFunctions();
        atualReqs.resetFunctions();
    });

</script>

<div id="boxe_consultas" class="modal-consultas modal hide fade" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h6>Consultas</h6>
    </div>
    <div class="modal-body modal-body-consultas" >
        <div class="row-fluid" >
            <div class="span5" style="margin-top: -15px;">
                <label><b>Cliente: </b></label>
                <table class="table" border="1px">
                    <tbody id="clienteIinfo">
                        <tr>
                            <th>Matricula: <span name="matricula"></span></th>
                            <th>Idade: <span name="idade"></span></th>
                        </tr>
                        <tr>
                            <th>Nome: <span name="nome"></span></th>
                            <th></th>
                        </tr>
                        <tr>
                            <th>Médico: <span name="medico"></span></th>
                            <th></th>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="span2" >
                <div class="row-fluid">
                    <div class="pull-left">
                        <a href="#" onclick="fechar_modal('boxe_consultas');" class="btn btn-sair"><i class="icon-off"></i> Sair </a>
                    </div>
                </div><br>
                <div class="row-fluid">
                    <a href="#" id="botaoAnterior" class="btn" onclick="consultasTela.ConsultaAnterior();" ><i class="icon-circle-arrow-left"> </i> </a>
                    <a href="#" id="botaoProximo" class="btn" onclick="consultasTela.ConsultaProxima();"><i class="icon-circle-arrow-right"></i> </a>
                    <a href="#" class="btn" onclick="abrir_modal('boxes-busca-consultas-periodo');"><i class="icon-eye-open"></i> </a>
                    <a href="#" class="btn btn-pesquisar" onclick="consultasTela.pesquisaConsulta();"><i class="icon-search"></i> </a>
                </div>
            </div>
            <div class="span5" id="table-FiladeEsperaPacientes" >
                <!--AQUI deve ser colocada a tabela com tres colunas (numero,nome paciente,hora--> 
                <table border="1" width="100%" id='FiladeEsperaPacientes' style="height: 10px"> 
                    <thead>
                        <tr>
                            <th>
                                 Numero
                            </th>
                            <th>
                                 Nome
                            </th>
                            <th>
                                 Hora
                            </th>
                        </tr>
                    </thead>
                    <tbody id="Corpo_Tabela_Fila_Espera">
                       
                    </tbody>
                </table>
                <!--<textarea id="areaDeTextoParaFilaDePacientes" style="height: 80px;"></textarea>-->
            </div>
        </div>

        <div class="row-fluid mrg-consul">
            <div class="row-fluid">
                <div class="span3">
                    <div class="row-fluid">
                        <table cellspacing='10' align="center" class="table table-bordered table-condensed">
                            <thead>
                                <tr class="white">
                                    <th align="center"> Esp</th>
                                    <th align="center"> Data </th>
                                    <th align="center"> Altura</th>
                                    <th align="center"> Peso</th>
                                    <th align="center"> PA</th>
                                </tr>
                            </thead>
                            <tbody id="HistoricoDeClientes">
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="span9" style="border: 1px dashed #3BB7E2 ; ">
                    <div id="tabs" class="tabbable">
                        <ul class="nav nav-tabs nav-aba" >
                            <li class="active"><a href="#clinica" data-toggle="tab" ><h4 class="active-titulo abas-consulta" >Clínica</h4></a></li>
                            <li><a href="#prescricoes" data-toggle="tab"><h4 class="abas-consulta">Prescrições</h4></a></li>
                            <li><a href="#resultados" data-toggle="tab"><h4 class="abas-consulta">Resultados</h4></a></li>
                            <li><a href="#laudos" data-toggle="tab"><h4 class="abas-consulta">Atestados/Laudos</h4></a></li>
                            <li><a href="#testescutaneos" data-toggle="tab"><h4 class="abas-consulta">Testes Cutâneos</h4></a></li>
                            <li><a href="#triagem" data-toggle="tab"><h4 class="abas-consulta">Triagem</h4></a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="clinica" >
                                <div class="row-fluid">
                                    <a href="#" class="consulta-link">Antecedentes Familiares</a><p></p>
                                    <div style="overflow: hidden; height: 60px; width: 854px; border-width: 1px; border-style: solid; margin-top: 1px; margin-left: 1px" id="areaDeTextoParaAtecedentesFamiliares" class="span11" ondblclick="
                                            TextAreaMCE.show(function(text) {
                                                //consultasTela.SelectedClient.setAntecedentesFamiliares(text);
                                                salvarAntecedentesFamiliares(text);
                                            });
                                            TextAreaMCE.set($(this).html());">                                        
                                    </div>
                                    <!--<textarea onchange="enviaDadosClienteConsulta();" name="ant-familiar" class="textarea-dados"></textarea>-->
                                </div>
                                <div class="row-fluid">
                                    <a href="#" class="consulta-link">Antecedentes Pessoais</a><p></p>
                                    <div style="overflow: hidden; height: 60px; width: 854px; border-width: 1px; border-style: solid; margin-top: 1px; margin-left: 1px" id="areaDeTextoParaAntecedentesPessoais"class="span11" ondblclick="
                                            TextAreaMCE.show(function(text) {
                                                //consultasTela.SelectedClient.setAntecedentes(text);
                                                salvarAntecedentesPessoal(text);
                                            });
                                            TextAreaMCE.set($(this).html());">                                        
                                    </div>
                                    <!--<textarea onchange="enviaDadosClienteConsulta();" name="ant-pessoal" class="textarea-dados"></textarea>-->
                                </div>
                                <div class="row-fluid">
                                    <a href="#" class="consulta-link">Alergias</a><p></p>
                                    <div style="overflow: hidden; height: 60px; width: 854px; border-width: 1px; border-style: solid; margin-top: 1px; margin-left: 1px" id="areaDeTextoParaAlergias"class="span11" ondblclick="
//										TextAreaMCE.show(function(text) {
//											consultasTela.SelectedClient.setAlergias(text);
//										});
//										TextAreaMCE.set($(this).html());">                                        
                                    </div>
                                    <!--<textarea onchange="//enviaDadosClienteConsulta();" name="alergias" ></textarea>-->
                                </div>
                                <!--                                <hr>-->
                                <p></p>
                                <div class="row-fluid">
                                    <div class="span4">
                                        <div class="row-fluid"><a class="consulta-link">Dados:</a></div><p></p>
                                        <div >
                                            <div class="span4 dados-mrg" >
                                                <div class="span4"><label> Cm: </label></div>
                                                <div class="span7"><input onchange="consultasTela.SelectedConsulta.setTamanho($(this).val());" type="text" name="" id="cons-cm"/></div>
                                            </div>

                                            <div class="span4 dados-mrg" >
                                                <div class="span4"><label> Kg: </label></div>
                                                <div class="span7"><input onchange="consultasTela.SelectedConsulta.setPeso($(this).val());" type="text" name="" id="cons-kg"/></div>
                                            </div>

                                            <div class="span4 dados-mrg" >
                                                <div class="span4"><label> P.A: </label></div>
                                                <div class="span7"><input onchange="consultasTela.SelectedConsulta.setPA($(this).val());" type="text" name="" id="cons-PA" /></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="span3">
                                        <div class="row-fluid"><a class="consulta-link">Imunizações:</a></div><p></p>
                                        <div>
                                            <a href="#" onclick="vacinacao();" class="btn ">Vacinações</a>
                                            <a href="#" onclick= "abrir_modal('boxes-imunoterapia')" class="btn ">Imunoterapias</a>
                                        </div>
                                    </div>
                                    <div class="span4">
                                        <div class="row-fluid"><a class="consulta-link">Observação:</a></div><!--<p></p>-->
                                        <textarea onchange="" name="obs" ></textarea>
                                    </div>
                                </div>

                                <div class="row-fluid">
                                    <div class="tab-content">
                                        <div class="active tab-pane" id="consultas" >
                                            <a href="#" class="consulta-link" id="areaDeTextoParaConsultaNome">Consulta de:</a><p></p>
                                            <div style="overflow: hidden; height: 110px; width: 854px; border-width: 1px; border-style: solid; margin-top: 1px; margin-left: 1px" id="areaDeTextoParaConsulta" class="span11" ondblclick="
                                                    TextAreaMCE.show(function(text) {
                                                        consultasTela.SelectedConsulta.setConsultaTexto(text);
                                                    });
                                                    TextAreaMCE.set($(this).html());"></div>
                                            <!--<textarea onchange="enviaDadosClienteConsulta();" name="text-consulta" class="medidatextarea" placeholder="Consultas"></textarea>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="prescricoes">
                                <div class="row-fluid">
                                    <div class="span8">
                                        <div class="row-fluid">
                                            <div class="span3">
                                                <a href="#" onclick="limparModalHipoteses();
                                                        limparIdMedicoHipoteses();
                                                        abrir_modal('boxes-hipotesediagnostica');" class="consulta-link">Hipótese Diagnóstica</a><br>
                                            </div>
                                            <div class="span2">
                                                <a href="#" onclick="criaCID10();
                                                        abrir_modal('boxes-cid10');" class="consulta-link">CID 10</a><br>
                                            </div>
                                        </div>
                                        <textarea style="width:1000px;" onchange="enviaDadosClienteConsulta();" name="hipotese-diag" id="txareahip" class="mrg-conmrgsul"></textarea>
                                    </div>
                                </div><br>
                                <div class="row-fluid">
                                    <div class="span1">
                                        <a href="#" onclick="abrir_modal('boxes-prescricoes');" class="consulta-link">Prescrições</a>
                                    </div>
                                    <div class="span3">
                                        <a href="#" onclick="abrir_modal('boxes-recomendacoes');" class="consulta-link">Informações e Recomendações</a>
                                    </div>
                                    <!-- <div class="span3">
                                            <ul class="thumbnails">
                                                    <div class="span2 thumbnail">
                                                            <div class="btn-group" style="position: relative">
                                                                    <a class="btn span12 dropdown-toggle" data-toggle="dropdown" href="#">
                                                                            <i class="icon-tags"></i> BULÁRIO
                                                                            <span class="caret"></span>
                                                                    </a>
                                                                    <ul class="dropdown-menu">
                                                                            <li><a href="http://www4.anvisa.gov.br/BularioEletronico/default.asp" target="_blank" >ANVISA</a></li>
                                                                            <li><a href="http://www.medicinanet.com.br/categorias/bulas_remedios.htm" target="_blank" >Medicina NET</a></li>
                                                                    </ul>
                                                            </div>
                                                    </div>
                                            </ul>
                                    </div>-->
                                </div>
                                <div class="row-fluid">
                                    <div class="span12">
                                        <div style="overflow: scroll; height: 300px; width: 926px; border-width: 1px; border-style: solid;"
                                             name="prescricao" id="txtarea-prescricoes" class="medidatextareapre" ondblclick="
                                                     textareaPrescricao.show(function(text) {
                                                         $('#txtarea-prescricoes').html(textareaPrescricao.get());
                                                     });
                                                     textareaPrescricao.set($('#txtarea-prescricoes').html())"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="resultados" >
                                <div class="row-fluid">
                                    <div style="height: 370px; overflow: scroll" class="span6">
                                        <a  href="#" class="consulta-link" onclick="limparModalRequisicaoServico();
                                                abrir_modal('boxes-requisicoesencaminhamento')"> Requisições / Encaminhamentos</a><br><br>
                                        <input id="hiddenRowId" type="hidden" value ="0"/>
                                        <table cellspacing='10' border='1px' align="center" class="table table-bordered table-condensed">
                                            <thead>
                                                <tr class="white">
                                                    <th align="center">Excluir</th>
                                                    <th align="center">Data</th>
                                                    <th align="center">Prestador/Serviço</th>
                                                </tr>
                                            </thead>
                                            <tbody id="tbody-prestador-servicos">
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="span6">
                                        <a class="consulta-link">Resultados</a><br>
                                        <textarea id="txarearesult" name="resultados-exames" onChange="enviaDadosClienteConsulta();"></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="laudos" >
                                <a  href="#" class="consulta-link" onclick="abrir_modal('boxes-atestados')"> Atestados/Laudos/Declarações</a><br><br>
                                <textarea style="height:350px" name="con-atestado" class="span12 toprint" height="80%" onchange="enviaDadosClienteConsulta();" id="con-atestado"></textarea>
                                <p></p>                                

<!--                        <table  cellspacing='10'  border='1px'  align="center" class="table table-bordered table-condensed" id="" >
                            <thead>
                                <tr class="white">
                                    <th align="center"> Tab1</th>
                                    <th align="center"> Tab2 </th>
                                    <th align="center"> Tab3</th>
                                    <th align="center"> Tab4</th>
                                    <th align="center"> Tab5 </th>
                                </tr>
                            </thead>

                            <tbody >
                                <tr name="table-color" class='dayhead '>
                                    <th align="center"> </th>
                                    <th align="center">3 </th>
                                    <th align="center"> </th>
                                    <th align="center"> </th>
                                    <th align="center"> </th>
                                </tr>
                                <tr name="table-color" class='dayhead '>
                                    <th align="center"> </th>
                                    <th align="center">3 </th>
                                    <th align="center"> </th>
                                    <th align="center"> </th>
                                    <th align="center"> </th>
                                </tr>
                                <tr name="table-color" class='dayhead '>
                                    <th align="center"> </th>
                                    <th align="center">3 </th>
                                    <th align="center"> </th>
                                    <th align="center"> </th>
                                    <th align="center"> </th>
                                </tr>
                                <tr name="table-color" class='dayhead '>
                                    <th align="center"> </th>
                                    <th align="center">3 </th>
                                    <th align="center"> </th>
                                    <th align="center"> </th>
                                    <th align="center"> </th>
                                </tr>
                                <tr name="table-color" class='dayhead '>
                                    <th align="center"> </th>
                                    <th align="center">3 </th>
                                    <th align="center"> </th>
                                    <th align="center"> </th>
                                    <th align="center"> </th>
                                </tr>

                            </tbody>
                        </table>
                                -->
                            </div>
                            <div class="tab-pane" id="testescutaneos" >
                                <div id="msgInsertTeste"></div>
                                <a  href="#" class="consulta-link" onclick="abrir_modal('boxes-testescutaneos')"> Testes Cutâneos</a><br><br>
                                <div class="row-fluid" id="tabela-testecutaneos" >
                                    <table cellspacing='10' border='1px' align="center" class="table table-bordered table-condensed">
                                        <thead>
                                            <tr class="white">
                                                <th align="center"> Data</th>
                                                <th align="center"> Bateria </th>
                                                <th align="center"> Alérgenos</th>
                                                <th align="center"> Resultados</th>
                                            </tr>
                                        </thead>
                                        <tbody id="testesCutaneosConfirmados" >

                                        </tbody>
                                    </table>
                                </div>
                                <input type="button" id="submitTesteCutaneo" onClick="submeterTesteCutaneo()" value="Submeter Teste" class="btn" /><br/><br/>
                                <div class="row-fluid">
                                    <div class="span10">
                                        <a   href="#" class="consulta-link" onclick="" > Resultados relevântes de Testes Cutâneos/Anotações</a><br><br>
                                        <textarea id="resultadosRelevantesTestesCutaneos"></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="triagem">
                                <div class="row-fluid">
                                    <fieldset class="table-bordered">
                                        <legend>Dados da gestação, parto e nascimento</legend>
                                        <div class="span2">
                                            <div class="pull-left">
                                                <a href="#" class="consulta-link"> Gestação:</a><p></p>
                                                <div class="row-fluid">
                                                    <select id="con_gestacao" onchange="consultasTela.SelectedClient.setGestacao($(this).val());">
                                                        <option></option>
                                                        <?php
                                                        foreach (buscaGestacao() as $gestacao) {
                                                            ?>
                                                            <option <?php echo $selected; ?> value="<?php echo $gestacao['id']; ?>" >
                                                                <?php echo $gestacao['tipo']; ?>
                                                            </option>
                                                            <?php
                                                        }
                                                        ?>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="span1">
                                            <a href="#" class="consulta-link"> Parto:</a><p></p>
                                            <select id="con_parto" onchange="consultasTela.SelectedClient.setParto($(this).val());">
                                                <option></option>
                                                <?php
                                                foreach (buscaParto() as $parto) {
                                                    ?>
                                                    <option <?php echo $selected; ?> value="<?php echo $parto['id']; ?>" >
                                                        <?php echo $parto['tipo']; ?>
                                                    </option>
                                                    <?php
                                                }
                                                ?>
                                            </select>
                                        </div>
                                        <div class="span8" >
                                            <a href="#" class="consulta-link">Condições de Nascimento</a><p></p>
                                            <div class="row-fluid">
                                                <div class="span5">
                                                    <div class="span6">
                                                        <label>Idade Gestacional:</label>
                                                    </div>
                                                    <div class="span4">
                                                        <input onchange="consultasTela.SelectedClient.setIdadeGestacional($(this).val());" type="text" id="idade_gestacional" />
                                                    </div>
                                                </div>
                                                <div class="span4">
                                                    <div class="span7">
                                                        <label>Peso ao nascer:</label>
                                                    </div>

                                                    <div class="span4" align="center" >
                                                        <input onchange="consultasTela.SelectedClient.setPesoNasc($(this).val());" type="text" id="peso_nascimento" />
                                                    </div>
                                                </div>
                                                <!--block-pink-->
                                                <div class="span3">
                                                    <div class="span4"><label>apgar :</label></div>
                                                    <div class="span8" align="center">
                                                        <input onchange="consultasTela.SelectedClient.setApgar($(this).val());" type="text" id="apgar" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </fieldset>
                                </div><br>
                                <div class="row-fluid">
                                    <fieldset class="table-bordered-enc">
                                        <div class="span1">
                                            <label>Pediatra:</label>
                                        </div>
                                        <div class="span4">
                                            <select id="con-medico-triagem" onchange="enviaDadosClienteConsulta();" >
                                                <option></option>
                                                <?php
                                                foreach (buscaTodosMedicos() as $medico) {
                                                    ?>
                                                    <option value="<?php echo $medico['id']; ?>" >
                                                        <?php echo $medico['nome']; ?>
                                                    </option>
                                                    <?php
                                                }
                                                ?>
                                            </select>
                                        </div>
                                    </fieldset>
                                </div><br>
                                <div class="row-fluid">
                                    <div class="row-fluid">
                                        <div class="span3 thumbnail">
                                            <a class="btn span12" onclick="consultasTela.modalCoracaozinho();"><i class="icon-info-sign"></i> Coraçãozinho</a>
                                        </div>
                                        <div class="span2 thumbnail">
                                            <a class="btn span12" onclick="consultasTela.modalLinguinha();"><i class="icon-info-sign"></i> Linguinha</a>
                                        </div>
                                        <div class="span2 thumbnail">
                                            <a href="#" class="btn span12" onclick="consultasTela.modalOlhinho();"><i class="icon-info-sign"></i> Olhinho </a>
                                        </div>
                                        <div class="span2 thumbnail">
                                            <a  class="btn span12" onclick="consultasTela.modalOrelhinha1();"><i class="icon-info-sign"></i> Orelhinha-1</a>
                                        </div>
                                        <div class="span2 thumbnail">
                                            <a class="btn span12" onclick="consultasTela.modalOrelhinha2();"> <i class="icon-info-sign"></i> Orelhinha-2</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- ===================== MODAL CONSULTA OLHINHO ====================-->
<div id="boxes-olhinho" class="modal modal-olhinho hide fade" style="top: 35%;">
    <div id="dialog-olhinho" class=" modal-body-olhinho"  style=" width: 970px;">
        <div><a href="#" id="fechar" class="close" />Fechar X</a>
            <h2 class="titulo">Consulta Olhinho</h2>
            <hr style="margin-top: -4px;"/>
            <div class="row-fluid">
                <div class="span6">
                    <fieldset class="table-bordered">
                        <legend>Resultados</legend>
                        <div class="span3">
                            <fieldset class="table-bordered">
                                <legend> Normal </legend>
                                <input type="checkbox" id="olhinho_resultado_normal_od" name="olhinho_resultado_normal[]" value="1"/> OD
                                <input type="checkbox" id="olhinho_resultado_normal_oe" name="olhinho_resultado_normal[]" value="1"> OE
                            </fieldset>
                        </div>
                        <div class="span1"> </div>
                        <div class="span3">
                            <fieldset class="table-bordered">
                                <legend> Suspeito </legend>
                                <input type="checkbox" id="olhinho_resultado_suspeito_od" name="olhinho_resultado_suspeito[]" value="1"/> OD
                                <input type="checkbox" id="olhinho_resultado_suspeito_oe" name="olhinho_resultado_suspeito[]" value="1"/> OE
                            </fieldset>
                        </div>
                        <div class="span1"> </div>
                        <div class="span3">
                            <fieldset class="table-bordered">
                                <legend> Leucoria </legend>
                                <input type="checkbox" id="olhinho_resultado_leucoria_od" name="olhinho_resultado_leucoria[]" value="1"/> OD
                                <input type="checkbox" id="olhinho_resultado_leucoria_oe" name="olhinho_resultado_leucoria[]" value="1"/> OE
                            </fieldset>
                        </div>
                    </fieldset>
                </div>
            </div>
            <div class="row-fluid">
                <fieldset class="table-bordered">
                    <legend>Anotações</legend>
                    <div class="row-fluid">
                        <div class="span6">
                            <fieldset class="table-bordered-enc">
                                <legend>QP</legend>
                                <textarea class="medidatextarea" placeholder="QP" id="olhinho_anotacoes_qp" name="olhinho_anotacoes_qp" ></textarea>
                            </fieldset>
                        </div>
                        <div class="span6">
                            <fieldset class="table-bordered-enc">
                                <legend>HF</legend>
                                <textarea  class="medidatextarea" placeholder="hf" id="olhinho_anotacoes_hf" name="olhinho_anotacoes_hf" ></textarea>
                            </fieldset>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6">
                            <fieldset class="table-bordered-enc">
                                <legend>Outros Exames</legend>
                                <textarea class="medidatextarea" placeholder="Outros Exames" id="olhinho_anotacoes_outros" name="olhinho_anotacoes_outros" ></textarea>
                            </fieldset>
                        </div>
                        <div class="span6">
                            <fieldset class="table-bordered-enc">
                                <legend>Observações</legend>
                                <textarea class="medidatextarea" placeholder="Observações" id="olhinho_anotacoes_obs" name="olhinho_anotacoes_obs" ></textarea>
                            </fieldset>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span9" >
                            <fieldset class="table-bordered">
                                <legend>Conclusões sobre a função oculares</legend>
                                <div class="row-fluid">
                                    <div class="span8">
                                        <div class="row-fluid">
                                            <div class="span8">
                                                <label>
                                                    <input type="radio" name="olhinho_conclusao_normal" id="olhinho_conclusao_normal" value="1" />
                                                    Sugestiva de função visual normal
                                                </label>
                                            </div>
                                        </div>
                                        <div class="row-fluid">
                                            <div class="span8">
                                                <label>
                                                    <input type="radio" name="olhinho_conclusao_normal" id="olhinho_conclusao_anormal" value="2" />
                                                    Sugestiva de função visual anormal
                                                </label>
                                            </div>
                                        </div>
                                        <!--
                                        <div class="row-fluid">
                                                <div class="span4">
                                                        <label>
                                                                <input type="radio" name="olhinho-reteste-ok" id="olhinho_reteste_ok" value="3" />
                                                                Sugerido reteste em
                                                        </label>
                                                </div>
                                                <div class="span2">
                                                        <input type="text" name="olhinho-reteste-data" id="olhinho_reteste_data"  />
                                                </div>
                                        </div>
                                        -->
                                    </div>
                                    <div class="span3">
                                        <a href="#" class="consulta-link"> Últimos Exames:</a><p></p>
                                        <select onchange="consultasTela.escolheDataOlhinho();" id="olho_ultimos_exames">
                                        </select>
                                    </div>
                                </div>
                            </fieldset>
                        </div>
                        <br>
                        <div class="span3">
                            <ul class="thumbnails">
                                <li>
                                    <a href="#" class="btn btn-imprimir" id="olhinho-consulta-imprimir" ><i class="icon-print"></i> Imprimir </a>
                                </li>
                                <li id="olho_botao_gravar">
                                    <a href="#" id="olho_botao_link" class="btn btn-gravar">  </a>
                                </li>
                                <li>
                                    <a href="#" class="btn btn-gravar" onClick="consultasTela.SelectedOlhoObj.limpaModalOlhinho();" ><i class="icon-inbox"></i> Novo </a>
                                </li>
                            </ul>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>

<!-- ===================FIM MODAL CONSULTA OLHINHO ====================-->

<!-- ===================== MODAL CONSULTA ORELHINHA ====================-->
<div id="boxes-orelhinha_1" class="modal modal-orelhinha_1 hide fade" style="top: 35%;">
    <div id="dialog-orelhinha_1" class=" modal-body-orelhinha_1" style="width: 970px;">
        <div><a href="#" id="fechar" class="close" />Fechar X</a>
            <h3 class="titulo">Consulta Orelhinha-1 </h3>
            <div class="row-fluid">
                <fieldset class="table-bordered">
                    <legend>Resultados</legend>
                    <div class="row-fluid" >
                        <label><b>Emissões otoacústicas evocadas estimulo Transiente</b></label>
                        <div class="span6">
                            <fieldset class="table-bordered">
                                <legend>OD:</legend>
                                <div class="row-fluid">
                                    <div class="span3">
                                        <div class="span6">
                                            <label>TEOAE: </label>
                                        </div>
                                        <div class="span5">
                                            <input id="orelhinha1_tahoe_od" type="text" />
                                        </div>
                                    </div>
                                    <div class="span3">
                                        <div class="span6">
                                            <label>NOISE: </label>
                                        </div>
                                        <div class="span5">
                                            <input id="orelhinha1_noise_od" type="text" />
                                        </div>
                                    </div>
                                    <div class="span2">
                                        <label >Frequências</label>
                                    </div>
                                    <div class="span2">
                                        <select id="orelhinha1_frequencia_od">
                                            <option></option>
                                            <option value ="1">1,0</option>
                                            <option value ="2" >1,5</option>
                                            <option value ="3">2,0</option>
                                            <option value ="4">3,0</option>
                                            <option value ="5">4,0</option>
                                        </select>
                                    </div>
                                </div>
                            </fieldset>
                        </div>
                        <div class="span5" >
                            <fieldset class="table-bordered" style="width: 400px;">
                                <legend>OE:</legend>
                                <div class="row-fluid">
                                    <div class="span3">
                                        <div class="span6">
                                            <label>TEOAE: </label>
                                        </div>
                                        <div class="span5">
                                            <input id="orelhinha1_tahoe_oe" type="text" />
                                        </div>
                                    </div>
                                    <div class="span3">
                                        <div class="span6">
                                            <label>NOISE: </label>
                                        </div>
                                        <div class="span5">
                                            <input id="orelhinha1_noise_oe" type="text" />
                                        </div>
                                    </div>
                                    <div class="span2">
                                        <label >Frequências:</label>
                                    </div>
                                    <div class="span2" style="margin-left: 15px;">
                                        <select id="orelhinha1_frequencia_oe">
                                            <option></option>
                                            <option value ="1">1,0</option>
                                            <option value ="2">1,5</option>
                                            <option value ="3">2,0</option>
                                            <option value ="4">3,0</option>
                                            <option value ="5">4,0</option>
                                        </select>
                                    </div>
                                </div>
                            </fieldset>
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="row-fluid">
                <fieldset class="table-bordered">
                    <legend>Meato acústico externo</legend>
                    <div class="row-fluid">
                        <div class="span1">
                            <label>OD:</label>
                        </div>
                        <div class="span2">
                            <select id="orelhinha1_meato_od">
                                <option></option>
                                <option value="1">Normal</option>
                                <option value="0">Anormal</option>
                            </select>
                        </div>
                        <div class="span1">
                            <label>OE:</label>
                        </div>
                        <div class="span2">
                            <select id="orelhinha1_meato_oe">
                                <option></option>
                                <option value="1">Normal</option>
                                <option value="0">Anormal</option>
                            </select>
                        </div>
                        <div class="span1"></div>
                        <label><b>Responsivo à voz Materna/Paterna</b></label>
                        <div class="span2">
                            <label>Localização</label>
                        </div>
                        <div class="span2">
                            <select id="orelhinha1_localizacao">
                                <option></option>
                                <option value="N">Não Realizado</option>
                                <option value="D">Direta</option>
                                <option value="I">Indireta</option>
                            </select>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <label><b>Avaliação de comportamento auditivo</b></label>
                        <div class="span2">
                            <select id="orelhinha1_avaliacao_01">
                                <option value=""></option>
                                <option value="Presente">Presente</option>
                                <option value="Ausente">Ausente</option>
                                <option value="Duvidoso">Duvidoso</option>
                            </select>
                        </div>
                        <div class="span2">
                            <select id="orelhinha1_avaliacao_02">
                                <option value=""></option>
                                <option value="Atencao">Atenção</option>
                                <option value="Procura">Procura</option>
                            </select>
                        </div>
                        <div class="span2">
                            <select id="orelhinha1_avaliacao_03">
                                <option value=""></option>
                                <option value="Nao Realizado">Não Realizado</option>
                                <option value="Sim">Sim</option>
                                <option value="Nao">Não</option>
                            </select>
                        </div>
                        <div class="span2">
                            <select id="orelhinha1_avaliacao_04">
                                <option value=""></option>
                                <option value="Nao Realizado">Não Realizado</option>
                                <option value="Direita">Direita</option>
                                <option value="Esquerda">Esquerda</option>
                                <option value="Para cima">Para cima</option>
                            </select>
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="row-fluid">
                <fieldset class="table-bordered">
                    <legend>Observações</legend>
                    <textarea class="medidatextarea" id="orelhinha1_observacoes" placeholder="Observações"></textarea>
                </fieldset>
            </div>
            <div class="row-fluid">
                <fieldset class="table-bordered">
                    <legend>Conclusão</legend>
                    <div class="span9" >
                        <div class="row-fluid">
                            <label ><b>Este exame não avalia a função  do tronco cerebral</b></label>
                            <div class="span7" id="O1-conclusao">
                                <div class="row-fluid">
                                    <div class="span10">
                                        <label>
                                            <input type="checkbox" id="orelhinha1_conclusao" value="1"/>
                                            Sugestiva de função coclear presente bilateralmente
                                        </label>
                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <div class="span7">
                                        <label>
                                            <input type="checkbox" id="O1-check-reavaliacao" value="reteste" />
                                            Sugerido reavaliação auditiva em
                                        </label>
                                    </div>
                                    <div class="span1">
                                        <input type="text" id="O1-reavaliacao2" name="data-reteste2"/>
                                    </div>
                                    <div class="span1"> </div>
                                    <div class="span2">
                                        <input type="text" id="O1-reavaliacao" name="data-reteste"/>
                                    </div>
                                </div>
                            </div>
                            <div class="span4">
                                <a class="btn"> Anamnese</a><p></p>
                                <div>
                                    <a href="#" class="consulta-link"> Últimos Exames:</a><p></p>
                                    <select onchange="consultasTela.escolheDataOrelhinha1();" id="orelha1_ultimos_exames">
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div><br>
                    <div class="span2">
                        <ul class="thumbnails">
                            <li>
                                <a href="#" class=" btn btn-imprimir" ><i class="icon-print"></i> Imprimir </a>
                            </li>
                            <li id="orelha1_botao_gravar">
                                <a href="#" id="orelha1_botao_link" class="btn btn-gravar">  </a>
                            </li>
                            <li>
                                <a href="#" class="btn btn-gravar" onClick="consultasTela.SelectedOrelha1Obj.limpaModalOrelhinha1();" ><i class="icon-inbox"></i> Novo </a>
                            </li>
                        </ul>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
</div>

<!-- ===================FIM MODAL CONSULTA ORELHINHA====================-->

<!-- ===================== MODAL CONSULTA CORAÇÃOZINHO====================-->
<div id="boxes-coracaozinho" class="modal modal-coracaozinho hide fade" style="top: 35%;">
    <div id="dialog-coracaozinho" class=" modal-body-coracaozinho" style="width: 970px;">
        <div><a href="#" id="fechar" class="close" />Fechar X</a>
            <h2 class="titulo">Consulta Coraçãozinho </h2>
            <hr style="margin-top: -4px;"/>
            <div class="row-fluid">
                <fieldset class="table-bordered">
                    <legend>Resultados do Teste do coraçãozinho</legend>
                    <div class="span3">
                        <fieldset class="table-bordered">
                            <legend> Mão direita %</legend>
                            <div class="row-fluid">
                                <div class="span10">
                                    <input type="text" id="coracao-mao-direita" />
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    <div class="span3">
                        <fieldset class="table-bordered">
                            <legend> Pé %</legend>
                            <div class="row-fluid">
                                <div class="span10">
                                    <input type="text" id="coracao-pe" />
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    <div class="span3">
                        <fieldset class="table-bordered">
                            <legend> Diferença %</legend>
                            <div class="row-fluid">
                                <div class="span10">
                                    <input type="text" id="coracao-diferenca" />
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    <div class="span2">
                        <a ONCLICK="consultasTela.SelectedCoracaoObj.imprimeListaMedicos();" class="btn"> Listagem de médicos </a>
                    </div>
                </fieldset>
            </div>
            <div class="row-fluid">
                <fieldset class="table-bordered">
                    <legend>Anotações</legend>
                    <div class="row-fluid">
                        <fieldset class="table-bordered">
                            <legend>QP</legend>
                            <div id="coracao-QP">
                                <div class="row-fluid">
                                    <?php
                                    $i = 1;
                                    foreach (anotacoesQpCoracaozinho() as $x) {
                                        ?>
                                        <div class="span4">
                                            <label>
                                                <input type="checkbox" coracao_qp_nome="<?php echo $x['nome']; ?>" name="coracao_qp[]" id="<?php echo "coracao_QP_" . $x['id']; ?>" value="<?php echo $x['id']; ?>"/>
                                                <?php echo $x['nome'] ?>
                                            </label>
                                        </div>
                                        <?php
                                        if (!($i % 3) && $i != 0) {
                                            echo "</div><div class='row-fluid'>";
                                            $i = 0;
                                        }
                                        $i++;
                                    }
                                    ?>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    <div class="row-fluid">
                        <fieldset class="table-bordered">
                            <legend>HF</legend>
                            <div class="tab-pane " id="hf-c" >
                                <div id="coracao-HF">
                                    <div class="row-fluid">
                                        <div class="span12">
                                            <?php
                                            $i = 1;
                                            foreach (anotacoesHfCoracaozinho() as $x) {
                                                if ($x['id'] == 7) {
                                                    echo "<div class='span10'>";
                                                } else {
                                                    echo "<div class='span4'>";
                                                }
                                                ?>
                                                <label>
                                                    <input type="checkbox" coracao_hf_nome="<?php echo $x['nome']; ?>" name="coracao_hf[]" id="<?php echo 'coracao_HF_' . $x['id']; ?>" value="<?php echo $x['id']; ?>" />
                                                    <?php echo $x['nome']; ?>
                                                </label>
                                            </div>
                                            <?php
                                            if (!($i % 3) && $i != 0) {
                                                echo "</div><div class='row-fluid'>";
                                                $i = 0;
                                            }
                                            ?>
                                            <?php
                                            $i++;
                                        }
                                        ?>
                                    </div>
                                </div>
                        </fieldset>
                    </div>
                    <div class="row-fluid">
                        <div class="span6">
                            <fieldset class="table-bordered">
                                <legend> Outros exames e achados</legend>
                                <textarea class="medidatextareaabas" id="coracao_outros_exames" placeholder="Outros Exames"></textarea>
                            </fieldset>
                        </div>
                        <div class="span6">
                            <fieldset class="table-bordered">
                                <legend>Observações</legend>
                                <textarea class="medidatextareaabas" id="coracao-observacoes" placeholder="Observações"></textarea>
                            </fieldset>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span9" >
                            <fieldset class="table-bordered">
                                <legend>Conclusões sobre o teste do coraçãozinho :</legend>
                                <div class="row-fluid">
                                    <div class="span8" id="coracao-conclusao">
                                        <div class="row-fluid">
                                            <div class="span8">
                                                <label>
                                                    <input type="radio" coracao_conclusao_nome="Sugestiva de oximetria de pulso normal" id="coracao-conclusao1" name="coracao_conclusao" value="normal" />
                                                    Sugestiva de oximetria de pulso normal
                                                </label>
                                            </div>
                                        </div>
                                        <div class="row-fluid">
                                            <div class="span8">
                                                <label>
                                                    <input type="radio" coracao_conclusao_nome="Sugestiva de oximetria de pulso anormal" id="coracao-conclusao1" name="coracao_conclusao" value="anormal" />
                                                    Sugestiva de oximetria de pulso anormal
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="span3">
                                        <a href="#" class="consulta-link"> Últimos Exames:</a><p></p>
                                        <select onchange="consultasTela.escolheDataCoracaozinho();" id="coracao_ultimos_exames">
                                        </select>
                                    </div>
                                </div>
                            </fieldset>
                        </div><br>
                        <div class="span3">
                            <ul class="thumbnails">
                                <li>
                                    <a href="#" id="coracao_botao_imprimir" class="btn btn-imprimir" ><i class="icon-print"></i> Imprimir </a>
                                </li>
                                <li id="coracao_botao_gravar">
                                    <a href="#" id="coracao_botao_link" class="btn btn-gravar">  </a>
                                </li>
                                <li>
                                    <a href="#" class="btn btn-gravar" onClick="consultasTela.SelectedCoracaoObj.limpaModalCoracaozinho();" ><i class="icon-inbox"></i> Novo </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
</div>

<!-- =================== FIM MODAL CONSULTA CORACAOZINHO ====================-->

<!-- ===================== MODAL CONSULTA LINGUINHA====================-->
<div id="boxes-linguinha" class="modal modal-linguinha hide fade" style="top: 35%;">
    <div id="dialog-linguinha" class=" modal-body-linguinha"  style="width: 970px;">
        <div><a href="#" id="fechar" class="close" />Fechar X</a>
            <h2 class="titulo">Consulta Linguinha </h2>
            <hr style="margin-top: -4px;"/>
            <div class="row-fluid">
                <fieldset class="table-bordered">
                    <legend>Anotações</legend>
                    <div class="row-fluid">
                        <fieldset class="table-bordered">
                            <legend>QP</legend>
                            <div class="row-fluid">
                                <div class="span4">
                                    <?php
                                    $linguaQp = anotacoesQpLinguinha();
                                    $str_click = '';
                                    for ($i = 0; $i < 5; $i++) {
                                        $x = $linguaQp[$i];
                                        if ($x['id'] == 2) {
                                            $str_click = 'onchange="consultasTela.ativaLinguaOpcoes();"';
                                        }
                                        ?>
                                        <label>
                                            <input type="checkbox" <?php echo $str_click; ?> linguinha_qp_descricao="<?php echo $x['nome']; ?>" name="linguinha_qp[]" id="<?php echo "linguinha_qp_" . $x['id']; ?>" value="<?php echo $x['id']; ?>"  />
                                            <?php echo $x['nome'] ?>
                                        </label>
                                        <?php
                                        unset($str_click);
                                    }
                                    ?>

                                </div>
                                <div class="span4" id="lingua_opcoes" style="display:none">
                                    <fieldset class="table-bordered">
                                        <legend>Dificuldade na amamentação</legend>
                                        <?php
                                        for ($i = 5; $i < count($linguaQp); $i++) {
                                            $x = $linguaQp[$i];
                                            ?>
                                            <label>
                                                <input type="checkbox" linguinha_qp_descricao="<?php echo $x['nome']; ?>" name="linguinha_qp[]" id="<?php echo "linguinha_qp_" . $x['id']; ?>" value="<?php echo $x['id']; ?>" />
                                                <?php echo $x['nome']; ?>
                                            </label>
                                            <?php
                                        }
                                        ?>
                                    </fieldset>
                                </div>

                            </div>
                        </fieldset>
                    </div>
                    <div class="row-fluid">
                        <div class="span6">
                            <fieldset class="table-bordered">
                                <legend> Outros exames e achados</legend>
                                <textarea class="medidatextareaabas" id="linguinha_outros_exames" placeholder="Outros Exames"></textarea>
                            </fieldset>
                        </div>
                        <div class="span6">
                            <fieldset class="table-bordered">
                                <legend>Observações</legend>
                                <textarea class="medidatextareaabas" id="linguinha_observacoes" placeholder="Observações"></textarea>
                            </fieldset>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <fieldset class="table-bordered">
                            <legend>Resultados do Teste da linguinha</legend>
                            <div class="span11">
                                <div class="span3">
                                    <label>
                                        <input type="checkbox" linguinha_resultado_nome="Freio lingual normal" name="linguinha-resultado[]" id="linguinha_result_freio_ling_normal" value="1" />
                                        Freio lingual normal
                                    </label>
                                </div>
                                <div class="span3">
                                    <label>
                                        <input type="checkbox" linguinha_resultado_nome="Freio lingual curto" name="linguinha-resultado[]" id="linguinha_result_freio_ling_curto" value="1" />
                                        Freio lingual curto
                                    </label>
                                </div>
                                <div class="span3">
                                    <label>
                                        <input type="checkbox" linguinha_resultado_nome="Inserção anteriorizada" name="linguinha-resultado[]" id="linguinha_result_insercao_anter" value="1" />
                                        Inserção anteriorizada
                                    </label>
                                </div>
                                <div class="span3">
                                    <label>
                                        <input type="checkbox" linguinha_resultado_nome="Anquiloglossia" name="linguinha-resultado[]" id="linguinha_result_anquiloglossia" value="1" />
                                        Anquiloglossia
                                    </label>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    <div class="row-fluid">
                        <div class="span9" >
                            <fieldset class="table-bordered">
                                <legend>Conclusões sobre o teste da linguinha :</legend>
                                <div class="row-fluid">
                                    <div class="span8" id="linguinha-conclusao">
                                        <div class="row-fluid">
                                            <div class="span8">
                                                <label>
                                                    <input type="radio" linguinha_conclusao_nome="Normal" name="linguinha_conclusao" id="linguinha_conclusao_normal" value='1' />
                                                    Normal
                                                </label>
                                            </div>
                                        </div>
                                        <div class="row-fluid">
                                            <div class="span6">
                                                <label>
                                                    <input type="radio" linguinha_conclusao_nome="Anormal" name="linguinha_conclusao" id="conclusao_duvida" value='2'/>
                                                    Gera dúvida-reavaliação em :
                                                </label>
                                            </div>
                                            <div class="span2">
                                                <input type="text" id="linguinha_reavaliacao"/>
                                            </div>
                                        </div>
                                        <div class="row-fluid">
                                            <div class="span11">
                                                <label>
                                                    <input type="radio" name="linguinha_conclusao" id="linguinha_conclusao_alteracao" value='3' />
                                                    Alteração - Encaminhada para acompanhamento especializado
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="span3">
                                        <a href="#" class="consulta-link"> Últimos Exames:</a><p></p>
                                        <select onchange="consultasTela.escolheDataLinguinha();" id="lingua_ultimos_exames">
                                        </select>
                                    </div>
                                </div>
                            </fieldset>
                        </div><br>
                        <div class="span3">
                            <ul class="thumbnails">
                                <li>
                                    <a href="#" id="lingua_botao_imprimir" class=" btn btn-imprimir" ><i class="icon-print"></i> Imprimir </a>
                                </li>
                                <li id="lingua_botao_gravar">
                                    <a href="#" id="lingua_botao_link" class="btn btn-gravar">  </a>
                                </li>
                                <li>
                                    <a href="#" class="btn btn-gravar" onClick="consultasTela.SelectedLinguaObj.limpaModalLinguinha();" ><i class="icon-inbox"></i> Novo </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
</div>
<!-- ===================FIM MODAL CONSULTA Linguinha====================--> 

<!-- ===================== MODAL CONSULTA ORELHINHA 2====================--> 
<div id="boxes-orelhinha_2" class="modal modal-orelhinha_2 hide fade" style="top: 35%;">
    <div id="dialog-orelhinha_2" class=" modal-body-orelhinha_2"  style="width: 970px;">
        <div><a href="#" id="fechar" class="close" />Fechar X</a>
            <h2 class="titulo">Consulta Orelhinha 2 </h2>
            <hr style="margin-top: -4px;"/>
            <div class="row-fluid">
                <fieldset class="table-bordered">
                    <legend>Conclusão :</legend>
                    <div class="row-fluid">
                        <label>Emissões otoacústicas evocadas estimulo Transiente</label>
                        <div class="span6">
                            <fieldset class="table-bordered" style="margin-left: -13px;">
                                <legend>OD:</legend>
                                <div class="row-fluid">
                                    <div class="span10">
                                        <select id="orelhinha2_conclusao_od">
                                            <option></option>
                                            <?php foreach (listaConclusaoOrelinha2('od') as $result) { ?>
                                                <option conclusao_od_nome="<?php echo $result['nome']; ?>" value="<?php echo $result['id']; ?>" > <?php echo $result['nome']; ?> </option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </fieldset>
                        </div>
                        <div class="span5">
                            <fieldset class="table-bordered" style="width: 400px;">
                                <legend> OE :</legend>
                                <div class="row-fluid">
                                    <div class="span10">
                                        <select id="orelhinha2_conclusao_oe">
                                            <option></option>
                                            <?php foreach (listaConclusaoOrelinha2('oe') as $result) { ?>
                                                <option conclusao_oe_nome="<?php echo $result['nome']; ?>" value="<?php echo $result['id'] ?>"> <?php echo $result['nome']; ?> </option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </fieldset>
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="row-fluid">
                <fieldset class="table-bordered">
                    <legend>Anotações</legend>
                    <div class="row-fluid">
                        <fieldset class="table-bordered">
                            <legend>Equipamento</legend>
                            <div class="span4">
                                <label>Equipamento utilizado no teste:</label>
                            </div>
                            <div class="span4">
                                <select id="orelhinha2_equipamento">
                                    <option></option>
                                    <?php foreach (listar('equipamentos_teste', '*') as $result) { ?>
                                        <option equipamento_nome="<?php echo $result['nome']; ?>" value="<?php echo $result['id'] ?>"> <?php echo $result['nome']; ?> </option>
                                    <?php } ?>
                                </select>
                            </div>
                        </fieldset>
                    </div>
                    <div class="row-fluid">
                        <fieldset class="table-bordered">
                            <legend>Meato acústico externo</legend>
                            <div class="span1">
                                <label>OD:</label>
                            </div>
                            <div class="span4">
                                <select id="orelhinha2_meato_od">
                                    <option></option>
                                    <option value="1">Sem Obstrução</option>
                                    <option value="0">Com Obstrução</option>
                                </select>
                            </div>
                            <div class="span1">
                                <label>OE:</label>
                            </div>
                            <div class="span4">
                                <select id="orelhinha2_meato_oe">
                                    <option></option>
                                    <option value="1">Sem Obstrução</option>
                                    <option value="0">Com Obstrução</option>
                                </select>
                            </div>
                        </fieldset>
                    </div>
                    <div class="row-fluid">
                        <fieldset class="table-bordered">
                            <legend>Resultado :</legend>
                            <div class="span3">
                                <label>Reflexo cócleo palpebral:</label>
                            </div>
                            <div class="span4">
                                <select id="orelhinha2_cocleo">
                                    <option></option>
                                    <?php foreach (listar('orelhinha2_resultado_cocleo', '*') as $result) { ?>
                                        <option resultado_cocleo_nome="<?php echo $result['nome']; ?>" value="<?php echo $result['id'] ?>"> <?php echo $result['nome']; ?> </option>
                                    <?php } ?>
                                </select>
                            </div>
                        </fieldset>
                    </div>
                    <div class="row-fluid">
                        <fieldset class="table-bordered">
                            <legend>Observações</legend>
                            <textarea class="medidatextareaabas" id="orelhinha2_observacoes" placeholder="Observações"></textarea>
                        </fieldset>
                    </div>
                    <div class="row-fluid">
                        <div class="span9" >
                            <fieldset class="table-bordered">
                                <legend>Reteste :</legend>
                                <div class="row-fluid">
                                    <label ><b>Este exame não avalia a função do tronco cerebral</b></label>
                                    <div class="span8" id="O2-conclusao">
                                        <div class="row-fluid">
                                            <div class="span10">
                                                <label>
                                                    <input type="checkbox" name="orelhinha2_conclusao" id="orelhinha2_conclusao" value="1" />
                                                    Sugestiva de função coclear presente bilateralmente
                                                </label>
                                            </div>
                                        </div>
                                        <div class="row-fluid">
                                            <div class="span7">
                                                <label>
                                                    <input type="checkbox" name="O2-conclusao" id="O2-check-reavaliacao" value="2" />
                                                    Sugerido reavaliação auditiva aos
                                                </label>
                                            </div>
                                            <div class="span2">
                                                <input type="text" name="" id="O2-reavaliacao" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="span3">
                                        <a href="#" class="consulta-link"> Últimos Exames:</a><p></p>
                                        <select onchange="consultasTela.escolheDataOrelhinha2();" id="orelha2_ultimos_exames">
                                        </select>
                                    </div>
                                </div>
                            </fieldset>
                        </div><br>
                        <div class="span3">
                            <ul class="thumbnails">
                                <li>
                                    <a href="#" id="orelha2_botao_imprimir" class=" btn btn-imprimir" ><i class="icon-print"></i> Imprimir </a>
                                </li>
                                <li id="orelha2_botao_gravar">
                                    <a href="#" id="orelha2_botao_link" class="btn btn-gravar">  </a>
                                </li>
                                <li>
                                    <a href="#" class="btn btn-gravar" onClick="consultasTela.SelectedOrelha2Obj.limpaModalOrelhinha2();" ><i class="icon-inbox"></i> Novo </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
</div>
<!-- ================================ FIM MODAL CONSULTA ORELHINHA 2====================-->

<!--================================ MODAL Hipotese diagnostica ==============================
  =============================================================================================-->
<div id="boxes-hipotesediagnostica" class="modal modal-hipotesediagnostica hide fade" style="top: 35%;">
    <div id="dialog-hipotesediagnostica" class=" modal-body-hipotesediagnostica"  style="width: 950px;" >
        <div id=""><a href="#" id="fechar" class="close" />Fechar X</a>
            <h3 class="titulo">Hípotese Diagnostíca</h3>
            <hr>
            <form class="form-hipotesediagnostica" action="" method="post">
                <div class="row-fluid">
                    <div class="span7">
                        <div class="row-fluid">
                            <div class="span4">
                                <label class="abas-consulta">Médico:</label>
                            </div>
                            <div class="span8 mrg-lef" >
                                <select id="medico-hipotese" onchange="limparModalHipoteses();
                                        filtraHipotese();">
                                    <option></option>
                                    <?php
                                    foreach (buscaTodosMedicos() as $medico) {
                                        ?>
                                        <option value="<?php echo $medico['id']; ?>" >
                                            <?php echo $medico['nome']; ?>
                                        </option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div><br>
                        <div class="row-fluid">
                            <div class="span2">
                                <label ><a href="#"  onclick="criaCID10();
                                        abrir_modal('boxes-cid10');" class="consulta-link"><b>CID 10</b></a></label>
                            </div>
                            <div class="span2">
                                <label class="abas-consulta">Pesquisar:</label>
                            </div>
                            <div class="span8  mrg-lef" >
                                <input type="text" id="filtro-hipotese" class="" name="" onkeyup="filtraHipotese();">
                            </div>
                        </div>
                    </div>
                    <div class="span3">
                        <ul class="thumbnails">
                            <li class="span4 option-butoes">
                                <div class="row-fluid" >
                                    <a href="#" class="btn btn-cancelar " onClick="defineHipotese()" ><i class="icon-ok"></i> OK</a>                
                                </div><br>
                                <div class="row-fluid" >
                                    <a href="#" class="btn btn-cancelar" onClick="cancelaHipoteses()" ><i class="icon-remove"></i> Cancelar</a>                
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </form>
        </div>
        <hr style="margin-top: -15px;">
        <div class="row-fluid">
            <div class="table" id="tabela_hipotesediagnostica" style="height: 250px; overflow: scroll;">
                <div class="active">
                    <table cellpadding="0" cellspacing="0" border="0"  class="table table-striped table-bordered table-condensed" >
                        <thead>
                            <tr id='0' class="doencaRow">
                                <th>Doenças</th>
                            </tr>
                        </thead>
                        <tbody id="tabela_HD_doencas">
                            <?php foreach (buscaDoencas() as $doenca) { ?>
                                <tr id='<?php echo $doenca['id'] ?>' value='$doenca[codigo]' name='table-color' class='dayhead doencaRow'>
                                    <th align="center"> 
                                        <input type="checkbox" name="<?php echo $doenca['id'] ?>" id="hipoteses" value="<?php echo $doenca['codigo'] . " - " . utf8_encode($doenca['nome']); ?>" onChange="atualizaTextareaHipotese()" />
                                        <?php echo utf8_encode($doenca['nome']); ?>
                                    </th>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                    <ul id="list-menu-doencas" class="dropdown-menu contextmenu" role="menu" aria-labelledby="dropdownMenu">
                        <li><a tabindex="-1" onclick="atualHipot.marcarFavorito();">Marcar Favorito</a></li>
                        <li><a tabindex="-1" onclick="atualHipot.desmarcarFavorito();">Desmarcar Favorito</a></li>
                        <li><a tabindex="-1" onclick="atualHipot.novaHipotese();">Novo</a></li>
                        <li><a tabindex="-1" onclick="atualHipot.editarHipotese();">Editar</a></li>
                        <li><a tabindex="-1" onclick="atualHipot.removerHipotese();">Remover</a></li>
                    </ul>
                    <hr/>
                </div>
            </div>
        </div>
        <div class="row-fluid mrg-lef" >
            <fieldset class="table-bordered">
                <legend>
                    <b>Incluir na HD  atual</b>
                </legend>
                <div class="row-fluid">
                    <textarea style="width: 920px; height: 130px" id="modal-texto-hipotese" ></textarea>
                </div>
            </fieldset>
        </div>
    </div>
</div>
<!--================================ FIM MODAL Hipotese diagnostica============
  ===========================================================================-->
<!--================ MODAL Hipotese Editar Doenca =============================
  ===========================================================================-->
<div id="modal-inserirhipotese" class="modal hide fade" style="width:700px;">
    <div class="modal-header">
        Inserir/Editar
        <button id="fechar-modal-inserirhipotese" type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    </div>        
    <div>
        <p></p>
        <input type="text" style="overflow: auto; width: 690px; height: 20px" placeholder="codigo" class="modal-body" id ="cod-modal-inserirhipotese" />
        <p></p>
        <input type="text" style="overflow: auto; width: 690px; height: 20px" placeholder="Novo texto" class="modal-body" id ="text-modal-inserirhipotese" />
        <p></p>
    </div>
    <div class="modal-footer">            
        <a id="salvar-modal-inserirhipotese" class="btn btn-primary">Salvar</a>
    </div>
</div>
<!--================================ FIM MODAL Hipotese Editar Doenca==========
  ===========================================================================-->
<!--================ MODAL CID10 ======================================
  ===========================================================================-->
<div id="boxes-cid10" class="modal modal-cid10 hide fade" style="top: 35%;">
    <div id="dialog-cid10" class=" modal-body-cid10" style="width: 970px;"  >
        <div id=""><a href="#" id="fechar" class="close" />Fechar X</a>
            <h2 class="titulo">CID-10</h2>
            <hr>
            <form class="form-cid10" action="" method="post">
                <div class="row-fluid">
                    <div class="span6">
                        <div class="table" id="tabela_cid10" style="height: 400px; overflow: auto">
                            <div class="active">
                                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed">
                                    <thead>
                                        <tr>
                                            <th>Descrição da CID</th>
                                        </tr>
                                    </thead>
                                    <tbody id="tabela-lista-cid10" >

                                    </tbody>
                                </table>
                                <hr/>
                            </div>
                        </div>
                    </div>
                    <div class="span6">
                        <!--<fieldset class="table-bordered">-->
                        <legend><b>Filtrar</b></legend>
                        <div class="row-fluid">
                            <div class="span3 abas-consulta">Nomeclatura:</div>
                            <div class="span8">
                                <input type="text" name="" id="filtro-cid10" onchange="filtraCID10();" />
                            </div>
                        </div>
                        <!--						</fieldset><br>-->
                        <div class="row-fluid">
                            <div class="span11">
                                    <!--<textarea class="textarea-cid10" id="modal-texto-cid10" class="span11" ></textarea>-->
                                <div class="row-fluid">
                                    <div class="span3 ">
                                        <a href="#" onclick="defineCID10();" class="btn"><i class="icon-ok"></i>OK</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!--================= FIM MODAL CID10 =================================
  ===========================================================================-->

<!--================ MODAL Prescricoes ======================================
  ===========================================================================-->
<div id="boxes-prescricoes" class="modal modal-prescricoes hide fade" style="top: 35%;">
    <div id="dialog-prescricoes" class=" modal-body-prescricoes" style="width: 970px;"  >
        <div id=""><a href="#" id="fechar" class="close" />Fechar X</a>
            <h2 class="titulo">Prescrições</h2>
            <hr>
            <div class="row-fluid">
                <div class="span4">
                    <div class="table" style="height: 520px; overflow: auto">
                        <div class="active">
                            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed">
                                <thead>
                                    <tr>
                                        <th>Título da Prescrição</th>
                                    </tr>
                                </thead>
                                <tbody id="tabela-lista-prescricoes">
                                    <?php
                                    foreach (listar("prescricoes", "*") as $prescricoes) {
                                        ?>
                                        <tr name="table-color" class='dayhead tr_prescricao_<?php echo $prescricoes['id']; ?> linhas-prescricoes'>
                                            <th align="center">
                                                <input type='checkbox' idbanco="<?php echo $prescricoes['id']; ?>" classetr="tr_prescricao_<?php echo $prescricoes['id']; ?>" name='doencasComPrescricoes' value='<?php echo $prescricoes['id']; ?> - <?php echo $prescricoes['nome'] ?>' onChange='atualizaTextareaPrescricoes()' />
                                                <?php echo $prescricoes['nome']; ?>
                                            </th>
                                        </tr>
                                        <?php
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="row-fluid">
                            <div class="span4">
                                <a href="#" onclick="abrir_modal('boxe-inserir_prescricao');" class="btn"><i class="icon-ok"></i>Adicionar</a>
                            </div>
                            <div class="span4">
                                <a href="#" onclick="editaPrescricaoModal();" class="btn"><i class="icon-ok"></i>Editar</a>
                            </div>
                            <div class="span4">
                                <a href="#" onclick="removerPrescricao();" class="btn"><i class="icon-trash"></i>Deletar</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="span8">
                    <fieldset class="table-bordered">
                        <legend><b>Médico</b></legend>
                        <div class="row-fluid">
                            <label class="abas-consulta">Mostrar prescrições do médico:</label>
                            <select id="medico-prescricoes" onchange="filtraPrescricoes();">
                                <option></option>
                                <?php foreach (buscaTodosMedicos() as $medico) { ?>
                                    <option value="<?php echo $medico['id']; ?>" >
                                        <?php echo $medico['nome']; ?>
                                    </option>
                                <?php } ?>
                            </select>
                        </div><br>
                        <div class="row-fluid">
                            <div class="span1 abas-consulta">Filtrar:</div>
                            <div class="span10">
                                <input type="text" name="" id="filtro-prescricoes"/>
                            </div>
                        </div>
                    </fieldset><br>
                    <div class="row-fluid">
                        <textarea class="textarea-prescricoes" id="modal-texto-prescricoes" ></textarea>
                        <div class="row-fluid">
                            <div class="span3 ">
                                <a href="#" onclick="definePrescricoes();" class="btn"><i class="icon-ok"></i>OK</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--================= FIM MODAL PRESCRICOES =================================
  ===========================================================================-->
<!--================ MODAL Recomendacoes ======================================
  ===========================================================================-->
<div id="boxes-recomendacoes" class="modal modal-recomendacoes hide fade" style="top: 35%;">
    <div id="dialog-recomendacoes" class=" modal-body-recomendacoes" style="width: 970px;" >
        <div id=""><a href="#" id="fechar" class="close" />Fechar X</a>
            <h2 class="titulo">Recomendações</h2>
            <hr>
            <form class="form-recomendacoes" action="" method="post">
                <div class="row-fluid">
                    <div class="span6">
                        <div class="table" id="tabela_recomendacoes"  style="height: 400px; overflow: auto" >
                            <div class="active">
                                <table cellpadding="0" cellspacing="0" border="0"  class="table table-striped table-bordered table-condensed" >
                                    <thead>
                                        <tr>
                                            <th>Título das Recomendações</th>
                                        </tr>
                                    </thead>
                                    <tbody id="Tabela_corpo_recomendacoes">
                                        <?php foreach (listar("recomendacoes", "*") as $recomend) { ?>
                                            <tr name="table-color" class='dayhead linhas-prescricoes' >
                                                <th align="center">
                                                    <input type='checkbox' name='recomendacoesDoencas' value='<?php echo $recomend['id'] ?>' onChange='atualizaTextareaRecomendacoes()' /> 
                                                    <?php echo $recomend['nome']; ?>
                                                </th>
                                            </tr>
                                        <?php } ?>
                                    </tbody>
                                </table>
                                <hr/>
                            </div>
                        </div>
                    </div>
                    <div class="span6   ">
                        <fieldset class="table-bordered">
                            <legend><b>Médico</b></legend>
                            <div class="row-fluid">
                                <label class="abas-consulta">Mostrar recomendação do médico</label>
                                <select id="medico-recomendacoes" onchange="filtraRecomendacoes();">
                                    <option></option>
                                    <?php
                                    foreach (buscaTodosMedicos() as $medico) {
                                        ?>
                                        <option value="<?php echo $medico['id']; ?>" >
                                            <?php echo $medico['nome']; ?>
                                        </option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div><br>
                            <div class="row-fluid">
                                <div class="span1 abas-consulta">Filtrar:</div>
                                <div class="span10">
                                    <input type="text" name="" id="filtro-recomendacoes" onchange="filtraRecomendacoes();"/>
                                </div>
                            </div>
                        </fieldset><br>
                        <div class="row-fluid">
                            <div class="span11">
                                <textarea class="textarea-recomendacoes" id="modal-texto-recomendacoes"></textarea>
                                <div class="row-fluid">
                                    <div class="span3 ">
                                        <a href="#" onclick="defineRecomendacoes();" class="btn"><i class="icon-ok"></i>OK</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!--================= FIM MODAL Recomendacoes =================================
  ===========================================================================-->
<!--================ MODAL Atestados ========================================
  ===========================================================================-->
<div id="boxes-atestados" class="modal modal-atestados hide fade" style="top: 35%;">
    <div id="dialog-atestados" class=" modal-body-atestados" style="width: 970px">
        <div id=""><a href="#" id="fechar" class="close" />Fechar X</a>
            <h2 class="titulo">Atestados</h2>
            <hr>
            <form class="form-atestados" action="" method="post">
                <div class="row-fluid">
                    <div class="span6">
                        <div class="table" id="tabela_atestados" style="height: 200px; overflow: auto">
                            <div class="active">
                                <table cellpadding="0" cellspacing="0" border="0"  class="table table-striped table-bordered table-condensed" >
                                    <thead>
                                        <tr>
                                            <th > Atestados</th>
                                        </tr>
                                    </thead>

                                    <tbody id="tabela-atestados">
                                        <?php foreach (buscaAtestados() as $atestado) { ?>
                                            <tr name="<?php echo $atestado['id'] ?>" id="IdAtestado" class='dayhead pointer-cursor' onClick="carregaAtestado('<?php echo utf8_encode(str_replace("'", "", $atestado['descricao'])) ?>');">
                                                <th align="center"><?php echo utf8_encode($atestado['nome']) ?></th>
                                            </tr>                                                        
                                        <?php } ?>                                                                                
                                    </tbody>

                                </table>                                
                                <hr/>
                                <ul id="list-menu-atestado" class="dropdown-menu contextmenu" role="menu" aria-labelledby="dropdownMenu">
                                    <li><a tabindex="-1" onclick="atualAtestado.flag = 1;
                                            consultasAtestado(atualAtestado)">Novo</a></li>
                                    <li><a tabindex="-1" onclick="atualAtestado.flag = 2;
                                            consultasAtestado(atualAtestado);">Editar</a></li>
                                    <li><a tabindex="-1" onclick="atualAtestado.flag = 3;
                                            consultasAtestado(atualAtestado);">Remover</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="span6">
                        <div class="row-fluid">
                            <div class="span3">
                                <ul class="thumbnails">
                                    <li class="span4 option-butoes">
                                        <div class="row-fluid" >
                                            <a href="#" class="btn btn-cancelar" onClick="defineAtestado();" ><i class=" icon-ok" ></i>OK</a>
                                        </div><br>
                                        <div class="row-fluid" >
                                            <a href="#" class="btn btn-cancelar" ><i class=" icon-remove-circle"></i>Cancelar</a>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="row-fluid">
                    <textarea class="textarea-atestados" id="modal-texto-atestado"  ></textarea>                                        
                </div>
            </form>
        </div>
    </div>
</div>
<!--================= FIM MODAL Atestados ===================================
  ===========================================================================-->
<!--================ MODAL Testes Cutaneos ==================================
  ===========================================================================-->
<div id="boxes-testescutaneos" class="modal modal-testescutaneos hide fade" style="top: 35%;">
    <div id="dialog-testescutaneos" class=" modal-body-testescutaneos"  style="width: 970px;">
        <div id=""><a href="#" id="fechar" class="close" />Fechar X</a>
            <h2 class="titulo">Testes Cutâneos</h2>
            <hr>
            <form class="form-testescutaneos" action="" method="post">
                <div class="row-fluid">
                    <div class="span12">
                        <div class="table" id="tabela-testedisponiveis" >
                            <div class="active">
                                <table cellpadding="0" cellspacing="0" border="0"  class="table table-striped table-bordered table-condensed" >
                                    <thead>
                                        <tr>
                                            <th> Testes Disponíveis</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach (listar("testes", "*") as $testes) { ?>
                                            <tr name="table-color" class='dayhead '>
                                                <th align="center">
                                                    <input id='<?php echo $testes['categoria_teste_id']?>' type='checkbox' name='testesCutaneos' value='<?php echo $testes['id'] ?> - <?php echo utf8_encode($testes['nome']) ?>' onChange='atualizaTextareaTestesCutaneos()' /> 
                                                    <?php echo $testes['nome']; ?>
                                                </th>
                                            </tr>
                                        <?php } ?>
                                    </tbody>
                                </table>
                                <hr/>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="row-fluid">
                    <div class="span12">
                        <div class="table" id="tabela-testeselecionados">
                            <div class="active">
                                <table cellpadding="0" cellspacing="0" border="0"  class="table table-striped table-bordered table-condensed" >
                                    <thead>
                                        <tr>
                                            <th> Testes Selecionados</th>
                                        </tr>
                                    </thead>
                                    <tbody id="testesCutaneosSelecionados">
                                        <tr name="table-color" class='dayhead testesCutaneosSelectionados1'>
                                            <th align="center"> </th>
                                        </tr>
                                    </tbody>
                                </table>
                                <hr/>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid" >
                        <div class="offset8">
                            <a href="#" class="btn btn-cancelar" onClick="testesCutaneosOK()"><i class=" icon-ok"></i> OK</a>      
                            <a href="#" class="btn btn-cancelar" onClick="fechar_modal('boxes-testescutaneos')" ><i class=" icon-remove-circle"></i>Cancelar</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!--================= FIM MODAL Testes Cutaneos =============================
  ===========================================================================-->
<!--================ MODAL Resultados Cutaneos ===============================
  ===========================================================================-->
<div id="boxes-resultcutaneos" class="modal-resultcutaneos hide fade" style="top: 35%;">
    <div id="dialog-resultcutaneos" class=" modal-body-resultcutaneos"  style=" background-image:  url('template/img/body-bg.png');">
        <div id=""><a href="#" id="fechar" class="close" />Fechar X</a>
            <h2 class="titulo">Resultados dos Testes Cutâneos</h2>
            <hr>
            <form class="form-resultcutaneos" action="" method="post">
                <div class="row-fluid">
                    <div class="span12">
                        <div class="table" id="tabela_resultcutaneos">
                            <div class="active">
                                <input type='hidden' id="idTesteClicado" />
                                <table cellpadding="0" cellspacing="0" border="0"  class="table table-striped table-bordered table-condensed" >
                                    <thead>
                                        <tr>
                                            <th>Antígeno</th>
                                            <th> Resultado</th>
                                            <th> Descrição</th>
                                        </tr>
                                    </thead>
                                    <tbody id="modal-resultadoTesteCutaneo">
                                    </tbody>
                                </table>
                                <hr/>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid" >
                        <a href="#" class="btn btn-cancelar" onClick="testesCutaneosResultadorOK()"><i class=" icon-ok"></i> OK</a>      
                        <a href="#" class="btn btn-cancelar" onClick="fechar_modal('boxes-resultcutaneos')"><i class=" icon-remove-circle"></i>Cancelar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!--================= FIM MODAL Resultados Cutaneos  =========================
  ===========================================================================-->
<!--================ MODAL Requisições e Encaminhamentos=======================
  ===========================================================================-->
<div id="boxes-requisicoesencaminhamento" class="modal modal-requisicoesencaminhamento hide fade" style="top: 35%;">
    <div id="dialog-requisicoesencaminhamento" class=" modal-body-requisicoesencaminhamento" style="width: 970px; height: 620px">
        <div id=""><a href="#" id="fechar" class="close" />Fechar X</a>
            <h2 class="titulo">Requisições e Encaminhamentos</h2>
            <hr>
            <form class="form-requisicoesencaminhamento" action="" method="post">
                <div class="row-fluid" >
                    <div class="offset4">
                        <a href="#" class="btn btn-cancelar" onclick="defineReqServico();" ><i class=" icon-ok"></i> OK</a>      
                        <a href="#" class="btn btn-cancelar" onclick="fechar_modal('boxes-requisicoesencaminhamento');
                                limparModalRequisicaoServico();"><i class=" icon-remove-circle"></i>Cancelar</a>
                    </div>
                </div><br>
                <div class="row-fluid" style="height: 250px; overflow: scroll" >
                    <div class="span6">
                        <!--                         ======MENU CONTEXTO TABLE ========
                                                <div  class="span5" >
                                                    <table class="table">
                                                        <tbody>
                                                            <tr>
                                                                <td class="table-menu-context">
                                                                    Teste1
                                                                </td>
                                                                <td class="table-menu-context">
                                                                    Teste2
                                                                </td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>-->

                        <!--  ======== MENU CONTEXTO TABLE -============-->
                        <div class="table" >
                            <div class="active">
                                <table cellpadding="0" cellspacing="0" border="0"  class="table table-striped table-bordered table-condensed" >
                                    <thead>
                                        <tr id='0' class="prestadorRow">
                                            <th >Prestador</th>
                                        </tr>
                                    </thead>
                                    <tbody id="tabela_Resultados_Prestador" class="table-menu-context-prestador">
                                        <?php foreach (buscaPrestador() as $prestador) { ?>
                                            <tr id="<?php echo $prestador['id']; ?>" name="table-color" class='dayhead prestadorRow' onClick="atualizaServicoPrestador();" >
                                                <th align="center"><input id="prestador" type="radio" name="prestador" value ="<?php echo $prestador['id']; ?>"> <?php echo $prestador['nome']; ?>
                                                    <?php if ($prestador['favorito'] == 1) { ?>
                                                        <img id='prestadorFavorito' name='<?php echo $prestador['id']; ?>' align='right' src='view/img/star.png' />
                                                    <?php } ?>
                                                </th>
                                            </tr>
                                        <?php } ?>
                                    </tbody>
                                    <ul id="list-menu-context-prestador" class="dropdown-menu contextmenu" role="menu" aria-labelledby="dropdownMenu">
                                        <li><a tabindex="-1" onclick="atualPrest.marcarFavorito();">Marcar Favorito</a></li>
                                        <li><a tabindex="-1" onclick="atualPrest.desmarcarFavorito();">Desmarcar Favorito</a></li>
                                        <li><a tabindex="-1" onclick="atualPrest.novoPrestador();">Novo</a></li>
                                        <li><a tabindex="-1" onclick="atualPrest.editarPrestador();">Editar</a></li>
                                        <li><a tabindex="-1" onclick="atualPrest.removerPrestador();">Remover</a></li>                                                                                
                                    </ul>
                                </table>
                                <hr/>
                            </div>
                        </div>
                    </div>
                    <div class="span6">
                        <div class="table" id="">
                            <div class="active">
                                <table cellpadding="0" cellspacing="0" border="0"  class="table table-striped table-bordered table-condensed" >
                                    <thead>
                                        <tr id='0' class="servicoRow">
                                            <th>Requisição / Indicação</th>
                                        </tr>
                                    </thead>
                                    <tbody id="tabela_Resultados_Requisicao" class="table-menu-context-requisicao">                                        
                                        <?php foreach (buscaRequisicaoServico() as $servico) { ?>
                                            <tr id="<?php echo $servico['id']; ?>" name="table-color" class='dayhead servicoRow' onClick="atualizaServicoPrestador();" >
                                                <th align="center">
                                                    <input id="reqservico" type="radio" name="reqServicos" value ="<?php echo $servico['id']; ?>" />
                                                    <?php echo $servico['nome']; ?>
                                                    <?php if ($servico['favorito'] == 1) { ?>
                                                        <img id='servicoFavorito' name='<?php echo $servico['id']; ?>' align='right' src='view/img/star.png' />
                                                    <?php } ?>
                                                </th>
                                            </tr>
                                        <?php } ?>
                                    </tbody>
                                    <ul id="list-menu-context-requisicao" class="dropdown-menu contextmenu" role="menu" aria-labelledby="dropdownMenu">
                                        <li><a tabindex="-1" onclick="atualReqs.marcarFavorito();">Marcar Favorito</a></li>
                                        <li><a tabindex="-1" onclick="atualReqs.desmarcarFavorito();">Desmarcar Favorito</a></li>
                                        <li><a tabindex="-1" onclick="atualReqs.novaRequisicao();">Novo</a></li>
                                        <li><a tabindex="-1" onclick="atualReqs.editarRequisicao();">Editar</a></li>
                                        <li><a tabindex="-1" onclick="atualReqs.removerRequisicao();">Remover</a></li>                                                                                  
                                    </ul>
                                </table>
                                <hr/>
                            </div>
                        </div>
                    </div>
                </div><br>
                <div class="row-fluid">
                    <textarea class="textarea-requisicoesencaminhamento" id="textarea-requisicao" style="height: 200px;">
                    </textarea>
                </div>
            </form>
        </div>
    </div>
</div>
<!--================= FIM MODAL Requisições e Encaminhamento==================
  ===========================================================================-->
<!--================ MODAL Editar Prestador =============================
  ===========================================================================-->
<div id="modal-editarprestador" class="modal hide fade" style="width:700px;">
    <div class="modal-header">
        Inserir/Editar
        <button id="fechar-modal-editarprestador" type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    </div>
    <div class='row-fluid'>
        <div class="table active">
            <table>
                <tbody>
                    <tr>
                <input type="text" style="overflow: auto; width: 690px; height: 20px" placeholder="Nome" class="modal-body" id ="nome-modal-editarprestador" />                        
                <p></p>
                </tr>
                <tr>
                <input type="text" style="overflow: auto; width: 690px; height: 20px" placeholder="Endereço" class="modal-body" id ="end-modal-editarprestador" />                        
                <p></p>
                </tr>
                <tr>
                <div>
                    <input type="text" style="overflow: auto; width: 190px; height: 20px" placeholder="Telefone" class="modal-body" id ="tel-modal-editarprestador" />                        
                    <p></p>
                    <input type="text" style="overflow: auto; width: 400px; height: 20px" placeholder="Email" class="modal-body" id ="email-modal-editarprestador" />                        
                    <p></p>
                </div>                            
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="modal-footer">            
        <a id="salvar-modal-editarprestador" class="btn btn-primary">Salvar</a>
    </div>
</div>
<!--================================ FIM MODAL Editar Prestador==========
  ===========================================================================-->
<!--================ MODAL Editar Requisicao =============================
  ===========================================================================-->
<div id="modal-editarrequisicao" class="modal hide fade" style="width:700px;">
    <div class="modal-header">
        Inserir/Editar
        <button id="fechar-modal-editarrequisicao" type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    </div>
    <div class='row-fluid'>
        <div class="table active">

            <input type="text" style="overflow: auto; width: 690px; height: 20px" placeholder="Nome" class="modal-body" id ="nome-modal-editarrequisicao" />                        
            <p></p>
            <textarea style="overflow: auto; width: 668px; height: 300px" class="modal-body" id ="text-modal-editarrequisicao"></textarea>

        </div>
    </div>
    <div class="modal-footer">            
        <a id="salvar-modal-editarrequisicao" class="btn btn-primary">Salvar</a>
    </div>
</div>
<!--================================ FIM MODAL Editar Requisicao==========
  ===========================================================================-->

<!--================================ MODAL PROCURAR CLIENTE===================
  ===========================================================================-->
<?php
require_once('view/recepcao/modal-procurar.phtml');
?>
<!--================================ FIM MODAL PROCURAR CLIENTE =============
============================================================================ -->
<!--================================ MODAL IMUNOTERAPIA======================
  ========================================================================== -->
<link type="text/css" rel="stylesheet" href="view/recepcao/css/index.css" />
<?php
require_once('view/recepcao/modal-imunoterapia.phtml');
?>
<!--================================ FIM MODAL IMUNOTERAPIA ==================
============================================================================ -->

<!--=================================== MODAL FICHA DE VACINA =============
    ======================================================================== -->

<div id="form-ficha-vacina">
    <!-- ID ALTERADO POR MOTIVO DE BUG NA TELA DE O ID ANTIGO ERA USADO PARA COLOCAR O MODAL -->
    <div id="ficha-vacina-xxx" class="modal-vacina hide fade">
        <div id="ficha-vac-xxx">
        </div>
    </div>
</div>

<!--=================================== FIM MODAL FICHA DE VACINA =================================================
    =============================================================================================================== -->
<!--================================ MODAL INSERIR PRESCRIÇÃO =====================================================
============================================================================================================== -->

<div id="boxe-inserir_prescricao" class="modal hide fade" style="top: 35%;">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">Fechar &times;</button>
        <h3>Inserir Prescrição</h3>
    </div>
    <div class="modal-body">
        <div class="row-fluid">
            <div class="span5">
                <label>Informe o Nome:</label>
                <input type='text' name='nome_prescricao_inserir'/>
            </div>
        </div>
    </div>
    <div class="modal-footer" id="inserir_prescricao_botao" >
        <input type='button' class="btn" value='Salvar' onclick='salvaNovaPrescricao();' name='nome_prescricao_inserir'/>
    </div>
</div>

<!--================================ FIM MODAL INSERIR PRECRIÇÃO =====================================================
============================================================================================================== -->
<!--==================================== MODAL EDITAR PRESCRIÇÕES ====================================================
  ===============================================================================================================-->
<div id="boxes-prescricoes-editar" class="modal modal-prescricoes hide fade" style="top: 35%;">
    <div id="dialog-prescricoes" class=" modal-body-prescricoes" style="width: 970px;"  >
        <div id=""><a href="#" id="fechar" class="close" />Fechar X</a>
            <h2 id="presc_titulo" class="titulo">iiiii</h2>
            <hr>
            <form class="form-prescricoes" action="" method="post">
                <div class="row-fluid">
                    <div class="span11">
                        <div class="row-fluid">
                            <textarea class="textarea-prescricoes-editar" id="modal-texto-prescricoes-editar" ></textarea>
                            <div class="row-fluid">
                                <div id="presc_botao" class="span2">
                                </div>
                                <div class="span2">
                                    <a href="#" onclick="fechar_modal('boxes-prescricoes-editar');" class="btn"><i class="icon-close"></i>Fechar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!--==================================== FIM MODAL EDITAR PRESCRICOES ==========================================
  ==============================================================================================================-->

<!--================================  MODAL BUSCA CONSULTAS POR PERÍODO ==================================================
============================================================================================================= -->

<div id="boxes-busca-consultas-periodo" class="modal modal-certificado-imu hide fade" style="top: 35%;">
    <div id="dialog-busca-consultas-periodo" class="modal-body modal-body-certificado-imu" style="width: 1024px;">
        <div id=""><a href="#" id="fechar" class="close"/>Fechar X</a>
            <h4 class="titulo">Procurar Consulta</h4>
            <hr style="margin-top: -2px;"/>
            <div class="row-fluid">
                <div class="span6">
                    <fieldset class="table-bordered">
                        <legend>Período</legend>
                        <div class="row-fluid">
                            <div class="span1">
                                <label> Início: </label>
                            </div>
                            <div class="span10">
                                <input id="consultaInicial" type="text" onblur="getdate2();" value="" />
                            </div>
                            <div class="span1">
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="span1">
                                <label> Final: </label>
                            </div>
                            <div class="span10">
                                <input id="consultafinal" onblur="getdate();" type="text" />
                            </div>
                            <div class="span1">
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="span3">
                    <div class="row-fluid">
                        <div class="span6">
                            <input onclick="consultasTela.capturaClientesporPeriodo(<?php echo $_SESSION[''] ?>)" class="btn btn-mini span10" type="button" name="" value="Mostrar" />
                        </div>
                    </div>
                    <div class="row-fluid" style="height:10px">
                    </div>
                    <div class="row-fluid">
                        <div class="span6">
                            <input class="btn btn-mini span10" onclick="fechar_modal('boxes-busca-consultas-periodo');" type="button" name="" value="Sair" />
                        </div>
                    </div>
                </div>
            </div><br><br>
            <div style="height:300px;overflow:auto" id="" class="row-fluid">
                <table cellspacing='10' class="table-striped table-bordered">
                    <thead>
                        <tr class="white">
                            <th class="titulo" align="center"> Matrícula </th>
                            <th class="titulo" align="center"> Membro </th>
                            <th class="titulo" align="center"> Nome </th>
                            <th class="titulo" align="center"> Idade </th>
                            <th class="titulo" align="center"> Data </th>
                        </tr>
                    </thead>
                    <tbody id="tbody-PesquisaClientePorPeriodo">

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!--================================  FIM MODAL BUSCA CONSULTAS POR PERÍODO =================================================
================================================================================================================= -->

<!--================================  DROPDOWN MENU IMPRIMIR =================================================
================================================================================================================= -->
<ul id="list-print" class="dropdown-menu contextmenu" role="menu" aria-labelledby="dropdownMenu">
    <li><a tabindex="-1" onclick="imprimirTexto(printTag)">Imprimir</a></li>                                       
</ul>
<!--================================  FIM DROPDOWN MENU IMPRIMIR =================================================
================================================================================================================= -->

<!--================================  DROPDOWN MENU Consulta Historico =================================================
================================================================================================================= -->
<ul id="list-menu-consultaHistorico" class="dropdown-menu contextmenu" role="menu" aria-labelledby="dropdownMenu">
    <li><a tabindex="-1" onclick="consultasTela.imprimirConsultaPadrao(1);">Imprimir</a></li>
    <li><a tabindex="-1" onclick="consultasTela.removerConsultaPadrao();">Remover</a></li>
</ul>
<!--================================  FIM DROPDOWN MENU Consulta Historico =================================================
================================================================================================================= -->

<!--============================== MODAL BUSCA CONSULTAS BOLETIM IMUNOBIOLÓGICO  ============================
============================================================================================================= -->

<div id="boxes-busca-boletim_imunobiologico" class="modal modal-boletim_imunobiologico hide fade" style="top: 35%;">
    <div id="dialog-busca-boletim_imunobiologico" class="modal-body modal-body-boletim_imunobiologico" style="width: 1024px;">
        <div>
			<a href="#" id="fechar" class="close"/>Fechar X</a>
            <h4 class="titulo">Boletim Imunobiológico</h4>
            <hr style="margin-top: -2px;"/>
            <div class="row-fluid">
                <div class="span6">
                    <fieldset class="table-bordered">
                        <legend>Período</legend>
                        <div class="row-fluid">
                            <div class="span1">
                                <label> Início: </label>
                            </div>
                            <div class="span10">
                                <input id="imunobiologico_data_inicio" type="text" value="" />
                            </div>
                            <div class="span1">
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="span1">
                                <label> Final: </label>
                            </div>
                            <div class="span10">
                                <input id="imunobiologico_data_fim" type="text" />
                            </div>
                            <div class="span1">
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="span3">
                    <div class="row-fluid">
                        <div class="span6">
							<input class="btn btn-mini span10" type="button" name="" id="botaomostrar_controleimunobiologico" onclick="buscaBoletimImunobiologico();" value="Mostrar" />
						</div>
                    </div>
                    <div class="row-fluid" style="height:10px">
                    </div>
                    <div class="row-fluid">
                        <div class="span6">
                            <input class="btn btn-mini span10" onclick="fechar_modal('boxes-busca-boletim_imunobiologico');" type="button" name="" value="Sair" />
                        </div>
                    </div>
                </div>
            </div><br><br>
            <div style="height:300px;overflow:auto" class="row-fluid">
                <table cellspacing='10' class="table-striped table-bordered">
                    <thead>
						<tr class="white">
							<th class="titulo" align="center"> Vacinações </th>
							<th class="titulo" align="center"> <1a </th>
							<th class="titulo" align="center"> 1a </th>
							<th class="titulo" align="center"> 2a </th>
							<th class="titulo" align="center"> 3a </th>
							<th class="titulo" align="center"> 4a </th>
							<th class="titulo" align="center"> 5a </th>
							<th class="titulo" align="center"> 6a </th>
							<th class="titulo" align="center"> 7a </th>
							<th class="titulo" align="center"> 8a </th>
							<th class="titulo" align="center"> 9a </th>
							<th class="titulo" align="center"> 10a </th>
							<th class="titulo" align="center"> 11a </th>
							<th class="titulo" align="center"> 12a </th>
							<th class="titulo" align="center"> 13-19 </th>
							<th class="titulo" align="center"> 20-59 </th>
							<th class="titulo" align="center"> 60> </th>
							<th class="titulo" align="center"> Total </th>
						</tr>
                    </thead>
                    <tbody id="tbody_imunobiologico">

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!--============================== FIM MODAL BUSCA CONSULTAS BOLETIM IMUNOBIOLÓGICO  ============================
================================================================================================================= -->
</body>