			</div> <!-- conteudo -->
        </div>
    </div>

	<div class="navbar navbar-fixed-bottom" >
		<div class="navbar-inner" id="status-bar">
			<div class="container">
				<div class="nav-collapse" style="margin-left: 15%;">
					<ul class="nav">
						<li ><a href="index.php?module=cadastro" ><i class="icon-user icon-white"></i> Clientes </a></li>
						<li><a href="index.php?module=ag_medica" ><i class="icon-home icon-white"></i> Agenda Médica</a></li>
						<li><a href="index.php?module=caixa" ><i class="icon-asterisk icon-white"></i> Caixa</a></li>
						<li><a href="index.php?module=consultas" ><i class="icon-user icon-white"></i>  Consultas </a></li>
						<li><a href="index.php?module=entradanf" ><i class="icon-tasks icon-white"></i> Notas Fiscais </a></li>
						<li><a href="index.php?module=encaminhamentopro" ><i class="icon-tasks icon-white"></i> Padrão Procedimentos TISS</a></li>
						
					 </ul>
				</div><!--/.nav-collapse -->
			</div>
		</div>
	</div>
</div> <!-- pagina -->

<!-- Bootstrap INICIO -->
	<script src="template/js/bootstrap-transition.js"></script>
	<script src="template/js/bootstrap-datepicker.js"></script>
	<script src="template/js/google-code-prettify/prettify.js"></script>
	<script src="template/js/bootstrap-alert.js"></script>
	<script src="template/js/bootstrap-modal.js"></script>
	<script src="template/js/bootstrap-dropdown.js"></script>
	<script src="template/js/bootstrap-scrollspy.js"></script>
	<script src="template/js/bootstrap-tab.js"></script>
	<script src="template/js/bootstrap-tooltip.js"></script>
	<script src="template/js/bootstrap-popover.js"></script>
	<script src="template/js/bootstrap-button.js"></script>
	<script src="template/js/bootstrap-collapse.js"></script>
	<script src="template/js/bootstrap-carousel.js"></script>
	<script src="template/js/bootstrap-typeahead.js"></script>
	<script src="view/js/utils.js"></script>
<!-- Bootstrap TÉRMINO -->
</body>
</html>
