<div id="wrapper" >
	<div id="login" >
		<div id="header_login">
		<h1>
			<img src="favicon.png" style="text-align: left; width: 40px;"/> Acesso ao Sistema
		</h1>
		</div>
		<p style="margin-top: -35px;">
			<label for="username" class="uname" data-icon="u" > Nome de Usuário </label>
			<input id="username" name="username" type="text" placeholder="Nome"/>
		</p>
		<p> 
			<label for="password" class="youpasswd" data-icon="p"> Sua senha </label>
			<input id="password" name="password" type="password" placeholder="ex. X8df!90EO" />
		</p>
		<p class="keeplogin">
			<input id="loginkeeping" type="checkbox" name="loginkeeping"  value="loginkeeping"/>
			<label for="loginkeeping">Desejo me Manter logado</label>
		</p>
		<p class="login button">
			<input type="submit" value="Entrar"/>
		</p>
		<p class="change_link">
			<label class="copyrigth"> Copyright © 2013 - CLIMEP - Version: x.xx </label>
			<a href="#" >Junte-se a nós</a>
		</p>
	</div>
 </div>
