<?php
$programadas = $_SESSION['fichavacina']['vacinasprogramadas'];
$cliente = $_SESSION['fichavacina']['cliente'];

$nome = $cliente['nome'];
$matricula = $cliente['matricula'];
$hoje = date('d/m/Y');

$html = "";

foreach($programadas as $prog) {

	$nomeVac = $prog['vacinaNome'];
	$data = $prog['data_prevista'];
	$html .=" <tr>
		<td class='texto5'>
			<h6>$nomeVac</h6>
		</td>
		<td class='texto5'>
			<h6>$data</h6>
		</td>
	</tr>";
}

//#header { position: fixed; top: 5px; right: 0px; height: 150px; color: black;}
$strhtml = "
<html>
	<head>
		<meta charset='utf-8'>
		<link href='css/bootstrap.css' rel='stylesheet'>
		<link href='css/pdfs.css' rel='stylesheet'>
	</head>
	<style>
		table.vaci-vacinas { margin-top: 10px; margin-left: 20px; margin-right:20px; border-collapse: collapse; }
		table.vaci-vacinas thead tr th,table.vaci-vacinas tbody tr td { border: 1px solid #000000; font-size: 6px; text-align: center; color: black; }
		table.vaci-vacinas th { background-color: #0088CC; width: 52.3px; height: 15px;}
		table.vaci-vacinas td { background-color: white; height: 25px;}

		table.tabela { border-collapse: collapse; width:710px}
		table.tabela td.texto { height: 20px; width: 410px;}
		table.tabela td.imagem { height: 45px; width: 135px;}

		imagem4 { height: 45px; width: 155px;}

		table.tabela2 { border:0px; border-collapse: collapse; width:400px}
		table.tabela2 td.datatexto { height: 10px; width: 320px;}
		table.tabela2 td.datadata { height: 10px; width: 60px;}
		table.tabela2 td.texto { height: 35px; width: 320px;}
		table.tabela2 td.matricula { height: 35px; width: 60px; text-align: right}

		table.tabela3 { border-collapse: collapse; width:800px}
		table.tabela3 td.texto3 { height: 30px; width: 425px;}
		table.tabela3 td.imagem3 { height: 45px; width: 120px;}

		table.program { border-collapse: collapse; width:200px; height:130px}
		table.program td.texto5 { width: 120px;}

		table.imagemtopo { border-collapse: collapse; width:510px; height:55px}
		table.imagemtopo td.texto5 { width: 20px;}

		.teste { margin-left: 20px; margin-right: 20px; margin-top: 10px; }
		.teste2 { margin-left: -10px; margin-right: -10px; margin-top: -10px; }

		.paragrafo {font-size: 8px; line-height:8px}

		.page-header {
			margin-left: 30px;
			border-top:2px solid #000000;
			border-bottom:2px solid #000000;
			border-left:  2px solid #000000;
			border-right: 2px solid #000000;
		}

		.page-carteirinha {
			margin-left: 10px;
			border:solid 2px #000000;
			-moz-border-radius-topleft: 39px;
			-moz-border-radius-topright:0px;
			-moz-border-radius-bottomleft:0px;
			-moz-border-radius-bottomright:39px;
			-webkit-border-top-left-radius:39px;
			-webkit-border-top-right-radius:0px;
			-webkit-border-bottom-left-radius:0px;
			-webkit-border-bottom-right-radius:39px;
			border-top-left-radius:39px;
			border-top-right-radius:0px;
			border-bottom-left-radius:0px;
			border-bottom-right-radius:39px;
		}
	</style>
<body>
";

$strhtml .= utf8_decode('
        <div id="header">
            <div class="row-fluid">
                <div class="span6" align="center">
                    <div class="page-carteirinha">
                        <div>
								<h3 align="center"><span> &nbsp; </span></h3>
								<div class="row-fluid"> 
									<img src="climep1.png" height="70px" width="150px">
								</div>
						</div>
                        <div>
                            <div class="row-fluid">
                                <div class="span2" >
                                </div>
                                <div class="span12" align="center">
                                    <h4 align="center"><span> &nbsp; </span></h4>
                                    <h3 align="center"><span>Anotações de Vacinação e outras</span></h3>
                                    <h3 align="center"><span>Medidas Preventivas</span></h3>
                                    <h5 align="center"><span>
');

$strhtml .= utf8_decode($nome);
$strhtml .= utf8_decode('
					</span></h5>
                                    <h6 align="center"><span>
');
$strhtml .= utf8_decode($matricula);
$strhtml .= utf8_decode('
</span></h6>
                                    <h4 align="center"><span> &nbsp; </span></h4>
                                </div>
                            </div>
                            <div class="row-fluid">
                                <div class="span11">
                                    <div align="center" class="page-header">
                                        <div align="center">
                                                <h6 align="center" style="margin-top:5px">PROCEDIMENTOS AGENDADOS</h6>
						<table align="center" class="program">
');
$strhtml .= utf8_decode($html);
$strhtml .= utf8_decode('
 
						</table>
					</div>
                                    </div> 
                                </div>
                            </div>
                            <div class="row-fluid">
                                <h6 align="center"><span>Braz de Aguiar  410, Belém, PA  (91) 3181-1644 </span></h6>
                                <h6 align="center"><span>www.climep.com.br</span></h6>
                                <h6 align="center"><span> &nbsp; </span></h6>
                            </div>
                        </div>
                    </div> 
                </div>
            </div>
        </div> 
		<div style="page-break-before: always;"></div>
');

// ACABOU A FOLHA DA FRENTE
$strhtml .= utf8_decode('

<table class="tabela teste2" border="2">
	<tr>
		<td class="texto">
			<h4><b>Anotações de Vacinações e outras Medidas Preventivas</b></h4>
		</td>
		<td rowspan="2" class="imagem">
			<div height="70px" width="150px">
				<img src="./climep1.png" height="90px" width="150px">
			</div>
		</td>
	</tr>
	<tr>
		<td class="texto">
			<table border="0" class="tabela2">
				<tr>
					<td class="datatexto"> </td>
					<td class="datadata">
');

$strhtml .= utf8_decode($hoje);
$strhtml .= utf8_decode('
					</td>
				</tr>
				<tr>
					<td class="texto">
					<h4><b>
');

$strhtml .= utf8_decode($nome);
$strhtml .= utf8_decode('
</b></h4> 
					</td>
					<td class="matricula">
');

$strhtml .= utf8_decode($matricula);
$strhtml .= utf8_decode('
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
');
$strhtml .= utf8_decode($_SESSION['fichavacina']['fichavacinahtml']);

$strhtml .= utf8_decode('
<table class="teste tabela3" border="2">
	<tr>
		<td class="texto3">
			<p class="paragrafo">
				Este Relatório atende a lei nº 6.259 de 30 de outubro de 1975, regulamentada pelo Decreto nº 78.231 de 12 
				de agosto de 1976,<br> portaria Conjunta ANVISA/FUNASA nº 01,de 02 de agosto de 2000, e portaria nº 597 do 
				Ministério da Saúde, de 08 de abril <br> de 2004, tendo validade em todo o Território Nacional.
				<br> <br>
				CLIMEP - Cínica de Medicina Preventiva do Pará S/C Ltda. Licença Sanitária 0521/10 (Código 8630-5/30 
				Serviços de Vacina- <br> ção e Imunização Humanas), processo 166/2010-DVSCEP, Prefeitura Municipal de Belém, SESMA, 
				Departamento de Vigilância <br> Sanitária, emitido em 13mai2010.
				Certificado de Inscrição 2.1-PA-102-03 de 16mar2010 no Conselho Regional de Medicina do <br> Estado do Pará.
				<br> <br>
			</p>
		</td>
		<td class="imagem3">
			<p class="paragrafo">Certificamos que as anotações <br> acima transcritas correspondem aos registros arquivados nesta Clínica</p>
		</td>
	</tr>
</table>
');
//print_r($_SESSION['fichavacina']['vacinasprogramadas']);
//unset($_SESSION['fichavacina']);
$strhtml .= '
</body>
</html>
';
//echo $strhtml;
//exit;
//require_once("lib/dompdf/dompdf_config.inc.php");
require_once("dompdf_config.inc.php"); 
$dompdf = new DOMPDF();
$dompdf->load_html($strhtml);
$dompdf->set_paper('a4', 'Portrait');
$dompdf->render();
$dompdf->stream("exemplo-01.pdf", array("Attachment" => 0));


//$dompdf->stream("arquivo.pdf");

//$pdf = $dompdf->output();
//file_put_contents("arquivo.pdf", $pdf)

?>
