<link type="text/css" rel="stylesheet" href="view/convenio/css/index.css" />
<script async defer language="javascript" src="view/convenio/js/consultaconvenio.js"></script>

<div id="consultaconvenio" style="display: block;">
	<div class="row-fluid">
		<h2 class="titulo"> Consulta(Convênio Terceiros) </h2>
		<hr style="margin-top: -5px;">
		<p style="margin-left: 15px;">
			Preencha os campos abaixo e clique em <b> 'Localizar' </b> para iniciar a pesquisa na base de dados. Clique em <b>'Novo'</b> para inclusão.
		</p>
	</div>
	<div class="row-fluid">
		<fieldset class="table-bordered">
			<div class="row-fluid">
				<div class="span2">
					<label>Convênio:</label>
				</div>
				<div class="span1">
					<input type="text" name="consultaconv-cod_convenio" onchange="buscaConsultaConvenioPorCodigo('convenio', 'consulta_convenio');"/>
				</div>
				<div class="span5">
					<input type="text" name="consultaconv-convenio" />
				</div>
			</div>
			<div class="row-fluid">
				<div class="span2">
					<label>Empresa:</label>
				</div>
				<div class="span1">
					<input type="text" name="consultaconv-cod_empresa" value="1" READONLY/>
				</div>
				<div class="span5">
					<input type="text" name="consultaconv-empresa" value="CLIMEP" READONLY/>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span2">
					<label>Tipo de Lanc:</label>
				</div>
				<div class="span3">
					<select name="consultaconv-tipoLancamento">
						<option value="0"> TODOS </option>
					</select>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span2">
					<label>Situação:</label>
				</div>
				<div class="span3">
					<select name="consultaconv-selecionado">
						<option value="0" > TODOS </option>
						<?php
						$statusConsultaConv = buscaTodosStatusDuplicata();
						foreach ($statusConsultaConv as $statusConsulta) {
							?>
							<option value="<?php echo $statusConsulta['id']; ?>"> <?php echo $statusConsulta['nome']; ?> </option>
							<?php
						}
						?>
					</select>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span2">
					<label>Selecionado Por:</label>
				</div>
				<div class="span3">
					<select name="consultaconv-selecionado">
						<option value="1" > DATA DE LANCAMENTO</option>
						<option value="2" > DATA CAIXA </option>
						<option value="3" > DATA BAIXA </option>
					</select>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span2">
					<label>De:</label>
				</div>
				<div class="span2">
					<input data-mask="99/99/9999" type="text" name="consultaconv-data_inicio"/>
				</div>
				<div class="span1">
					<label>Até:</label>
				</div>
				<div class="span2">
					<input data-mask="99/99/9999" type="text" name="consultaconv-data_fim"/>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span2">
					<label>Ordenado Por:</label>
				</div>
				<div class="span3">
					<select name="consultaconv-ordenado">
						<option value="1" > CODIGO SERVICO E DATA </option>
						<option value="2" > CONVENIO </option>
						<option value="3" > MEDICO </option>
						<option value="4" > DATA </option>
						<option value="5" > NOME CLIENTE E DATA </option>
						<option value="6" > CONVENIO E CODIGO SERVICO </option>
						<option value="7" > MEDICO E NOME CLIENTE </option>
						<option value="8" > VALOR </option>
					</select>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span2">
					<label>Usuário :</label>
				</div>
				<div class="span3">
					<select name="consultaconv-usuario">
						<option value="00"> TODOS </option>
						<?php
						$convenios = buscaTodosUsuarios(); // Busca todos os convenios ativos = 1
						foreach ($convenios as $convenio) {
							?>
							<option value="<?php echo $convenio['id']; ?>"> <?php echo strtoupper($convenio['nome']); ?> </option>
							<?php
						}
						?>
					</select>
				</div>
			</div>
			<hr>
			<div class="row-fluid">
				<!-- <div class="span5">
					<div class="row-fluid">
						<div class="span8">
							<label>
								<input type="checkbox" name="" />
								Somente(Particular do Médicos)
							</label>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span6">
							<label>
								<input type="checkbox" name="" />
								Agregado de Convênios
							</label>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span6">
							<label>
								<input type="checkbox" name="" />
								Agregado de Médicos
							</label>
						</div>
					</div>
				</div> -->
				<div class="offset6">
					<!--<a href="#" class="btn" onclick="novaLancamentoconveniado();" ><i class="icon-plus"></i> Novo </a> -->
					<a href="#" class="btn" onClick="limparConsultaConvenio();" ><i class="icon-trash"></i> Limpar </a>
					<a href="#" class="btn" onClick="consultaConvenio();" ><i class="icon-search"></i> Localizar </a>
				</div>
			</div>
        </fieldset>
	</div>
</div>

<div id="consultaconveniotabela" style="display: none;">
	<a href="#" onclick="volta();" class="btn"><i class="icon-circle-arrow-left"></i> Voltar</a>
	<a href="#" onclick="imprimirLancamentosInclusos()" class="btn"><i class="icon-print"></i> Imprimir</a>
	<fieldset class="table-bordered">
		<div class="row-fluid span12" id="table-resumocaixa" style="overflow: auto;">
			<table cellspacing='10' border='1px' align="center" class="table table-bordered table-condensed">
				<thead id="thead-mapa">
					<tr class="white">
						<th> N. GUIA </th>
						<th> CONVÊNIO </th>
						<th> MATRÍCULA </th>
						<th> NOME </th>
						<th> SERVIÇO </th>
						<th> EMPRESA </th>
						<th> DATA </th>
						<th> VALOR </th>
						<th> MÉDICO </th>
						<th> USUÁRIO </th>
					</tr>
				</thead>
				<tbody id="tbody-consulta"> </tbody>
			</table>
		</div>
	</fieldset>
</div>
<div id="lancamentoconveniado" style="display: none;">
	<div class="row-fluid">
		<h2 class="titulo"> Lançamento para Conveniado </h2>
		<hr style="margin-top: -5px;">
		<p style="margin-left: 15px;">
			Preencha todos os campos correatemente e clique em <b>'Avançar'</b> para incluir um novo registro.
		</p>
	</div>
	<div class="row-fluid">
		<fieldset class="table-bordered">
			<div class="row-fluid">
				<div class="span2">
					<label>Convênio:</label>
				</div>
				<div class="span1">
					<input type="text" name="insereconv-cod_convenio" onchange="buscaConsultaConvenioPorCodigo('convenio','insere_convenio');"/>
				</div>
				<div class="span5">
					<input type="text" name="insereconv-convenio"/>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span2">
					<label>Empresa:</label>
				</div>
				<div class="span1">
					<input type="text" name="insereconv-cod_empresa" value="1" READONLY/>
				</div>
				<div class="span5">
					<input type="text" name="insereconv-empresa" value="CLIMEP" READONLY/>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span2">
					<label>Tipo de Lanc:</label>
				</div>
				<div class="span1">
					<input type="text" name="insereconv-cod_tipo_lacamento"/>
				</div>
				<div class="span5">
					<input type="text" name="insereconv-tipo_lacamento"/>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span2">
					<label>Data Serviço:</label>
				</div>
				<div class="span2">
					<input data-mask="99/99/9999" type="text" name="insereconv-data_servico"/>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span2">
					<label> Valor:</label>
				</div>
				<div class="span2">
					<input onKeyPress="return(MascaraMoeda(this,'.',',',event));"  type="text" name="insereconv-valor"/>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span2">
					<label> Nº Controle:</label>
				</div>
				<div class="span2">
					<input  type="text" name="insereconv-numero_controle"/>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span2">
					<label> Observação:</label>
				</div>
				<div class="span8">
					<input type="text" name="insereconv-observacao"/>
				</div>
			</div>
			<hr>
			<div class="row-fluid">
				<div class="offset6">
					<a href="#" class="btn" onClick="consultaconveniado();" ><i class="icon-search"></i> Consulta </a>
					<a href="#" class="btn" onClick="insereConvenio();" > Avançar <i class="icon-circle-arrow-right"></i> </a>
				</div>
			</div>
		</fieldset>
	</div>
</div>
