<link type="text/css" rel="stylesheet" href="view/convenio/css/index.css" />
<div id="consultarecebimento" style="display: block;">
    <div class="row-fluid">
        <h2 class="titulo"> Consulta de recebimento de faturas  </h2>
        <hr style="margin-top: -5px;">
        <p style="margin-left: 15px;">
            Preencha os campos abaixo e clique em <b> 'Localizar' </b> para iniciar a pesquisa na base de dados.Clique em <b>Novo</b> para inclusão
        </p>
    </div>
    <div class="row-fluid">
        <fieldset class="table-bordered">
            <div class="row-fluid">
                <div class="span2">
                    <label>Convênio:</label>
                </div>
                <div class="span1">
                    <input type="text" name="" />
                </div>
                <div class="span5">
                    <input type="text" name="" />
                </div>
            </div>
            <div class="row-fluid">
                <div class="span2">
                    <label>Empresa:</label>
                </div>
                <div class="span1">
                    <input type="text"  name=""/>
                </div>
                <div class="span5">
                    <input type="text" name="" />
                </div>
            </div>
            <div class="row-fluid">
                <div class="span2">
                    <label>Status:</label>
                </div>
                <div class="span1">
                    <input type="text"  name=""/>
                </div>
                <div class="span5">
                    <input type="text" name="" />
                </div>
            </div>

            <div class="row-fluid">
                <div class="span2">
                    <label>Selecionar Por:</label>
                </div>
                <div class="span3">
                    <select name="">
                        <option value="1" >01 - DATA_LACAMENTO </option>
                        <option value="2" >02 - DATA_TESTE </option>
                        <option value="3" >03 - DATA_ID_TESTE2 </option>
                        <option value="4" >04 - DATA_ID_TESTE3 </option>
                    </select>
                </div>
            </div>


            <div class="row-fluid">
                <div class="span2">
                    <label>De:</label>
                </div>
                <div class="span2">
                    <input data-mask="99/99/9999" type="text" name=""/>
                </div>
                <div class="span1">
                    <label>Até:</label>
                </div>
                <div class="span2">
                    <input data-mask="99/99/9999" type="text" name=""/>
                </div>
            </div>

            <div class="row-fluid">
                <div class="span2">
                    <label>Ordenar Por:</label>
                </div>
                <div class="span3">
                    <select name="">
                        <option value="1" >01 - ID_EMPRESA </option>
                        <option value="2" >02 - ID_TESTE1 </option>
                        <option value="3" >03 - ID_TESTE2 </option>
                        <option value="4" >04 - ID_TESTE3 </option>
                    </select>
                </div>
            </div>
            <hr>
            <div class="row-fluid">
            
                <div class="offset6">
                    <a href="#" class="btn"  ><i class="icon-plus"></i> Novo </a>
                    <a href="#" class="btn"  ><i class="icon-search"></i> Localizar </a>
                </div>
            </div>
        </fieldset>
    </div>
</div>
