<script async defer src="view/estoque/js/transfVacina.js"></script>
<script async defer src="view/estoque/js/index.js"></script>
<script async defer src="view/js/utils.js"></script>
<script async defer src="template/js/bootstrap-datepicker.js"></script>
<link type="text/css" rel="stylesheet" href="view/estoque/css/index.css" />

<div id="entrada1">
	<h2 class="titulo">ENF - Entrada de Nota Fiscal no Estoque</h2>
	<fieldset class="nota-fiscal table-bordered" style="margin-top: -12px;">
		<legend> Cabeçalho da Nota Fiscal</legend>
		<div class="row-fluid">
			<div class="span4">
				<label class="nf-nome-text" for="num-nf">Nota Fiscal</label>
				<input id="num-nf" name="num-nf" type="text" placeholder="NUMERO DA NOTA" value=""  />
			</div>
			<div id="nf-fornecedor" class="span2">
				<label class="nf-nome-text" for="nf-fornecedor">Fornecedor (cod.)</label>
				<input id="nf-fornecedor" name="nf-fornecedor" type="text" placeholder="CÓDIGO" onchange="buscaFornecedor();" value="<?php echo $cnpj; ?>"/>
			</div>
			<div class="span5 nf-fornecedor-large" >
				<label class="nf-nome-text" for="nf-fornecedor"></label>
				<select id="nf-fornecedor-large" name="nf-fornecedor-large" onchange="buscaCodFornecedor();">
					<option></option>
					<?php
					$fornecedores = buscaFornecedores();
					
					if(!empty($fornecedores)) {
						foreach ($fornecedores as $fornecedor) {
						?>
							<option value="<?php echo $fornecedor['id']; ?>" >
								<?php echo $fornecedor['nome']; ?>
							</option>
						<?php
						}
					}
					?>
				</select>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span12">
				<div class="row-fluid">
					<div class="span3">
						<label class="nf-nome-text" for="nf-frente">Frete</label>
						<select id="nf-frete" name="nf-frete" >
							<?php
							$fretes = buscaFrete();
							if(!empty($fretes)) {
								foreach ($fretes as $frete) {
							?>
									<option value="<?php echo $frete['id']; ?>" >
										<?php echo $frete['nome']; ?>
									</option>
							<?php
								}
							}
							?>
						</select>
					</div>
					<div class="span2">
						<label class="nf-nome-text" for="nf-valor-frente">Valor Frete</label>
						<input id="nf-valor-frete" name="nf-valor-frete" type="text" onKeyPress="return(MascaraMoeda(this, '.', ',', event))"/>
					</div>
					<div class="span2">
						<label class="nf-nome-text" for="nf-data-emissao">Data Emissão</label>
						<input type="text" name="nf-data-emissao" id="nf-data-emissao" placeholder="" value=""/>
					</div>
					<div class="span2">
						<label class="nf-nome-text" for="nf-total-nota">Total Nota</label>
						<input type="text" name="nf-total-nota" id="nf-total-nota" onKeyPress="return(MascaraMoeda(this, '.', ',', event))"/>
					</div>
					<div class="span2">
						<label class="nf-nome-text" for="nf-entrada">Data Entrada</label>
						<input id="nf-data-entrada" type="text" name="nf-data-entrada"  placeholder="" value=""/>
					</div>
				</div>
				<div class="row-fluid">
				</div>
			</div>
		</div>
	</fieldset><hr>
	<fieldset class="nota-fiscal table-bordered" style="margin-bottom: 5px;">
		<legend>Dados do Faturamento</legend>
		<div class="row-fluid">
			<div class="span3">
				<label class="nf-nome-text" for="nf-tipo">Tipo :</label>
				<select id="nf-selc-tipo" name="nf-selc-tipo" >
					<option value="BOLETO">BOLETO</option>
					<option value="EM CARTEIRA">EM CARTEIRA</option>
					<option value="NOTA PROMISSORA">NOTA PROMISSORA</option>
					<option value="DEPÓSITO BANCÁRIO">DEPÓSITO BANCÁRIO</option>
				</select>
			</div>

			<div class="span3">
				<label class="nf-nome-text" for="nf-numero">Número :</label>
				<input id="nf-numero" type="text" name="nf-numero" placeholder="NUMERO DA NOTA"/>
			</div>

			<div class="span2">
				<label class="nf-nome-text" for="nf-vencto">1º Vencimento :</label>
				<input id="nf-selc-vencto" name="nf-selc-vencto" data-mask='99/99/9999' type="text"/>
			</div>
			<div class="span2" style="margin-top: 17px;">
				<select id="nf-selc-intervalo" name="nf-selc-intervalo">
					<option value="15">15</option>
					<option value="30">30</option>
					<option value="45">45</option>
					<option value="60">60</option>
					<option value="90">90</option>
					<option value="120">120</option>
				</select>
			</div>
		</div>

		<div class="row-fluid">	
			<div class="span12">
				<div class="span3">
					<label class="nf-nome-text" for="nf-valor"> Valor :</label>
					<input id="nf-valor" name="nf-valor" onKeyPress="return(MascaraMoeda(this, '.', ',', event))" type="text"/>
				</div>

				<div class="span2">
					<label class="nf-nome-text" for="nf-parcelas">Parcelas :</label>
					<select id="nf-selc-parcelas" name="nf-selc-parcelas" >
						<option value="1">1</option>
						<option value="2">2</option>
						<option value="3">3</option>
						<option value="4">4</option>
						<option value="5">5</option>
						<option value="6">6</option>
						<option value="7">7</option>
						<option value="8">8</option>
						<option value="9">9</option>
						<option value="10">10</option>
						<option value="11">11</option>
						<option value="12">12</option>
					</select>
				</div>

				<div class="span3">
					<label class="nf-nome-text" for="nf-parcelas">Banco :</label>
					<select id="nf-banco" name="nf-banco" >
						<?php
						$bancos = buscaTodosBancos();
						if(!empty($bancos)) {
							foreach ($bancos as $banco) {
								?>
								<option value="<?php echo $banco['id']; ?>" ><?php echo $banco['nome']; ?></option>
								<?php
							}
						}
						?>
					</select>
				</div>

				<div class="span3">
					<div class="row-fluid">
						<input class="btn btn-mini span12 nf-n" type="submit" name="nf-n" onclick="processarDuplicatas();" value="Processar Duplicatas"/>
					</div>
				</div>
			</div>
		</div><br>
		<div style="height:170px;overflow:auto;color:black" class="row-fluid">
			<table align="center" class="table-striped table-modify" >
				<thead>
					<tr class="white">
						<th align="center"> Documento </th>
						<th align="center"> Número </th>
						<th align="center"> Vencimento </th>
						<th align="center"> Valor </th>
					</tr>
				</thead>
				<tbody id="tbody-nf-parcelas">
				</tbody>
			</table>
		</div>
	</fieldset>
	<div class="container-fluid">
		<div class="span12">
			<ul class="thumbnails">
				<li class="span2 botao">
					<input class="btn btn-mini nf-n span10" type="reset" name="avancar" value="Novo"/>
				</li>
				<li class="span2 botao">
					<input class="btn btn-mini nf-n span10" type="button" name="fechar" onclick="document.location.href = 'index.php';" value="Fechar"/>
				</li>
				<li class="span2 botao">
					<input class="btn btn-mini nf-n span10" type="button" onclick="validaEntradanfForm();" value="Avançar >>"/>
				</li>
			</ul>
		</div>
	</div>
</div>
<!--================================ FIM FORMULAŔIO DE CADASTRO ==============================================================
	========================================================================================================================== -->

<!--================================  FORMULÁRIO de ITENS DE NOTA FISCAL  ====================================================
	========================================================================================================================== -->

<div  style="display: none;" id="entrada2">
	<div class="row-fluid">
		<div class="span9">
			<h2 class="titulo">Entrada de Nota Fiscal</h2>
			<div id="result-transf"></div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<hr style="margin-top: -4px;"/>
			<fieldset class="table-bordered">
				<legend>Entrada</legend>
				<div class="row-fluid">
					<div class="span6">
						<label>Origem :
							<select id="origem-transf" disabled>
								<?php
								foreach (buscaLocal() as $local) {
									$selected = "";
									if ($local['id'] == '3') {
										$selected = "SELECTED";
									}
									?>
									<option <?php echo $selected; ?> value="<?php echo $local['id']; ?>" ><?php echo $local['nome']; ?></option>
									<?php
								}
								?>
							</select>
						</label>
					</div>
					<div class="span6">
						<label>Destino :
							<select id="destino-transf">
								<?php
								foreach (buscaLocal() as $local) {
									if ($local['nome'] != 'Almoxarifado') {
										continue;
									}
									?>
									<option value="<?php echo $local['id']; ?>" ><?php echo $local['nome']; ?></option>
									<?php
								}
								?>
							</select>
						</label>
					</div>
				</div><br/>
			</fieldset>
		</div>
	</div><br/>
	<div class="row-fluid">
		<fieldset class="table-bordered">
			<legend> Itens da Nota Fiscal </legend>
			<div style="height:300px;overflow:auto;color:black" class="row-fluid">
				<table  cellspacing='10' align="center" class="table-modfy table-striped">
					<thead>
						<tr class="white">
							<th align="center">Excluir </th>
							<th align="center"> Código </th>
							<th align="center"> Produto </th>
							<th align="center"> Lote </th>
							<th align="center"> Validade</th>
							<th align="center"> Qtd </th>
							<th align="center"> Tipo</th>
							<th align="center"> Custo </th>
						</tr>
					</thead>

					<input type="hidden" value="0" id="hiddenRowId">
					<tbody id="table-transf-vacina-append">
					</tbody>
				</table>
			</div>
		</fieldset>
	</div><br/>
	<div class="row-fluid">
		<fieldset class="table-bordered" >
			<div class="span3" >
				<label>Vacina :</label>
				<select onchange="buscaPrecoMaterial();" id="material-id">
					<option></option>
					<?php
					$listaMateriais = buscaMaterial(''); // busca Material por nome do tipo de Material
					if(!empty($listaMateriais)) {
						foreach ($listaMateriais as $material) {
							?>
							<option value="<?php echo $material['id']; ?>" ><?php echo $material['nome']; ?></option>
							<?php
						}
					}
					?>
				</select>
			</div>
			<div class="span2" id="tv-lote">
				<label>
					Lote :
					<input type="text" id="em-lote"/>
				</label>
			</div>
			<div class="span2" id="tv-validade">
				<label>
					Validade:
					<input type="text" id="em-validade"/>
				</label>
			</div>
			<div class="span1" >
				<label>Tipo :</label>
				<select id="em-tipo">
					<option value="Frasco">Frasco</option>
					<option value="Dose">Dose</option>
				</select>
			</div>
			<div class="span2">
				<div class="span11">
					<label>
						Quantidade:
						<input type="text" id="em-quantidade"/>
					</label>
				</div>
			</div>
			<div class="span2">
				<div class="span10">
					<label>
						Valor Unit:
						<input type="text" id="em-custo" onKeyPress="return(MascaraMoeda(this, '.', ',', event))"/>
					</label>
				</div>
			</div>
		</fieldset>
	</div>
	<div class="row-fluid">
		<fieldset id="flst-color-trans" class="table-bordered" >
			<div id="opcoes-trans" class="span12">
				<div class="span2 botao">
					<input class="btn btn-mini nf-n span12" type="submit" name="finalizar" id="submit-entrada-vacina" value="Finalizar Nota"/>
				</div>
				<div class="span2 botao">
					<input class="btn btn-mini span12" type="button" name="gravar" id="entrada-table-append" value="Incluir »"/>
				</div>
				<div class="span2 botao">
					<input class="btn btn-mini span12" type="button" name="cancelar" onclick="redirecionar('index.php');" value="Cancelar" />
				</div>
				<div class="span2 botao">
					<input class="btn btn-mini span12" type="button" onclick='goToEntrada1();' name="voltar" value="Voltar" />
				</div>
<!--				<div class="span2 botao">
					<input class="btn btn-mini nf-n span12" type="button" name="imprimir" value="Imprimir" />
				</div>-->
			</div>
		</fieldset>
	</div>
</div>