<script async defer src="view/estoque/js/filtroSelects.js"></script>
<script async defer src="view/estoque/js/transfVacina.js"></script>
<script async defer src="template/js/geral.js"></script>
<link type="text/css" rel="stylesheet" href="view/estoque/css/index.css" />
<div class="row-fluid">
    <div class="span9">
<h2 class="titulo">Transferência de Vacina</h2>
<div id="result-transf"></div>
</div>
    <!--<div class="span3" style="margin-top: 10px; margin-left: -10px;">
        <button class="btn btn-mini span12" onclick= "abrir_modal('boxes-consulta-estoque');">Consulta</button>
    </div>-->
</div>

<div class="row-fluid">
    <div class="span12">
             <hr style="margin-top: -4px;"/>
             <fieldset class="table-bordered">
                 <legend>Tranferência Consulta e Entrada</legend>
                 <div class="row-fluid">
                     <div class="span4">
                        <label>Origem :
                        <select id="origem-transf">
							<option></option>
						<?php
								foreach(buscaLocal() as $local) {
						?>
									<option value="<?php echo $local['id']; ?>" ><?php echo $local['nome']; ?></option>
						<?php
								}
						?>
                        </select>  
                         </label>
                     
					</div>    
                     <div class="span4">
                        <label>Destino :
                        <select id="destino-transf">
							<option></option>
						<?php
								foreach(buscaLocal() as $local) {
						?>
									<option value="<?php echo $local['id']; ?>" ><?php echo $local['nome']; ?></option>
						<?php
								}
						?>
                        </select>  
                        </label>
                     
					</div>    
                    <div class="span4">
                     <label>Motivo :
                        <select id="motivo-transf">
						<?php
								foreach(buscaMotivo() as $motivo) {
						?>
									<option value="<?php echo $motivo['id']; ?>" ><?php echo $motivo['nome']; ?></option>
						<?php
								}
						?>
                        </select>
                     </label>
					</div>    
                 </div>    
                 <br/>
             </fieldset>
    </div>
</div><br/>

<div class="row-fluid" >
    <fieldset class="table-bordered">
        <legend> Itens Selecionados para Transferência  </legend>
        <table  cellspacing='10'  border='1px'  align="center" class="table table-bordered" >
            <thead>
                <tr class="white">
                    <th align="center"> Excluir </th>
                    <th align="center"> Código </th>
                    <th align="center"> Vacina </th>
                    <th align="center"> Qtd </th>
                    <th align="center"> Lote Atual </th>
                    <th align="center"> Novo Lote </th>
                    <th align="center"> Almox </th>
                    <th align="center"> Sala</th>
                    <th align="center"> Validade</th>
                    <th align="center"> Tipo</th>
                </tr>
            </thead>

            <input type="hidden" value="0" id="hiddenRowId">
            <tbody id="table-transf-vacina-append">
            </tbody>

        </table>
    </fieldset>
</div><br/>

<div class="row-fluid"   >
    <fieldset id="flst-color-trans" class="table-bordered" >
        <div id="opcoes-trans" class="span12 " >

            <!--<div class="span2 botao">
                <input class="btn btn-mini nf-n span12" type="button" name="ajuda" value="<F1> - Ajuda" />
            </div>-->
            <div class="span1 botao">
                <!--<input class="btn btn-mini nf-n span12" type="button" name="ajuda" value="<F1> - Ajuda" />-->
            </div>
            <div class="span2 botao">
               <!-- <input class="btn btn-mini nf-n span12" type="button" name="imprimir" value="<F5> - Imprimir" />-->
            </div>
            <div class="span3 botao">
                <!--<input class="btn btn-mini nf-n span12" type="submit" name="finalizar" id="submit-transf-vacina" value="<F7> - Finalizar Notas" />-->
                <input class="btn btn-mini nf-n span12" type="submit" name="finalizar" id="submit-transf-vacina" value="Finalizar Notas" />
            </div>
            <!--<div class="span3 botao">
                <input class="btn btn-mini nf-n span12" type="submit" name="excluir" value="<DEL> - Excluir Item da Nota" />
            </div>-->


        </div>

    </fieldset>
</div><br>

<div class="row-fluid" >
    <fieldset class="table-bordered" >
        <div class="span3" >
            <label>Vacina :</label>
            <select id="material-id" onChange="buscaLotes();" >
				<option></option>
				<?php
						foreach(buscaMaterial('') as $material) {
				?>
							<option value="<?php echo $material['id']; ?>" ><?php echo $material['nome']; ?></option>
				<?php
						}
				?>
            </select>
        </div>
        <div class="span2" id="tv-lote" >
            <label>Lote :</label>
			<select id="lote-id" onChange="buscaValidadeLote();">
				<option></option>
			</select>
        </div>
        <div class="span2" id="tv-validade" >
            <label>
                Validade:
                <input type="text" class="" name="" disabled/>
            </label>
        </div>
        <div class="span2" >
            <label>Tipo :</label>
            <select id="tv-tipo">
				<option value="Frasco">Frasco</option>
				<option value="Dose">Dose</option>
				<option value="ML">ML</option>
            </select>
        </div>
        <div class="span2"  >
            <label>
                Quantidade:
                <input type="text" class="" name="" id="tv-quantidade"/>
            </label>
        </div>

    </fieldset>
</div><br>

<div class="row-fluid" >
    <div class="span12"> 
        <fieldset class="table-bordered">
            <div class="span10" >
                <fieldset id="flst-color-trans-footer" class="table-bordered" >       
                    <div>

                    </div>
                </fieldset>
            </div>

            <div class="span2" style="margin-left: 1px;">

                <ul class="">   
                    <li class="span12 "> 
                        <input class="btn btn-mini span12" style="margin-left: 4px;" type="button" name="gravar" id="tv-table-append" value="Incluir »" />
                    </li>
                    <li class="span12 " style="padding-top: 5px;">
                        <input class="btn btn-mini span12" type="button" name="cancelar" value="Cancelar" onclick="document.location.href='index.php'"/>
                    </li>
                </ul>
            </div>
        </fieldset>
    </div>
</div>


</div>
<?php
	include('view/estoque/modal-consulta-transfestoque.phtml');
?>

