<script async defer src="template/js/bootstrap-datepicker.js"></script>
<script async defer src="view/estoque/js/index.js"></script> 
<link type="text/css" rel="stylesheet" href="view/estoque/css/index.css" />

<h2 class="titulo">Últimas Entradas</h2>
<div class="row-fluid">
	<div class="span10" >
		<fieldset class=" table-bordered">
			<legend>
				Pesquisa
			</legend>
			<div class="span3">
				<label>
					Material :
				 <select id="ue-id-material" >
				 	<option value=""> Todos </option>
				 	<?php

				 			foreach(buscaMaterial('') as $vacinamaterial) {
								$select = '';
								if($vacinamaterial['id'] == $idMaterial){
									$select = "SELECTED";
								}
				 	?>
								<option <?php echo $select; ?> value="<?php echo $vacinamaterial['id']; ?>" ><?php echo $vacinamaterial['nome']; ?></option>
				 	<?php
				 			}
				 	?>
				 </select>
				</label>
			</div>

			<div class="span2 m-top" >
				<label>
					<input type="radio" class="" name="option" id="ue-option" value="entrada" <?php echo $checkEntrada; ?>/>
					Entrada
				</label>
			</div>

			<div class="span3 m-top">
				<label>
					<input type="radio" class="" name="option" id="ue-option" value="ult6entradas" <?php echo $check6entradas; ?>/>
					Últimas 6 Entradas
				</label>
			</div>

			<div class="span3 m-top" >
				<label>
<?php
							if(!empty($soVacina)) {
								$checkSoVacina = "checked";
							}
				?>
					<input type="checkbox" class="" name="ue-checkbox" id="ue-checkbox" value="so-vacinas" <?php echo $checkSoVacina; ?>/>
					Somente Vacinas
				</label>
			</div>
            <div class="row-fluid">
                <div class="span10 m-left" style="margin-left: 15px;">


                    <div class="span2">

                        <label>
                            Início:
							<input type="text" class="" name="" id="ue-dataInicio" value="<?php echo converteData($dataInicio); ?>" />
                        </label>

                    </div>

                    <div class="span2" >
                        <label>
                            Fim:
                            <input type="text" class="" name="" id="ue-dataFim" value="<?php echo converteData($dataFim); ?>" />
                        </label>
                    </div>

                    <div class="span4 m-top" style="margin-left: 20px;">
                        <label>
						<input type="radio" class="" name="option" id="ue-option" value="fluxo-vacinas" <?php echo $checkFluxo; ?>/>
                            Fluxo de Vacina por 
                            <i class="icon-chevron-right"></i>
                        </label>
                    </div>

                    <div class="span3 m-top">
                        <label>
                            <select id="ue-select-option" onchange="checkFluxo();" >
                                <option></option>
                                <option value="vacina" <?php echo $selectVacina; ?>>Vacina</option>
                                <option value="imuno" <?php echo $selectImuno; ?>>Imunoterapia</option>
                                <option value="triagem" <?php echo $selectTriagem; ?>>Triagem Neonatal</option>
                                <option value="imunidade" <?php echo $selectImunidade; ?>>Imunidade</option>
                            </select>
                        </label>
                    </div>

                </div>
            </div>
        </fieldset>       
    </div>
    
    <div class="span2" style="margin-top: 10px;margin-left: -10px;">
        <ul class="">   
            <li class="span12 "> 
                <input class="btn btn-mini span12"  type="button" name="" id="ue-processar" onclick="ultEntradasMaterial();" value="Processar" />
            </li>
            <li class="span12 " style="padding-top: 20px;">
                <input class="btn btn-mini span12" type="button" name="" value="Fechar" onclick="document.location.href='index.php'" />
            </li>
        </ul>
    </div>


</div><br/>
<div class="row-fluid">
    

  <fieldset class="table-bordered">
        <legend> Resultado da pesquisa  </legend>
        <table  cellspacing='10'  border='1px'  align="center" class="table table-bordered" >
<?php
		if($option == 'entrada' || $option == '' ) {
?>
            <thead>
                <tr class="white">
                    <th align="center">ID</th>
                    <th align="center">Nota </th>
                    <th align="center">VI.Nota </th>
                    <th align="center">Entrada </th>
                    <th align="center">Fornecedor </th>
                    <th align="center">Vacina </th>
                    <th align="center">Qtd</th>
                    <th align="center">V.Únt</th>
                </tr>
            </thead>
            <tbody >
			<?php
if(!empty($materiais)){
				foreach($materiais as $material) {
					$divisor = $material['quantidade_doses']*$material['qtd_ml_por_dose'];
					$materialEmFrasco = ($material['quantidade'])/($divisor);

			?>
                <tr  name="table-color" class='dayhead '>
                    <th align="center"><?php echo $material['id_movimentacao']; ?></th>
                    <th align="center"><?php echo $material['nota_fiscal']; ?></th>
                    <th align="center"><?php echo $material['valor_nota_fiscal']; ?></th>
                    <th align="center"><?php echo converteData($material['data_entrada']); ?></th>
                    <th align="center"><?php echo $material['nome_fornecedor']; ?></th>
                    <th align="center"><?php echo $material['nome_material']; ?></th>
                    <th align="center"><?php echo frascosML($material['quantidade_doses'],$material['qtd_ml_por_dose'],$materialEmFrasco); ?></th>
                    <th align="center"><?php echo $material['valor_unit']; ?></th>
                </tr>
<?php
				}
} else {
?>
                <tr  name="table-color" class='dayhead '>
                    <th text-align="center" colspan='8' style="text-align:center;"> Sem Dados Disponíveis</th>

                </tr>
<?php
}
?>

            </tbody>

<?php
		} else if ($option == 'ult6entradas') {
?>
            <thead>
                <tr class="white">
                    <th align="center">Cód.</th>
                    <th align="center">Vacina</th>
                    <th align="center">(6) </th>
                    <th align="center">Qtd</th>
                    <th align="center">(5) </th>
                    <th align="center">Qtd</th>
                    <th align="center">(4) </th>
                    <th align="center">Qtd</th>
                    <th align="center">(3) </th>
                    <th align="center">Qtd</th>
                    <th align="center">(2) </th>
                    <th align="center">Qtd</th>
                    <th align="center">(1) </th>
                    <th align="center">Qtd</th>
                    <th align="center">Total</th>
                    <th align="center">Média</th>
                </tr>
            </thead>
            <tbody >

<?php
if(!empty($materiais)){

					foreach($materiais as $material2) {
?>
						<tr name="table-color" class='dayhead '>
							<th align="center"><?php echo $material2[0]['id_material']; ?></th>
							<th align="center"><?php echo $material2[0]['nome_material']; ?></th>
<?php
						foreach($material2 as $material3) {
							$divisor = $material3['quantidade_doses'] * $material3['qtd_ml_por_dose'];
							$materialEmFrasco = ($material3['quantidade']) / ($divisor);
							$total += $material3['quantidade'];
?>
							<th align="center"><?php echo converteData($material3['data_entrada']); ?></th>
							<th align="center"><?php echo frascosML($material3['quantidade_doses'],$material3['qtd_ml_por_dose'],$materialEmFrasco); ?></th>
<?php
						}
						$total = $total/($divisor);
						for($qtd = count($material2);$qtd < 6;$qtd++){
?>
							<th align="center"></th>
							<th align="center"></th>
<?php
						}
?>
							<th align="center"><?php echo frascosML($material2[0]['quantidade_doses'],$material2[0]['qtd_ml_por_dose'],$total); ?></th>
							<th align="center"><?php echo frascosML($material2[0]['quantidade_doses'],$material2[0]['qtd_ml_por_dose'],$total/6); ?></th>
						</tr>
<?php
						$total = 0;
					}

} else {
?>

                <tr  name="table-color" class='dayhead '>
                    <th text-align="center" colspan='16' style="text-align:center;"> Sem Dados Disponíveis</th>

                </tr>
<?php

}
?>

            </tbody>
<?php
		} else if ($option == 'fluxo-vacinas') {
?>
            <thead>
                <tr class="white">
                    <th align="center">Cód.</th>
                    <th align="center">Vacina</th>
                    <th align="center">Entrada</th>
                    <th align="center">Caixa</th>
                    <th align="center">Saldo</th>
                </tr>
            </thead>
            <tbody>
			<?php
if(!empty($materiais)){
				foreach($materiais as $material) {
			?>

                <tr  name="table-color" class='dayhead '>
                    <th align="center"><?php echo $material['id_material']; ?></th>
                    <th align="center"><?php echo $material['nome_material']; ?></th>
                    <th align="center"><?php echo estoqueMaterial($material['id_material'],'entrada'); ?></th>
                    <th align="center"><?php echo estoqueMaterial($material['id_material'],'consumo'); ?></th>
                    <th align="center"><?php echo estoqueMaterial($material['id_material'],'total'); ?></th>
                </tr>

<?php
				}
?>
            </tbody>
<?php
} else {
?>

                <tr  name="table-color" class='dayhead '>
                    <th text-align="center" colspan='5' style="text-align:center;"> Sem Dados Disponíveis</th>

                </tr>
<?php

}
		}
?>
        </table>
    </fieldset>
</div>
