<?php
const COD_CIDADE = '427';
const CNPJ = '05083142000183';
const RAZAO_SOCIAL_REMETENTE = 'CLINICA DE MEDICINA PREVENTIVA DO PARA S/S LTDA.';
const RAZAO_SOCIAL_PRESTADOR = 'CLINICA DE MEDICINA PREVENTIVA DO PARA S/S LTDA.';
const VERSAO = '1';
const METODO_ENVIO = 'WS';
const INSCRICAO_MUNICIPAL_PRESTADOR = '0069496';
const TIPO_RPS = 'RPS';
const SERIE_RPS = 'NF';
const NUMERO_RPS = '0';
const DDD_PRESTADOR = '091';
const TELEFONE_PRESTADOR = '31811644';
const VERSAO_COMPONENTE = '1.0.0.7';
?>
