<!DOCTYPE html>
<html lang="pt" >
    <head>
        <meta charset="utf-8">
        <link href="./css/bootstrap.css" rel="stylesheet">

        <link href="./css/pdfs.css" rel="stylesheet">

    </head>
    <body>

        <div class="container-fluid" >
            <div class="page-header">
                <div class="borderpage" >
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="pull-left marginleft paddingtop" >
                                <div class="input-prepend">
                                    <label><b>Nome:</b></label>
                                    <span class="add-on spanfont" ><?php echo $_POST['titular']; ?> - <?php echo $_POST['idade_titular']; ?></span>
                                </div>
                            </div>
                        </div>
                        <div class="span2 labelsexo" >
                             <div align="center" class="paddingtop" >
                               
                                <div class="input-prepend">
                                    <label><b>Sexo :</b></label>
                                    <span class="add-on" style="font-size: 10px;"><?php echo $_POST['sexo']; ?></span>
                                </div>
                            </div>
                        </div>
                        <div class="span2 labelnascimento" >
                             <div align="center" class="paddingtop" >
                                <div class="input-prepend">
                                    <label><b>Nascimento :</b></label>
                                    <span class="add-on" style="font-size: 10px;"><?php echo $_POST['data_nascimento_titular']; ?></span>
                                </div>
                            </div>
                        </div>
                        <div class="span2" style=" border-right:1px solid #000000; ">
                             <div align="center" class="paddingtop" >
                                <div class="input-prepend">
                                    <label><b>Matrícula :</b></label>
                                    <span class="add-on" style="font-size: 10px;"><?php echo $_POST['matricula_titular']; ?></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span5">
                        <div class="pull-left labelmae" >
                            <div class="input-prepend">
                                <label><b> Mãe(se menor): </b></label>
                                <span class="add-on" style="font-size: 10px;"><?php echo $_POST['titular']; ?></span>
                            </div>
                        </div>
                    </div>
                    <div class="span3  labeltelefone" >
                        <div class="pull-left margintelefone"  >
                            <div class="input-prepend">
                                   <label><b>Telefone:</b></label>
                                <span class="add-on" style="font-size: 10px;"><?php echo $_POST['telefone']; ?></span>
                            </div>
                        </div>
                    </div>
                    <div class="span4">
                        <div class="pull-left marginmedico" >
                            <div class="input-prepend">
                                <label><b>Médico Assistente:</b></label>
                                <span class="add-on" style="font-size: 10px;"><?php echo $_POST['medico']; ?></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="page-header">
                <div class="row-fluid">
                    <table class="table table-bordered table-condensed">
                        <thead>
                            <tr>
                                <th>IT</th>
                                <th>ACAROS INJ</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Frasco</td>
                                <td>e</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Intervalo</td>
                                <td>e</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Observação</td>
                                <td>e</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>1</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>1</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </div> 
            </div> 
            <hr>
            </body>
            </html>
