<!DOCTYPE html>
<html lang="pt" >
    <head>
        <meta charset="utf-8">
        <link href="./css/bootstrap.css" rel="stylesheet">
        <link href="./css/pdfs.css" rel="stylesheet">
    </head>
    <body>
        <div class="container-fluid" >
            <div class="row-fluid"><br><br>
                <div class="span4 " ></div>
                <div>
                    <h3>CERTIFICADO DE VACINAÇÃO</h3>
                </div>
            </div>
            <div class="page-header">


                <div class="row-fluid">
                    <div class="row-fluid">
                        <p>Certifico a quem interessar possa que os informes abaixo transcritos
                            constituem-se um resumo das anotações arquivadas no Serviço de Imunização desta Clínica
                            , correspondendo a procedimentos administrados à pessoa abaixo identificada:</p>
                    </div>

                </div>
            </div>
            <div class="row-fluid">
                <div class="span1">
                    <p>  Nome: </p>
                </div> 
                <div  class="span10">
                    <h4>GLENDA MARIA ALVES FERREIRA</h4>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span1">
                    <p> Sexo: </p>
                </div> 
                <div  class="span3">
                    <h4> F</h4>
                </div>
                <div class="span2">
                    <p> Nascimento: </p>
                </div> 
                <div  class="span2">
                    <h4>31out11</h4>
                </div>
                <div class="span2">
                    <p> Matrícula: </p>
                </div> 
                <div  class="span2">
                    <h4>331.381</h4>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span2">
                    <p>  Endereço: </p>
                </div> 
                <div  class="span9">
                    <h4>CONJ.JARDIM VILA NOVA QDª 4 CASA 03, ANANIDEUA, PA</h4>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="page-header">
                <div class="row-fluid">
                    <table class="table ">
                        <thead>
                            <tr>
                                <th>Vacinação realizada-Lote</th>
                                <th>dd/mm/aa</th>
                                <th>Vacinação realizada-Lote</th>
                                <th>dd/mm/aa</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Frasco</td>
                                <td>e</td>
                                <td>Frasco</td>
                                <td>e</td>

                            </tr>
                            <tr>
                                <td>Frasco</td>
                                <td>e</td>
                                <td>Frasco</td>
                                <td>e</td>

                            </tr>
                            <tr>
                                <td>Frasco</td>
                                <td>e</td>
                                <td>Frasco</td>
                                <td>e</td>

                            </tr>
                            <tr>
                                <td>Frasco</td>
                                <td>e</td>
                                <td>Frasco</td>
                                <td>e</td>
                            </tr>
                        </tbody>
                    </table>
                </div> 
            </div> 
            <div class="page-header">
                <div class="borderpage" >
                    <div class="row-fluid">
                        <div> <h4>Anotações:</h4></div>
                        <div class="page-header"></div>
                        <div><h5>(*) Vacinações realizadas em outra instituição, conforme documentação apresentada pelo cliente.</h5></div>
                    </div>
                </div>
            </div>
            
            <div class="row-fluid">
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam eget ligula eu lectus lobortis condimentum. Aliquam nonummy auctor massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla at risus. Quisque purus magna, auctor et, sagittis ac, posuere eu, lectus. Nam mattis, felis ut adipiscing.</p>
            </div>
            
            <div class="row-fluid"><br>
                <div class="">
                    <h4>Belém, quarta-feira, 26 de setembro de 2012</h4>
                </div>
            </div><br><br>
            <div class="row-fluid">
                <div class="page-line "></div>
            </div>
        </div>


        <hr>
    </body>
</html>
