<!DOCTYPE html>
<html lang="pt" >
    <head>
        <meta charset="utf-8">
        <link href="./css/bootstrap.css" rel="stylesheet">
        <link href="./css/pdfs.css" rel="stylesheet">
    </head>
    <body>
        <div class="container-fluid" >

            <div class="row-fluid">
                <div class="row-fluid"><br><br>
                    <div class="span3 " ></div>
                    <div>
                        <h2>Mapa de Consumo do Estoque</h2>
                        <p></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="page-header">
                <div class="row-fluid">
                    <table class="table ">
                        <thead>
                            <tr>
                                <th>PRODUTO</th>
                                <th>Origem e lote validade</th>
                                <th>Modulo</th>
                                <th>Cosumo da semana</th>
                                <th></th>
                                <th>Entrada da Semana</th>
                                <th>Data de Entrada</th>
                                <th>4 - 2º Feira</th>
                                <th>5 - 3º Feira</th>
                                <th>6 - 4º Feira</th>
                                <th>7 - 5º Feira</th>
                                <th>8 - 6º Feira</th>
                                <th>9 - Sábado</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                
                            </tr>
                      
                            <tr>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                
                            </tr>
                      
                            <tr>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                <td>e</td>
                                
                            </tr>
                      
                        </tbody>
                    </table>
                </div> 
            </div> 
            <hr>
            </body>
            </html>
