<!DOCTYPE html>
<html lang="pt" >
    <head>
        <meta charset="utf-8">
        <link href="./css/bootstrap.css" rel="stylesheet">
        <link href="./css/pdfs.css" rel="stylesheet">
    </head>
    <body>
        <div class="container-fluid" >

            <div class="row-fluid">
                <div class="row-fluid"><br><br>
                    <div class="span3 " ></div>
                    <div>
                        <h3>RELATÓRIO DE AVISOS EMITIDOS EM 16/02/201</h3>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="page-header">
                <div class="row-fluid">
                    <table class="table ">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nome</th>
                                <th></th>
                                <th>Data</th>
                                <th>Obs</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Frasco</td>
                                <td>e</td>
                                <td>yy</td>
                                <td></td>
                                <td></td>

                            </tr>
                      
                        </tbody>
                    </table>
                </div> 
            </div> 
            <hr>
            </body>
            </html>
