<!DOCTYPE html>
<html lang="pt" >
    <head>
        <meta charset="utf-8">
        <link href="./css/bootstrap.css" rel="stylesheet">
        <link href="./css/pdfs.css" rel="stylesheet">
    </head>
    <body>
        <div class="container-fluid" >
            <div class="row-fluid">

                <div>
                    <h3>IZABELA PANDORA ARRAES DOS SANTOS</h3>
                </div>
            </div>
            <div class="row-fluid"><br>

                <div>
                    <h4>Dados da gestação, parto e nascimento</h4>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="page-header">
                <div class="row-fluid">
                    <table class="table ">
                        <thead>
                            <tr>
                                <th>gestação</th>
                                <th>parto</th>
                                <th>condições de nascimento</th>
                                <th>data de nascimento</th>
                                <th>idade atual</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>normal</td>
                                <td>alterada</td>
                                <td>normal</td>
                                <td>cesariano</td>
                                <td>idade gestacional</td>
                                <td>peso ao nascer</td>
                                <td>apgar</td>
                                <td>data nasciemento</td>
                                <td>idade atual</td>

                            </tr>

                            <tr>
                                <td>X</td>
                                <td></td>
                                <td></td>
                                <td>X</td>
                                <td>38</td>
                                <td>3100</td>
                                <td>?</td>
                                <td>24out12</td>
                                <td>14d</td>

                            </tr>

                        </tbody>
                    </table>

                </div> 
            </div> 
            <div class="row-fluid">
                <h4>QP: sem queixas clínicas</h4>
            </div>
            <div class="row-fluid">
                <div class="page-header">
                    <table class="table ">
                        <thead>
                            <tr>
                                <th>Data do exame</th>
                                <th>mão direita</th>
                                <th>pé</th>
                                <th>diferença</th>
                                <th>Resultado</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>07nov12</td>
                                <td>98%</td>
                                <td>100%</td>
                                <td>2%</td>
                                <td>Sugestivo de oximetria de pulso normal</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="row-fluid">
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam eget ligula eu lectus lobortis condimentum. Aliquam nonummy auctor massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla at risus. Quisque purus magna, auctor et, sagittis ac, posuere eu, lectus. Nam mattis, felis ut adipiscing.</p>
            </div>

            <div class="row-fluid"><br>
                <div class="pull-left">
                    <h5>Conclusões e, se indicadas, recomendações</h5>
                    <h4>SSS</h4>
                </div>


                <div class="pull-right">
                    <h5>Realizado por</h5>
                    <h4>Drª Sheyla Mendes</h4>
                    <p>Pediatra</p>
                    <p>CRM(PA) 6430</p>
                </div>

            </div>
            <hr>
            <div class="row-fluid">
                <div class="pull-right">
                    <h4>CLIMEP - Clínica de Medicina Preventiva do Pará</h4>
                    <p class="floatrigth">Av. Braz de Aguiar nº 410 66.035-000 Belém/PA</p><br>
                    <h5 class="floatrigth">www.climep.com.br - Tel: 3181 - 1644</h5>
                </div>  
            </div>
            <div class="row-fluid">
            </div>
        </div>
        <hr>
    </body>
</html>
