<?php
	$listabairros = mostraBairros();
?>

<h2 class="titulo_cadastro">Edição de Usuario</h2>

<form class="cadastro" action="" method="post">
	<fieldset class="cadastro table-bordered">
		<div class="row-fluid">
			<div class="span1">
				<label for="matricula">Matrícula</label>
				<input id="matricula" name="matricula" type="text" value="<? echo $arr['id']; ?>" disabled/>
			</div>

			<div class="span4">
				<label for="nome">Nome / Titular</label>
				<input id="nome" name="nome" type="text" value="<?php echo $arr['nome']; ?>" />
			</div>

			<div class="span4">
				<label for="sobrenome">Sobrenome</label>
				<input id="sobrenome" name="sobrenome" type="text" value="<?php echo $arr['sobrenome']; ?>" />
			</div>
			<div class="span1">
				<label for="sexo">Sexo</label>
				<select name="sexo" id="sexo">
				<?php
					if ( $arr['sexo'] == 'M' ) {
				?>
						<option value="M" selected >M</option>
						<option value="F">F</option>
				<?php
					} else {
				?>
						<option value="M">M</option>
						<option value="F" selected>F</option>
				<?php
					}
				?>
				</select>
			</div>
			<div class="span2">
				<label for="nascimento">D. Nascimento</label>
				<input id="dp2" name="nascimento" type="text" value="<?php echo $arr['data_nascimento']; ?>" />
			</div>
		</div>
		<div class="row-fluid">	
			<div class="span10">
				<div class="row-fluid">
					<div class="span7">
						<label for="conjuge">Cônjuge</label>
						<input id="conjuge" name="conjuge" type="text" value="<?php echo $arr['conjuge']; ?>" />
					</div>

					<div class="span3 lembrete" >
						<label for="nao">Não imprimir lembrete	
						<?php
							if($arr['imprimir_lembrete'] == 0) {
						?>
						<input id="nao" name="lembrete" value="0" type="checkbox" checked />
						<?php
							} else {
						?>
						<input id="nao" name="lembrete" value="0" type="checkbox" />
						<?php
							}
						?>
						</label>
					</div>

					<div class="span2">
						<label for="pamp">Data PAMP</label>
						<input id="pamp" name="pamp" type="text" />
					</div>
				</div>
		
				<div class="row-fluid">	
					<div class="span6">
						<label for="endereco">Endereço</label>
						<input id="endereco" name="endereco" type="text" value="<?php echo $arr['endereco']; ?>" />
					</div>
					<div class="span1">
						<label for="numero">Número</label>
						<input id="numero" name="numero" type="text" value="<?php echo $arr['numero']; ?>" />
					</div>
					<div class="span3">
						<label for="bairro">Bairro</label>
						<input type="text" name="bairro" data-provide="typeahead" data-items="4" data-source='<?php echo $listabairros ?>' value="<?php echo $arr['bairro']; ?>" />
					</div>
					<div class="span2">
						<label for="cep">CEP</label>
						<input id="cep" name="cep" type="text" value="<?php echo $arr['cep']; ?>" />
					</div>
				</div>
					
				<div class="row-fluid">	
					<div class="span6">
						<label for="complemento">Complemento</label>
						<input id="complemento" name="complemento" type="text" value="<?php echo $arr['complemento']; ?>"  />
					</div>
					<div class="span2">
						<label for="estado">Estado</label>
						<select name="estado" id="estado">
						<?php
							if ($arr['estado'] == 'PA') {
						?>
								<option value="PA" selected >PA</option>
								<option value="PE">PE</option>
						<?php
							} else {
						?>
								<option value="PA">PA</option>
								<option value="PE" selected>PE</option>
						<?php
							}
						?>
						</select>
					</div>
					<div class="span4">
						<label for="cidade">Cidade</label>
						<select name="cidade" id="cidade">
						<?php
							if ($arr['cidade'] == 'Belem') {
						?>
								<option value="Belem" selected>Belém</option>
								<option value="Castanhal">Castanhal</option>
						<?php
							} else {
						?>
								<option value="Belem">Belém</option>
								<option value="Castanhal" selected>Castanhal</option>
						<?php
							}
						?>
						</select>
					</div>
				</div>
				
				<div class="row-fluid">
					<div class="span6">
						<label for="email">Email</label>

						<input id="email" name="email" type="text" value="<?php echo $arr['email']; ?>"/>
					</div>
					<div class="span2">
						<label for="categoria">Categoria</label>
						<select name="categoria" id="categoria">
						<?php
							foreach(buscaCategoria() as $categoria ) {
								if($categoria['id_categoria'] == $arr['categoria_id']) {
						?>
								<option  value="<?php echo $categoria['id_categoria']; ?>" selected="<?php echo $arr['categoria_id']; ?>" > <?php echo $categoria['categoria_nome']; ?> </option>
						<?php
								} else {
						?>
								<option  value="<?php echo $categoria['id_categoria']; ?>"> <?php echo $categoria['categoria_nome']; ?> </option>
						<?php
								}

							}
						?>
						</select>
					</div>
					<div class="span2">
						<label for="origem">Origem</label>
						<select name="origem" id="origem">
						<?php
							foreach(buscaOrigem() as $origem ) {
								if($origem['id_origem'] == $arr['origem_id']) {
						?>
								<option  value=" <?php echo $origem['id_origem']; ?>" selected="<?php echo $arr['origem_id']; ?>" > <?php echo $origem['origem_nome']; ?> </option>
						<?php
								} else {
						?>
								<option  value=" <?php echo $origem['id_origem']; ?>"  > <?php echo $origem['origem_nome']; ?> </option>
						<?php
								}
							}
						?>
						</select>
					</div>
					<div class="span2" >
						<input class="btn btn-mini" id="cadastrar"  type="submit" name="submit" value="Editar"/>
					</div>
				</div>
			</div>
			<div class="span2">
				<fieldset class="menu-botoes table-bordered">
					<legend>Menu</legend>
					<div class="row-fluid">
						<input class="btn btn-mini span12" type="submit" name="encaminhar" value="Encaminhar" />
					</div>
					<div class="row-fluid">
						<input class="btn btn-mini span12" type="submit" name="vacinas" value="Vacinas"/>
					</div>
					<div class="row-fluid">
						<input class="btn btn-mini span12" type="submit" name="procurar" value="Procurar" />
					</div>
					<div class="row-fluid">
						<a class="btn btn-mini span12" href="index.php">Fechar</a>
					</div>
				</fieldset>
			</div>
		</div>
		
	</fieldset>
	
 	<div class="row-fluid">
 		<div class="span7">

			<fieldset class="table-bordered">
				<legend>Contatos Telefônicos</legend>
					<div class="row-fluid">

                                                        <label class="span3" for="ddd-residencial" >Residencial</label>
							<input class="ddd " id="ddd-residencial" name="ddd-residencial" type="text" />
							<input class="fone"  id="fone-residencial" name="tel_residencial" type="text" value="<?php echo $arr['tel_residencial']; ?>"/>
							<input class="fone2" id="fone2-residencial" name="fone2-residencial" type="text" />

					</div>
					<div class="row-fluid">

							<label class="span3" for="ddd-comercial">Comercial</label>
							<input class="ddd" id="ddd-comercial" name="ddd-comercial" type="text" />
							<input class="fone" name="tel_comercial" type="text" value="<?php echo $arr['tel_comercial']; ?>"/>
							<input class="fone2" name="fone2-comercial" type="text" />
					
					</div>
                                
					<div class="row-fluid">

							<label class="span3" for="ddd-apoio">Apoio</label>
							<input class="ddd" id="ddd-apoio" name="ddd-apoio" type="text" />
							<input class="fone" name="tel_apoio" type="text" value="<?php echo $arr['tel_apoio']; ?>"/>
							<input class="fone2" name="fone2-apoio" type="text" />
						
					</div>
			</fieldset>
		</div>
            
		<div class="span5">
		 	<div class="row-fluid">
		 		<fieldset class="atualizado table-bordered">
		 			<legend>Atualizado</legend>
		 		</fieldset>
		 	</div>
			<div class="row-fluid">
				<fieldset class="indicacao table-bordered">
					<legend>Indicação</legend>
				</fieldset>
			</div>
		</div>
            
            <div class="row-fluid">
			<fieldset class="emissao-nf table-bordered">
				<legend>Emissão de Nota Fiscal</legend>
                                    <div class="row-fluid">
                                        
                                       
                                         <div class="span1 nome-nfla"  >
                                            <label for="nome-nf">Nome</label>
                                         </div>   
                                           
                                           <div class="span6 nome-inp" >
                                             <input id="nome-nf" name="nome_nf" type="text" value="<?php echo $arr['nome_nf']; ?>"/>
                                         </div>
                                      
                                          <div class="span1 doc-lab"  >
                                            	<label for="doc-nf">Doc</label>
                                           </div>   
                                                <div class="span4 doc-inp"  >
                                                    <input name="doc_nf" type="text" value="<?php echo $arr['doc_nf']; ?>"/>
                                           </div>
                                      
                                        
				   </div>
			</fieldset>

        </div>        
            
 	<div class="row-fluid">
 		<div class="span7">
			<fieldset class="observacoes table-bordered">
				<legend>Observações</legend>
				<div class="row-fluid">
					<textarea name="observacoes"><?php echo $arr['observacao']; ?></textarea>
				</div>
			</fieldset>
		</div>
 		<div class="span5">
			<fieldset class="table-bordered">
				<legend>Dependentes</legend>
				<div class="row-fluid dependentes"></div>
			</fieldset>
		</div>
	</div>
 </form>
</div>

