<div id="boxes-guia-tiss" class="modal-guia-tiss">

<script async defer src="template/js/bootstrap-tooltip.js"></script>
<script async defer src="template/js/bootstrap-popover.js"></script>
<script async defer src="template/js/bootstrap-datepicker.js"></script>
<script async defer src="template/js/maskedinput.js"></script>
<script async defer src="view/recepcao/js/guia-tiss.js"></script>
<script async defer src="view/js/utils.js"></script>

	<div class="modal-body-guia-tiss">
		<div>
			<a href="#" id="fechar" class="close"> Fechar X</a>
			<h2 class="titulo">Guia de procesimento TISS</h2>
			<fieldset class=" table-bordered" id="DadosDaGuiaTiss" >
				<div class="row-fluid" >
					<div class="span2">
						<label>1 - Regitro ANS:</label>
						<input type="text" class="" name="guia-tiss-registro_ans"/>
					</div>

					<div class="span2">
						<label>2,3 - Nº Guia Principal:</label>
						<input type="text" class="" name="guia-tiss-guia_principal"/>
					</div>

					<div class="span2">
						<label>4 - Data de Autorização :</label>
						<input type="text" class="" id="guia-tiss-data_autorizacao" name="guia-tiss-data_autorizacao"/>
						<script>
						</script>
					</div>

					<div class="span1">
						<label>5 - Senha :</label>
						<input type="text" class="" name="guia-tiss-senha"/>
					</div>

					<div class="span2">
						<label>6 - Data Validade de Senha :</label>
						<input type="text" class="" name="guia-tiss-data_validade_senha"/>
					</div>

					<div class="span2">
						<label>7 - Data Emissão de Senha:</label>
						<input type="text" class="" name="guia-tiss-data_emissao_senha"/>
					</div>
				</div>

				<div class="row-fluid" >
					<div class="span2">
						<label>8 - Número da Carteira :</label>
						<input type="text" class="" maxlength=16 name="guia-tiss-numero_carteira"/>
					</div>

					<div class="span2">
						<label>9 - Plano :</label>
						<input type="text" class="" name="guia-tiss-plano"/>
					</div>

					<div class="span2">
						<label>10 - Validade da Carteira: </label>
						<input type="text" class="" id="guia-tiss-data_validade_carteira" name="guia-tiss-data_validade_carteira"/>
					</div>

					<div class="span3">
						<label>11 - Nome: </label>
						<input type="text" class="" name="guia-tiss-nome"/>
					</div>

					<div class="span2">
						<label>12 - Número CNS: </label>
						<input type="text" class="" name="guia-tiss-numero_cns"/>
					</div>
				</div>

				<div class="row-fluid" >
					<div class="span5">
						<label>13 - Cód. Operadora CNPJ/CPF (CRM ou Cód. + Dígito): </label>
						<input type="text" class="" name="guia-tiss-codigo_operadora"/>
					</div>

					<div class="span4">
						<label>14 - Nome do Contratado : </label>
						<input type="text" class="" name="guia-tiss-nome_contratado"/>
					</div>

					<div class="span2">
						<label>15 - Código CNES: </label>
						<input type="text" class="" name="guia-tiss-codigo_cnes"/>
					</div>
				</div>

				<div class="row-fluid" >
					<div class="span4">
						<label>16 - Nome do Profissional Solicitante:</label>
						<input type="text" class="" name="guia-tiss-nome_profissional_solicitante"/>
					</div>

					<div class="span2">
						<label>17 - Conselho Profissional :</label>
						<input type="text" value="CRM" class="" name="guia-tiss-conselho_profissional"/>
					</div>

					<div class="span2">
						<label>18 - Número Conselho:</label>
						<input type="text" class="" name="guia-tiss-numero_conselho"/>
					</div>

					<div class="span1">
						<label>19 - UF:</label>
						<input type="text" class="" name="guia-tiss-estado"/>
					</div>

					<div class="span2">
						<label>20 - Código CBOS:</label>
						<input type="text" class="" name="guia-tiss-codigo_cbos"/>
					</div>
				</div>

				<div class="row-fluid" >
					<div class="span2">
						<label>21 - Data / Hora da Solicitação:</label>
						<input type="text" class="" name="guia-tiss-data_hora_solicitacao"/>
					</div>

					<div class="span2">
						<label>22 - Caráter da Solicitação: </label>
						<select name="guia-tiss-carater_solicitacao" >
						<?php
						foreach(listaCaraterSolicitacao() as $carater) {
							unset($selected);
							if($carater['nome'] == 'E') {
								$selected = "selected = selected";
							}
						?>
							<option <?php echo $selected; ?> rel="popover" data-content="<?php echo $carater['descricao']; ?>" idRegistro="<?php echo $carater['id']; ?>" value="<?php echo $carater['nome']; ?>" ><?php echo $carater['nome']; ?></option>
						<?php
						}
						?>
						</select>
					</div>

					<div class="span1" >
						<label>23 - CID 10 </label>
						<select onchange="setIndicacao();" name="guia-tiss-cid" >
							<option>-----</option>
						<?php
						foreach(listaCID() as $cid) {
						?>
							<option idRegistro="<?php echo $cid['id']; ?>" value="<?php echo $cid['nome']; ?>" ><?php echo $cid['nome']; ?> </option>
						<?php
						}
						?>
						</select>
					</div>

					<div class="span6">
						<label>24 - Indicação Clínica (Obrigatório se pequenas cirugia, terapia, consulta de referência e alto custo):</label>
						<input type="text" class="" name="guia-tiss-indicacao_clinica"/>
					</div>

				</div>

				<div class="row-fluid" >
					<div class="span1">
						<label>25 - Tabela:</label>
						<input type="text" class="" name="guia-tiss-tabela"/>
					</div>

					<div class="span2">
						<label>30 - Cód. do Executante:</label>
						<input type="text" class="" name="guia-tiss-codigo_executante"/>
					</div>

					<div class="span4">
						<label>31 - Nome do Contratado:</label>
						<input type="text" class="" name="guia-tiss-nome_executante"/>
					</div>

					<div class="span1">
						<label>32 - T.L.:</label>
						<input type="text" class="" value="08" name="guia-tiss-tl"/>
					</div>

					<div class="span3">
						<label>33,34,35 - Logradouro, nº Compl:</label>
						<input type="text" class="" name="guia-tiss-logradouro"/>
					</div>
				</div>

				<div class="row-fluid" >
					<div class="span2">
						<label>36 - Município:</label>
						<input type="text" class="" name="guia-tiss-municipio"/>
					</div>

					<div class="span2">
						<label>37 - UF :</label>
						<input type="text" class="" name="guia-tiss-estado2"/>
					</div>

					<div class="span2">
						<label>38 - Cód. IBGE:</label>
						<input type="text" class="" name="guia-tiss-codigo_ibge"/>
					</div>

					<div class="span1">
						<label>39 - CEP :</label>
						<input type="text" class="" id="guia-tiss-cep" name="guia-tiss-cep"/>
					</div>

					<div class="span2">
						<label>40 - CNES:</label>
						<input type="text" class="" name="guia-tiss-cnes"/>
					</div>

					<div class="span2">
						<label>40a - Cód do Executante:</label>
						<input type="text" class="" name="guia-tiss-codigo_executante"/>
					</div>
				</div>

				<div class="row-fluid" >
					<div class="span3">
						<label>41 - Nome do Profissional Executante:</label>
						<input type="text" class="" name="guia-tiss-nome_profissional_executante"/>
					</div>

					<div class="span2">
						<label>42 - Conselho Profissional:</label>
						<input type="text" value="CRM" class="" name="guia-tiss-conselho_profissional2"/>
					</div>

					<div class="span2">
						<label>43 - Número Conselho:</label>
						<input type="text" class="" name="guia-tiss-numero_conselho2"/>
					</div>

					<div class="span2">
						<label>44 - UF:</label>
						<input type="text" value="PA" class="" name="guia-tiss-estado3"/>
					</div>

					<div class="span2">
						<label>45 - Cód. CBOS:</label>
						<input type="text" class="" name="guia-tiss-codigo_cbos2"/>
					</div>
				</div>

				<div class="row-fluid" >
					<div class="span2">
						<label>45a - Grau de Partições:</label>
						<input type="text" class="" name="guia-tiss-grau_particoes"/>
					</div>

					<div class="span2">
						<label>46 - Tipo de Atendimento:</label>
						<select name="guia-tiss-tipo_atendimento" >
							<option></option>
						<?php
						foreach(listaTipoAtendimento() as $tipoAtendimento) {
							unset($selected);
							if($tipoAtendimento['nome'] == '05') {
								$selected = "selected = selected";
							}
						?>
							<option <?php echo $selected; ?> rel="popover" data-content="<?php echo $tipoAtendimento['descricao']; ?>" idRegistro="<?php echo $tipoAtendimento['id']; ?>" value="<?php echo $tipoAtendimento['nome']; ?>" ><?php echo $tipoAtendimento['nome']; ?></option>
						<?php
						}
						?>
						</select>
					</div>

					<div class="span2">
						<label>47 - Indicação de Acidente:</label>
						<select name="guia-tiss-indicacao_acidente" >
						<?php
						foreach(listaIndicacaoAcidente() as $tipoIndicacao) {
							unset($selected);
							if($tipoIndicacao['nome'] == 2) {
								$selected = "selected = selected";
							}
						?>
							<option <?php echo $selected; ?> rel="popover" data-content="<?php echo $tipoIndicacao['descricao']; ?>" idRegistro="<?php echo $tipoIndicacao['id']; ?>" value="<?php echo $tipoIndicacao['nome']; ?>" ><?php echo $tipoIndicacao['nome']; ?></option>
						<?php
						}
						?>
						</select>
					</div>

					<div class="span2">
						<label>48-Tipo de Saída</label>
						<select name="guia-tiss-tipo_saida" >
						<?php
						foreach(listaTipoSaida() as $tipoSaida) {
							unset($selected);
							if($tipoSaida['nome'] == 5) {
								$selected = "selected = selected";
							}
						?>
							<option <?php echo $selected; ?> rel="popover" data-content="<?php echo $tipoSaida['descricao']; ?>" idRegistro="<?php echo $tipoSaida['id']; ?>" value="<?php echo $tipoSaida['nome']; ?>" ><?php echo $tipoSaida['nome']; ?></option>
						<?php
						}
						?>
						</select>
					</div>

					<div class="span2">
						<label>49 - Tipo de Doença:</label>
						<select name="guia-tiss-tipo_doenca" >
						<?php
						foreach(listaTipoDoenca() as $tipoDoenca) {
							unset($selected);
							if($tipoDoenca['nome'] == 'A') {
								$selected = "selected = selected";
							}
						?>
							<option  <?php echo $selected; ?> rel="popover" data-content="<?php echo $tipoDoenca['descricao']; ?>" idRegistro="<?php echo $tipoDoenca['id']; ?>"value="<?php echo $tipoDoenca['nome']; ?>" ><?php echo $tipoDoenca['nome']; ?></option>
						<?php
						}
						?>
						</select>
					</div>

					<div class="span2">
						<label>50 - Tempo de Doença:</label>
						<select name="guia-tiss-tempo_doenca" >
						<?php
						foreach(listaTempoDoenca() as $tempoDoenca) {
							unset($selected);
							if($tempoDoenca['nome'] == 'A') {
								$selected = "selected = selected";
							}
						?>
							<option  <?php echo $selected; ?> rel="popover" data-content="<?php echo $tempoDoenca['descricao']; ?>" idRegistro="<?php echo $tempoDoenca['id']; ?>" value="<?php echo $tempoDoenca['nome']; ?>" ><?php echo $tempoDoenca['nome']; ?></option>
						<?php
						}
						?>
						</select>
					</div>
				</div><br>

				<div class="row-fluid" >
					<div class="span2">
						<label>65 - Tot. Procedimentos R$</label>
						<input type="text" value="0" class="" name="guia-tiss-total_procedimentos"/>
					</div>

					<div class="span2">
						<label>66 - Tot. Taxas Aluguéis R$</label>
						<input type="text" value="0" class="" name="guia-tiss-total_taxas_alugueis"/>
					</div>

					<div class="span2">
						<label>67 - Total Materiais R$</label>
						<input type="text" value="0" class="" name="guia-tiss-total_materiais"/>
					</div>

					<div class="span2">
						<label>68 - Total Medicamento R$</label>
						<input type="text" value="0" class="" name="guia-tiss-total_medicamento"/>
					</div>

					<div class="span1">
						<label>69 - Diárias</label>
						<input type="text" value="0" class="" name="guia-tiss-total_diarias"/>
					</div>

					<div class="span2">
						<label>70 - Tot. Gases Medicinais R$</label>
						<input type="text" value="0" class="" name="guia-tiss-total_gases_medicinais"/>
					</div>
				</div>

				<div class="row-fluid" >
					<div class="span2">
						<label>71 - Total Geral da Guia R$</label>
						<input type="text" class="" name="guia-tiss-total_geral_guia"/>
					</div>

					<div class="span2">
						<label>86 - Data do Solicitante</label>
						<input type="text" class="" name="guia-tiss-data_solicitante"/>
					</div>

					<div class="span2">
						<label>87 - Data Resp. Autorização</label>
						<input type="text" class="" name="guia-tiss-data_responsavel_autorizacao"/>
					</div>

					<div class="span2">
						<label>88 - Data Benef. Responsável </label>
						<input type="text" class="" name="guia-tiss-data_beneficio_responsavel"/>
					</div>

					<div class="span2">
						<label>89 - Data Prestador Executante </label>
						<input type="text" class="" name="guia-tiss-data_prestador_executante"/>
					</div>
				</div> <br>

				<div class="row-fluid">
					<div class="span6">
						<label>64 - Observações</label>
						<textarea name="guia-tiss-observacoes" ></textarea>
					</div>

					<div class="span1" id="" >
						<input type="button" class="btn btn-mini span12" onclick="insereGuiaTiss();" name="grava_guia_tiss" value="Enviar" >
					</div>

					<div class="span1" >
						<input type="button" class="btn btn-mini span12" onclick="imprimirGuiaTiss();" name="" value="Imprimir"/>
					</div>
					
					<div class="span1" >
						<input type="button" class="btn btn-mini span12" onclick="fechar_modal('boxes-guia-tiss');" name="" value="Fechar"/>
					</div>

					<div class="span3" id="" style="margin-left: 15px;">
						<label>
							<h4>Total de Procedimentos: <?php echo $qtd_procs; ?></h4>
						</label>
					</div>
				</div>
			</fieldset>
		</div>
	</div>
</div>
