<div id="boxes-busca" class="modal modal-busca hide fade">
	<div id="dialog-busca" class=" modal-body-busca" >
		<div id="procura"><a href="#" id="fechar" class="close"/>Fechar X</a>
			<h2 class="titulo">Procura</h2>
			<hr>
			<form class="form-busca" action="" method="post">
				<fieldset class="busca">
					<legend>Opções de busca</legend>

					<div class="row-fluid">
						<div class="span8">
							<div class="row-fluid ">
								<div class="span8">
									<div class="span3">
										<label class="nome-text" >Nome:</label>
									</div>

									<div class="span5 " >
										<input id="nome" name="nome" type="text" />
									</div>
								</div>
							</div>

							<div class="row-fluid ">
								<div class="span8">
									<div class="span3 "  >
										<label class="nome-text">Nascimento:</label>
									</div>

									<div class="span5 " >
										<input data-mask='99/99/9999' id="nascimento" name="nascimento" type="text" onblur="dateComplete($(this));"/>
									</div>
								</div>
							</div>

							<div class="row-fluid ">
								<div class="span8">
									<div class="span3 "  >
										<label class="nome-text">Outro:</label>
									</div>

									<div class="span5 " >
										<input class="outro" id="outro" name="outroc" type="text" style="display: none"/>
										<input class="outro" id="outrotelefone" name="outrotelefone" type="text" data-mask="(99)9999-9999 " />
										<input class="outro" id="outrocpf" name="outrocpf" type="text" data-mask="999-999-999-99" style="display: none"/>
									</div>

								</div>

							</div>
						</div> 

						<div class="span4" >
							<div class="row-fluid " >
								<ul class="thumbnails">
									<li class="span4 tipo-list" >
										<fieldset class=" busca thumbnail">
											<legend>Tipo</legend>
											<div class="controls">
												<div class="row-fluid">
													<label class="radio" >
														<input type="radio" name="opcao-tipo" id="tudo" value="tudo" checked />
														Tudo
													</label>
												</div>
												<div class="row-fluid">
													<label class="radio" >
														<input type="radio" name="opcao-tipo" id="familiares" value="familiares"  />
														Familhas
													</label>
												</div>
												<div class="row-fluid" >
													<label class="radio">
														<input type="radio" name="opcao-tipo" id="extensao" value="membros" />
														Membros
													</label>
												</div>

											</div>
										</fieldset>
									</li>
									<li class="span4 option-butoes">
										<fieldset class="menu-butoes busca">
											<legend>Opções</legend>
											<div class="row-fluid" >
												<input class="btn btn-mini span12" type="button" name="procurar" value="Procurar" id="submit_busca"/>
											</div>
											<div class="row-fluid" >
												<input class="btn btn-mini span12" type="button" name="vacinas" value="Cancelar" onClick="fechar_modal('boxes-busca')"/>
											</div>
											<div class="row-fluid" style="visibility: hidden;">
												<input class="btn btn-mini span12" type="button" name="confirmar" value="Confirmar" />
											</div>
										</fieldset>
									</li>
								</ul>
							</div>
						</div>
					</div>

					<div class="row-fluid" >
						<div class="span11 radio-list">
							<div class="span8">
								<div class="span2" >
									<label name="telefone" >
										<input type="radio" id="telefone" name="opcao" value="telefone" checked onclick="addmask($(this))"/>
										Telefone
									</label>
								</div>

								<div class="span2 " >
									<label name="cpf">
										<input type="radio" id="cpf" name="opcao" value="cpf" onclick="addmask($(this))" />
										CPF
									</label>
								</div>

								<div class="span2">
									<label name="conjuge">
										<input type="radio" id="conjuge" name="opcao"  value="conjuge" onclick="addmask($(this))"/>
										Cônjuge
									</label>
								</div>

								<div class="span2">
									<label   name="email">
										<input type="radio" id="email" name="opcao"  value="email" onclick="addmask($(this))" />
										E-mail
									</label>
								</div>
							</div>

							<div class="span3 checkbox-option"  >
								<label>
									<input id="ArquivoMorto" value="0" type="checkbox" />
									Incluir Arquivo Morto
								</label>
							</div>
						</div>
					</div>
				</fieldset>
			</form>
			<hr>
		</div>

		<div>
			<div id='modalProcurarRegistrosEncontrados'></div>
			<div class="row-fluid">
				<div class="table"  id="tabela_busca" style="height:300px; overflow: auto;">
					<div class="active">
						<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed">
							<thead>
								<tr>
									<th>Tipo</th>
									<th>Matrícula</th>
									<th>Nome</th>
									<th>Email</th>
									<th>Telefone Residencial</th>
								</tr>
							</thead>
							<tbody>
							</tbody>
						</table>
						<hr/>
					</div>
				</div>
                            <div id="tabela_busca_pagnacao">
                            </div>
			</div>
		</div>
	</div>
</div>
<script>

    function addmask(field){
        var valor = field.val();
        if(valor == 'telefone'){
            $("input.outro").val("");
            $("input#outro").hide();
            $("input#outrocpf").hide();
            $("input#outrotelefone").show();
        }else if (valor == 'cpf'){
            $("input.outro").val("");
            $("input#outro").hide();
            $("input#outrotelefone").hide();
            $("input#outrocpf").show();
        }else{
            $("input.outro").val("");
            $("input#outrocpf").hide();
            $("input#outrotelefone").hide();
            $("input#outro").show();
        }
    }

</script>
