<div id="boxes-guia-tiss">

<script async defer src="template/js/bootstrap-tooltip.js"></script>
<script async defer src="template/js/bootstrap-popover.js"></script>
<script async defer src="template/js/bootstrap-datepicker.js"></script>
<script async defer src="template/js/maskedinput.js"></script>
<script async defer src="view/recepcao/js/guia-tiss.js"></script>
<script async defer src="view/js/utils.js"></script>

	<div class="modal-body-guia-tiss" style=" background-image: url('template/img/body-bg.png');">
		<div>
			<a href="#" id="fechar" class="close"> Fechar X</a>
			<h2 class="titulo">Guia de procesimento TISS</h2>
			<fieldset class="table-bordered">
				<div class="row-fluid" >
					<div class="span2">
						<label>1 - Regitro ANS :</label>
						<input type="text" class="" name="guia-tiss-consulta-registro_ans"/>
					</div>

					<div class="span2">
						<label>2 - Número da Guia :</label>
						<input type="text" class="" name="guia-tiss-consulta-guia_principal"/>
					</div>

					<div class="span2">
						<label>3 - Data Emissão da Guia :</label>
						<input type="text" id="guia-tiss-consulta-data_autorizacao" name="guia-tiss-consulta-data_autorizacao" onblur="setaCamposDataConsulta();" />
					</div>

					<div class="span2">
						<label>4 - Número da Carteira :</label>
						<input type="text" name="guia-tiss-consulta-numero_carteira"/>
					</div>

					<div class="span2">
						<label>5 - Plano :</label>
						<input type="text" name="guia-tiss-consulta-plano"/>
					</div>

					<div class="span2">
						<label>6 - Validade da Carteira :</label>
						<input type="text" class="" id="guia-tiss-consulta-data_validade_carteira" name="guia-tiss-consulta-data_validade_carteira"/>
					</div>
				</div>

				<div class="row-fluid" >
					<div class="span3">
						<label>7 - Nome :</label>
						<input type="text" class="" name="guia-tiss-consulta-nome"/>
					</div>

					<div class="span2">
						<label>8 - Número CNS :</label>
						<input type="text" class="" name="guia-tiss-consulta-numero_cns"/>
					</div>

					<div class="span2">
						<label>9 - Cód. Operadora CNPJ/CPF:</label>
						<input type="text" class="" name="guia-tiss-consulta-codigo_operadora"/>
					</div>

					<div class="span3">
						<label>10 - Nome do Contratado : </label>
						<input type="text" class="" name="guia-tiss-consulta-nome_contratado"/>
					</div>

					<div class="span2">
						<label>11 - Código CNES: </label>
						<input type="text" class="" name="guia-tiss-consulta-codigo_cnes"/>
					</div>
				</div>

				<div class="row-fluid" >
					<div class="span1">
						<label>12 - T.Log :</label>
						<input type="text" class="" name="guia-tiss-consulta-tl"/>
					</div>

					<div class="span4">
						<label>13,14,15 - Logradouro, nº Compl:</label>
						<input type="text" class="" name="guia-tiss-consulta-logradouro"/>
					</div>

					<div class="span2">
						<label>16 - Município:</label>
						<input type="text" class="" name="guia-tiss-consulta-municipio"/>
					</div>

					<div class="span1">
						<label>17 - UF :</label>
						<input type="text" class="" name="guia-tiss-consulta-estado"/>
					</div>

					<div class="span2">
						<label>18 - Cód. IBGE:</label>
						<input type="text" class="" name="guia-tiss-consulta-codigo_ibge"/>
					</div>

					<div class="span1">
						<label>19 - CEP :</label>
						<input type="text" class="" id="guia-tiss-consulta-cep" name="guia-tiss-consulta-cep"/>
					</div>
				</div>

				<div class="row-fluid" >
					<div class="span4">
						<label>20 - Nome do Profissional Executante:</label>
						<input type="text" class="" name="guia-tiss-consulta-nome_profissional_executante"/>
					</div>

					<div class="span2">
						<label>21 - Conselho Profissional:</label>
						<input type="text" value="CRM" class="" name="guia-tiss-consulta-conselho_profissional2"/>
					</div>

					<div class="span2">
						<label>22 - Número Conselho:</label>
						<input type="text" class="" name="guia-tiss-consulta-numero_conselho2"/>
					</div>

					<div class="span1">
						<label>23 - UF:</label>
						<input type="text" value="PA" class="" name="guia-tiss-consulta-estado2"/>
					</div>

					<div class="span2">
						<label>24 - Cód. CBOS:</label>
						<input type="text" class="" name="guia-tiss-consulta-codigo_cbos2"/>
					</div>
				</div>

				<div class="row-fluid" >

					<div class="span2">
						<label>25 - Tipo de Doença:</label>
						<select name="guia-tiss-consulta-tipo_doenca" >
						<?php
						foreach(listaTipoDoenca() as $tipoDoenca) {
						?>
							<option rel="popover" data-content="<?php echo utf8_encode($tipoDoenca['descricao']); ?>" value="<?php echo $tipoDoenca['id']; ?>" ><?php echo $tipoDoenca['nome']; ?></option>
						<?php
						}
						?>
						</select>
					</div>

					<div class="span2">
						<label>26 - Tempo de Doença:</label>
						<select name="guia-tiss-consulta-tempo_doenca" >
						<?php
						foreach(listaTempoDoenca() as $tempoDoenca) {
						?>
							<option rel="popover" data-content="<?php echo utf8_encode($tempoDoenca['descricao']); ?>" value="<?php echo $tempoDoenca['id']; ?>" ><?php echo $tempoDoenca['nome']; ?></option>
						<?php
						}
						?>
						</select>
					</div>

					<div class="span2">
						<label>27 - Indicação de Acidente:</label>
						<select name="guia-tiss-consulta-indicacao_acidente" >
						<?php
						foreach(listaIndicacaoAcidente() as $tipoIndicacao) {
							if($tipoIndicacao['nome'] == 5) {
								$selected = "selected = selected";
							}
						?>
							<option <?php echo $selected; ?> rel="popover" data-content="<?php echo utf8_encode($tipoIndicacao['descricao']); ?>" value="<?php echo $tipoIndicacao['id']; ?>" ><?php echo $tipoIndicacao['nome']; ?></option>
						<?php
						}
						?>
						</select>
					</div>

					<div class="span2" >
						<label>28 - CID Principal :</label>
						<select onchange="setIndicacao();" name="guia-tiss-consulta-cid1" >
							<option>-----</option>
						<?php
						foreach(listaDoencas() as $doenca) {
						?>
							<option value="<?php echo $doenca['id_doencas']; ?>" ><?php echo $doenca['nome']; ?> </option>
						<?php 
						}
						?>
						</select>
					</div>

					<div class="span1" >
						<label>29 - CID (2) </label>
						<select onchange="setIndicacao();" name="guia-tiss-consulta-cid2" >
							<option>-----</option>
						<?php
						foreach(listaDoencas() as $doenca) {
						?>
							<option value="<?php echo $doenca['id_doencas']; ?>" ><?php echo $doenca['nome']; ?> </option>
						<?php 
						}
						?>
						</select>
					</div>

					<div class="span1" >
						<label>30 - CID (3) </label>
						<select onchange="setIndicacao();" name="guia-tiss-consulta-cid3" >
							<option>-----</option>
						<?php
						foreach(listaDoencas() as $doenca) {
						?>
							<option value="<?php echo $doenca['id_doencas']; ?>" ><?php echo $doenca['nome']; ?> </option>
						<?php 
						}
						?>
						</select>
					</div>

					<div class="span1" >
						<label>31 - CID (4) </label>
						<select onchange="setIndicacao();" name="guia-tiss-consulta-cid4" >
							<option>-----</option>
						<?php
						foreach(listaDoencas() as $doenca) {
						?>
							<option value="<?php echo $doenca['id_doencas']; ?>" ><?php echo $doenca['nome']; ?> </option>
						<?php 
						}
						?>
						</select>
					</div>
				</div>

				<div class="row-fluid" >
					<div class="span2">
						<label>32 - Data Atendimento :</label>
						<input type="text" class="" name="guia-tiss-consulta-data_atendimento"/>
					</div>

					<div class="span2">
						<label>33 - Código Tabela :</label>
						<input type="text" class="" name="guia-tiss-consulta-codigo_tabela"/>
					</div>

					<div class="span2">
						<label>34 - Código Procedimento :</label>
						<input type="text" class="" name="guia-tiss-consulta-codigo_procedimento"/>
					</div>

					<div class="span2">
						<label>35 - Tipo de Atendimento :</label>
						<select name="guia-tiss-consulta-tipo_atendimento" >
						<?php
						foreach(listaTipoAtendimento() as $tipoAtendimento) {
						?>
							<option rel="popover" data-content="<?php echo utf8_encode($tipoAtendimento['descricao']); ?>" value="<?php echo $tipoAtendimento['id']; ?>" ><?php echo $tipoAtendimento['nome']; ?></option>
						<?php 
						}
						?>
						</select>
					</div>

					<div class="span2">
						<label>36 - Tipo de Saída :</label>
						<select name="guia-tiss-consulta-tipo_saida" >
						<?php
						foreach(listaTipoSaida() as $tipoSaida) {
						?>
							<option rel="popover" data-content="<?php echo utf8_encode($tipoSaida['descricao']); ?>" value="<?php echo $tipoSaida['id']; ?>" ><?php echo $tipoSaida['nome']; ?></option>
						<?php
						}
						?>
						</select>
					</div>
				</div>

				<div class="row-fluid">
					<div class="span11">
						<label>37 - Observações</label>
						<textarea name="guia-tiss-consulta-observacoes" ></textarea>
					</div>
				</div>

				<div class="row-fluid" >
					<div class="span3">
						<label>38 - Data do e assinatura do Médico </label>
						<input type="text" class="" name="guia-tiss-consulta-data_solicitante"/>
					</div>

					<div class="span3">
						<label>39 - Data Benef. Responsável </label>
						<input type="text" class="" name="guia-tiss-consulta-data_beneficio_responsavel"/>
					</div>
				</div> <br>

				<div class="row-fluid">
					<div class="span2" id="" >
						<input type="button" class="btn btn-mini span12" onclick="insereGuiaTissConsulta();" name="grava_guia_tiss" value="Gravar e Imprimir" >
					</div>

					<div class="span2" >
						<input type="button" class="btn btn-mini span12" onclick="fechar_modal('boxes-guia-tiss');" name="" value="Abandona"/>
					</div>
				</div>
			</fieldset>
		</div>
	</div>
</div>

