<div class="table" id="tabela_busca">
	<div class="active">
		<table cellpadding="0" cellspacing="0" border="0"  class="table table-striped table-bordered table-condensed" >
			<thead>
				<tr>
					<th>Matrícula</th>
					<th>Nome</th>
					<th>Membro</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($arr as $array) { ?>
				<tr id="tr_pesquisa" ondblClick="editarMembro(<?php echo ($array['flag'] == 'T') ? $array['cliente_id'] : $array['fk_titular_id'] ; ?>,<?php echo $array['cliente_id'] ?>)">
						<td class="dataTables_empty" align="center"><?php echo $array['cliente_id']; ?></td>
						<td class="dataTables_empty" align="center"><?php echo $array['nome']; ?></td>
						<td class="dataTables_empty" align="center"><?php echo $array['membro']; ?></td>
					</tr>
				<?php } ?>
			</tbody>
		</table>
		<hr/>
	</div>
</div>