<link type="text/css" rel="stylesheet" href="view/financeiro/css/index.css" />
<div class="row-fluid">
	<div id="baixacrconsultarduplicatas">
    <script async defer language="javascript" src="view/financeiro/js/baixacr.js"></script>
        <div class="row-fluid">
            <h2 class="titulo">CTREC - Consulta Parcelas Fatura </h2>
            <hr style="margin-top: -5px;">
            <p style="margin-left: 15px;">
                Preencha os campos abaixo e clique em<b> 'Localizar'</b> para iniciar a pesquisa na base de dados. Clique em <b>'Novo'</b> para inclusão.
            </p>
        </div>
        <div class="row-fluid" >
            <fieldset class="table-bordered">
                <div class="row-fluid">
                    <div class="span8" >
			<div class="row-fluid">
				<div class="span3">
					<label>Cliente:</label>
				</div>
				<div class="span1">
					<input type="text" onchange="buscaPorCodigoCR('cliente','baixa');" name="baixacr-cod_cliente" />
				</div>
				<div class="span6">
					<input type="text" name="baixacr-cliente" />
				</div>
			</div>
			<div class="row-fluid">
				<div class="span3">
					<label>Empresa:</label>
				</div>
				<div class="span1">
					<input type="text" onchange="buscaPorCodigoCR('empresa','baixa');" name="baixacr-cod_empresa" />
				</div>
				<div class="span6">
					<input type="text" name="baixacr-empresa" />
				</div>
			</div>
			<div class="row-fluid">
				<div class="span3">
					<label>Banco:</label>
				</div>
				<div class="span1">
					<input type="text" onchange="buscaPorCodigoCR('banco','baixa');" name="baixacr-cod_banco"/>
				</div>
				<div class="span6">
					<input type="text" name="baixacr-banco" />
				</div>
			</div>
                        <div class="row-fluid">
                            <div class="span3">
                                <label>Moeda:</label>
                            </div>
                            <div class="span7">
                                <select name="baixacr-moeda">
                                    <option value="00" > TODOS </option>
                                    <?php
                                    $moedas = buscaTodasMoedas();
                                    foreach ($moedas as $moeda) {
                                        ?>
                                        <option value="<?php echo $moeda['id']; ?>"> <?php echo $moeda['nome']; ?> </option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="span3">
                                <label>Status:</label>
                            </div>
                            <div class="span7">
                                <select name="baixacr-status">
                                    <option value="00" > TODOS </option>
                                    <?php
                                    $statusConsultaDup = buscaTodosStatusDuplicata();
                                    foreach ($statusConsultaDup as $statusConsulta) {
                                        ?>
                                        <option value="<?php echo $statusConsulta['id']; ?>"> <?php echo $statusConsulta['nome']; ?> </option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="span3">
                                <label>Selecionado Por:</label>
                            </div>
                            <div class="span7">
                                <select name="baixacr-selecionado_por">
                                    <option value="1" > DATA DE LANCAMENTO</option>
                                    <option value="2" > DATA DE VENCIMENTO </option>
                                    <option value="3" > DATA DE EMISSAO </option>
                                    <option value="4" > DATA DE BAIXA </option>
                                </select>
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="span3">
                                <label>De:</label>
                            </div>
                            <div class="span3">
                                <input data-mask="99/99/9999" type="text" name="baixacr-data_inicio"/>
                            </div>
                            <div class="span1">
                                <label>Até:</label>
                            </div>
                            <div class="span3">
                                <input data-mask="99/99/9999" type="text" name="baixacr-data_fim"/>
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="span3">
                                <label>Ordenado Por:</label>
                            </div>
                            <div class="span7">
                                <select name="baixacr-ordenado_por">
                                    <option value="1" > STATUS </option>
                                    <option value="2" > NOME </option>
                                    <option value="3" > DATA DE EMISSAO </option>
                                    <option value="4" > DATA DE VENCIMENTO </option>
                                    <option value="5" > MOEDA </option>
                                    <option value="6" > BANCO </option>
                                    <option value="7" > TIPO DOCUMENTO </option>
                                </select>
                            </div>
                            <!--</div>-->
                        </div>
                    </div>
                    <div id="showlistcheck" class="span4" style="display: none">
                        <div>
                            <fieldset class="table-bordered">
                                <legend>Cartões</legend>
								<?php
									$listaCartao = buscaTodosCartoes();
									foreach ($listaCartao as $lista) {
								?>
								<div class="row-fluid">
									<div class="span1">
										<input type="checkbox" name="baixacr-cartao[]" value="<?php echo $lista['id']; ?>">
									</div>
									<div class="span10">
										<label class="checkbox">
											<?php echo $lista['nome']; ?>
										</label>
									</div>
                                </div>
								<?php
									}
								?>
                            </fieldset>
                        </div>
                    </div>
                </div>

                <div class="row-fluid">
                    <hr>
                    <div class="span3">

                        <div class="row-fluid">
                            <label>
                                <input id="showinput" type="checkbox" name="op" onclick="showinput();" />
                                Selecione uma fatura
                            </label>
                        </div>
                        <div class="row-fluid">
                            <label>
                                <input id="showlist"  type="checkbox" name="" onclick="showlist();" />
                                Agregado por Cartão
                            </label>
                        </div>
                    </div>
                    <div id="campotexto" class="span3" style="display: none;">
                        <div class="row-fluid">
                            <div class="span11">
                                <label>Numero Fatura:</label>
                                <input type="text" id="numero_fatura" name="baixacr-numero_controle">
                            </div>
                        </div><br>

                    </div>
                </div>
                <div class="row-fluid">
                    <div class="offset6">
                    <a href="#" class="btn" onclick="cleanFormConsultaBaixaCr();"> Limpar </a>
                        <a href="#" class="btn" onclick="criaListaBaixaCR();"><i class="icon-search"></i> Localizar </a>
                    </div>
                </div>
        </div>

        </fieldset>
    </div><br>
</div>

<div id="baixarclocalizar" class="row-fluid" style="display: none;">
    <div class="row-fluid">
        <h2 class="titulo">Fatura Baixa CR</h2>
        <hr style="margin-top: -5px;">
    </div>
    <div class="row-fluid">
        <div class=" span3" style="margin-left: 10px; margin-bottom: 10px;">
            <a href="#" onclick="voltarConsultabaixarc();" class="btn"><i class="icon-circle-arrow-left"></i> Voltar</a>
            <a href="#" onclick="imprimirBaixacr();" class="btn"><i class="icon-print"></i> Imprimir</a>
            <br>
        </div>
        <fieldset class="table-bordered">
            <div class="row-fluid" id="tabelabaixarc" >
                <table class="tablebigfinanceiro table-condensed table-bordered table-striped ">
                    <thead>
                        <tr>
                            <th> STATUS </th>
                            <th> FATURA </th>
                            <th> PARCELA </th>
                            <th> CLIENTE </th>
                            <th> TIPO CLIENTE </th>
                            <th> EMISSÃO </th>
                            <th> VENCIMENTO </th>
                            <th> VALOR </th>
                            <th> DESCONTO </th>
                            <th> MULTA </th>
                            <th> JUROS (DIA) </th>
                            <th> RECEBIDO </th>
                            <th> TOTAL A RECEBER </th>
                            <th> MOEDA </th>
                            <th> BANCO </th>
                            <th> TIPO DOCUMENTO </th>
                            <th> PLANO CONTAS </th>
                            <th> DATA BAIXA </th>
                            <th> USUÁRIO </th>
                            <!-- <th> OCORRENCIA </th> -->
                            <th> DIAS ATRASO </th>
                            <!-- <th> RECEBER SEM JUROS </th> -->
                            <th> CONTA BAIXADA </th>
                        </tr>
                    </thead>

                    <tbody id="baixarc" >
                    </tbody>
                </table>
            </div>
        </fieldset>
    </div>
</div>

<div id="pesquisar_baixarc" style="display: none;">
    <div id="dialog-pesbaixarc" >
<!--        <div id=""><a href="#" id="fechar" class="close" />Fechar X</a>
            <h2 class="titulo">Pesquisar  Baica RC</h2>
            <hr style="margin-top: -4px;"/>
            <div class="row-fluid">
                <fieldset class="table-bordered">
                    <div class="row-fluid" id="tabelapesbaixarc">
                        <table class="table table-condensed table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th> PARCELA </th>
                                    <th> VENCIMENTO </th>
                                    <th> VALOR </th>
                                    <th> MULTA </th>
                                    <th> JUROS </th>
                                    <th> DESCONTO </th>
                                    <th> VALOR_PAGO </th>
                                    <th> TOTAL_PAGAR </th>
                                    <th> STATUS </th>
                                </tr>
                            </thead>

                            <tbody id="" > </tbody>
                        </table>
                    </div>
                </fieldset>
                <br>
                <div class="offset11">
                    <ul class="thumbnails">
                        <li>
                            <a href="#" class="btn span12" onclick="fechar_modal('pesquisar_baixarc');" id="" ><i class="icon-remove"></i> Fechar </a>
                        </li>
                    </ul>
                </div>
            </div>
            <br>
        </div>-->
	<div id="">
		
        <div class="row-fluid">
            <div class="row-fluid">
                <h2 id="baixacr-modal-titulo" class="titulo"> </h2>
                <hr style="margin-top: -5px;">
                <p style="margin-left: 15px;">
                    Preencha os campos abaixo informando que Conta Corrente será usada para receber o pagamento.
                </p>
            </div>
        </div>
        <div class="row-fluid">
            <fieldset class="table-bordered">
                <div class="row-fluid">
                    <div class="span2">
                        <label>Data Operação:</label>
                        <input data-mask="99/99/9999" type="text" name="baixacr-modal-data_operacao"/>
                    </div>
                    <div class="span6">
                        <label>Conta Corrente:</label>
                        <input type="text" name="baixacr-modal-conta_corrente"/>
                    </div>
                    <div class="span2">
                        <label>Valor:</label>
                        <input type="text" name="baixacr-modal-valor"/>
                    </div>
                </div><br>
                <!-- <div class="row-fluid">
                    <fieldset class="table-bordered">
                        <legend>Dados adicionais</legend>
                        <div class="row-fluid">
                            <div class="span3">
                                <label>Banco/Agência:</label>
                            </div>
                            <div class="span7">
                                <input type="text" name="" value="CLIMEP / CLIMEP"  disabled/>
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="span3">
                                <label>Saldo Disponível/Indisponível:</label>
                            </div>

                            <div class="span7">
                                <input type="text" name="" value="R$ 1.031.213.01/ R$ 0,00" disabled />
                            </div>
                        </div>
                    </fieldset>
                </div><br> -->
                <div class="row-fluid">
                    <fieldset class="table-bordered">
                        <div class="row-fluid">
                            <div class="span2">
                                <label>Tipo de Operação:</label>
                            </div>
                            <div class="span1">
                                <input type="text" class="" onchange="buscaPorCodigoCR('tipo_operacao','baixa-modal');" name="baixacr-modal-cod_tipo_operacao">
                            </div>
                            <div class="span5">
                                <input type="text" name="baixacr-modal-tipo_operacao">
                            </div>
							<div class="span1">
								<button class="btn" onclick="abrir_modal('baixacr-tipo_operacao_modal')"><i class="icon-search"></i></button>
							</div>
                        </div>
                        <div class="row-fluid">
                            <div class="span2">
                                <label>N.Documento:</label>
                            </div>
                            <div class="span3">
                                <input type="text" class="" name="baixacr-modal-numero_documento">
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="span2">
                                <label>Data Baixa:</label>
                            </div>
                            <div class="span2">
                                <input data-mask="99/99/9999" type="text" name="baixacr-modal-data_baixa" />
                            </div>
                        </div>
                    </fieldset>
                    <fieldset class="table-bordered">
                        <div id="tabela2baixaduplicata">
                            <table class="table table-condensed table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th> Nº DOC </th>
                                        <th> CLIENTE  </th>
                                        <th> TIPO  </th>
                                        <th> VENCIMENTO </th>
                                        <th> VALOR </th>
                                        <th> TOTAL A PAGAR </th>
                                    </tr>
                                </thead>
                                <tbody name="baixacr-modal-tbody_lista_parcelas">
                                </tbody>
                            </table>
                        </div >
                    </fieldset><br>
                    <div class="offset7">
                        <input type="hidden" name="baixacr-modal-hidden_parcela_id" value="">
                        <a href="#" onclick="cleanFormConsultaBaixaCrModal();hidebaixarc()" class="btn"><i class="icon-circle-arrow-left"></i> Voltar</a>
                        <a href="#" onclick="baixaCrParcela();" style="display:none" id="baixacr-modal-baixa" class="btn" > Avançar <i class="icon-circle-arrow-right"></i></a>
                        <a href="#" onclick="estornoParcelaFatura();" style="display:none" id="baixacr-modal-estorno" class="btn" > Estornar <i class="icon-circle-arrow-right"></i></a>
                    </div>
                </div>
        </div><br>
    </div>
</div>

<div id="baixacr-tipo_operacao_modal" class="modal hide fade" >
	<div class="modal-body" style=" background-image: url('template/img/body-bg.png');">
		<div id="">
			<div class="row-fluid"><br>
				<table class="table table-bordered table-condensed">
					<thead>
						<tr >
							<th> COD OPERACAO </th>
							<th> OPERACAO </th>
							<th> E_S </th>
							<th> COMPENSACAO </th>
						</tr>
					</thead>

					<tbody id="lancamentos-lista_tipo_operacoes" >
					<?php
						$tipos = buscaTodosTipoOperacoes('E');
						foreach ($tipos as $tipo) {
					?>
							<tr id="teste" ondblclick="escolherOperacaoCr('<?php echo $tipo['nome'];?>');">
								<th> <?php echo $tipo['codigo'];?> </th>
								<th> <?php echo $tipo['nome'];?> </th>
								<th> <?php echo $tipo['e_s'];?> </th>
								<th> <?php echo $tipo['compensacao'];?> </th>
							</tr>
					<?php
						}
					?>
					</tbody>
				</table>
			</div>
		</div>
		<div class="modal-footer">
			<button class="btn" onclick="fechar_modal('baixacr-tipo_operacao_modal');"><i class="icon-remove"></i> Fechar </button>
		</div>
	</div>
</div>
