<link type="text/css" rel="stylesheet" href="view/financeiro/css/index.css" />
<div id="copiacheque" class="row-fluid" >
    <div id="chequeconsultarduplicatas">
        <script async defer language="javascript" src="view/financeiro/js/cheque.js"></script>
        <div class="row-fluid">
            <h2 class="titulo">Re-Impressão de Comprovantes </h2>
            <hr style="margin-top: -5px;">
            <p style="margin-left: 15px;">
                Preencha os campos abaixo e clique em<b> 'Localizar'</b> para iniciar a pesquisa na base de dados. Clique em <b>'Novo'</b> para inclusão.
            </p>
        </div>
        <div class="row-fluid">
            <fieldset class="table-bordered">
                <div class="row-fluid">
                    <div class="span2">
                        <label>Fornecedor:</label>
                    </div>
                    <div class="span1">
                        <input type="text" onchange="buscaFornecedorChequePorCodigo();" name="cheque-dup-cod_fornecedor" />
                    </div>
                    <div class="span5">
                        <input type="text" name="cheque-dup-fornecedor" />
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span2">
                        <label>De:</label>
                    </div>
                    <div class="span2">
                        <input data-mask="99/99/9999" type="text" name="" />
                    </div>
                    <div class="span1">
                        <label>Até:</label>
                    </div>
                    <div class="span2">
                        <input data-mask="99/99/9999" type="text" name="" />
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span2">
                        <label>Ordenado Por:</label>
                    </div>
                    <div class="span3">
                        <select name="consulta-dup-ordenado_por">
                            <option value="1" > EMPRESA </option>
                            <option value="2" > DATA DE LANCAMENTO </option>
                            <option value="3" > USUARIO</option>
                        </select>
                    </div>
                </div>
                <hr><br>
                <div class="row-fluid">
                    <div class="offset6">
                        <a href="#"  class="btn" onclick="showcheque();"><i class="icon-adjust"></i> Cheque </a>
                        <a href="#" class="btn"><i class="icon-plus-sign"></i> Novo (D.S.N) </a>
                        <a href="#" class="btn"><i class="icon-search"></i> Localizar </a>
                    </div>
                </div>
            </fieldset>
        </div><br>
    </div>
</div>

<div id="cheque" class="row-fluid" style="display: none;">

    <div class="row-fluid" >
        <div class="span4">

        </div>
        <div class="span4">
            <h3 align="center" class="titulo">COPIA DE CHEQUE</h3>
        </div>
        <div class="pull-right" style="margin-right: 20px;">
            <span class="add-on">Data:<b>12/03/2013</b></span>
        </div>
    </div>
    <hr>
    <div class="row-fluid" style="margin-left:15px;">
        <div class="span4">
            <a href="#" class="btn " onclick="hidecheque();"><i class=" icon-arrow-left"></i> Voltar</a>
        </div>
    </div><br>
    <div class="row-fluid">

        <div class="pull-left"  style="margin-left:15px;">
            <div class="input-prepend">
                <span class="add-on">Empresa:<b>CLIMEP</b></span>
            </div>
        </div>
        <div class="pull-right" style="margin-right:20px;">
            <div class="input-prepend">
                <span class="add-on">Usuário:<b>GILMARA</b></span>
            </div>
        </div>
        <div class="row-fluid">

            <fieldset class="table-bordered">
                <div class=" span5">
                    <div class="pull-left"  >
                        <div class="input-prepend">
                            <span class="add-on">Banco:<b> BANCO DO BRASIL</b></span>
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="pull-left"  >
                        <div class="input-prepend">
                            <span class="add-on">Cheque:<b> 30603 </b></span>
                        </div>
                    </div>
                </div>
                <div class="span3">
                    <div class="pull-right"  >
                        <div class="input-prepend">
                            <span class="add-on">R$:<b> 2.816,64 </b></span>
                        </div>
                    </div>
                </div>
                <div class="row-fluid">
                    <span>a quantia: <b>Dois Mil, Oitocentos e Dezesseis Reais e Sessenta e Quatro C</b></span>
                </div><br></br>
                <div class="row-fluid">
                    <div class=" span5">
                        <div class="pull-left"  >
                            <div class="input-prepend">
                                <span class="add-on">Nominal a:<b> PROFARMA FARM</b></span>
                            </div>
                        </div>
                    </div>
                </div>
                <fieldset class="table-bordered-t">
                    <legend> Histórico</legend>
                    <div class="input-prepend">
                        <span class="add-on"><b>06/03/2013</b></span>
                    </div>
                </fieldset>
            </fieldset>
            <hr>
            <span><b>Transação efetuada com sucesso por J8002027 GILMARA RODRIGUES PAMPLONA</b></span>
        </div>
    </div>
</div>

<script>

    function showcheque() {

        $("#copiacheque").hide('slow', function() {
            $("#cheque").show('slow');
        });
    }
    function hidecheque() {

        $("#cheque").hide('slow', function() {
            $("#copiacheque").show('slow');
        });
    }

</script>
