<link type="text/css" rel="stylesheet" href="view/financeiro/css/index.css" />
<div class="row-fluid">
    <h2 class="titulo">Plano de Conta Contabil</h2>
    <hr style="margin-top: -5px;">
</div>
<div class="row-fluid">
    <fieldset class="table-bordered">
        <div class="span6">
            <div class="" style="overflow: auto; width: 425px; height: 500px;">
                <table class="table table-bordered table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>Plano</th>
                            <th>Descrição</th>
                            <th>Programa</th>
                            <th>Módulo</th>
                        </tr>
                    </thead>

                    <tbody>
                        <tr>
                            <th>g</th>
                            <th>g</th>
                            <th>g</th>
                            <th>g</th>
                        </tr>
                        <tr>
                            <th>g</th>
                            <th>g</th>
                            <th>g</th>
                            <th>g</th>
                        </tr>
                        <tr>
                            <th>g</th>
                            <th>g</th>
                            <th>g</th>
                            <th>g</th>
                        </tr>
                        <tr>
                            <th>g</th>
                            <th>g</th>
                            <th>g</th>
                            <th>g</th>
                        </tr>
                        <tr>
                            <th>g</th>
                            <th>g</th>
                            <th>g</th>
                            <th>g</th>
                        </tr>
                        <tr>
                            <th>g</th>
                            <th>g</th>
                            <th>g</th>
                            <th>g</th>
                        </tr>
                        <tr>
                            <th>g</th>
                            <th>g</th>
                            <th>g</th>
                            <th>g</th>
                        </tr>
                        <tr>
                            <th>g</th>
                            <th>g</th>
                            <th>g</th>
                            <th>g</th>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="span6">
            <fieldset class="table-bordered">
                <div class="row-fluid">
                    <div class="span2">
                        <label>Plano:</label>
                    </div>
                    <div class="span3">
                        <input type="text" name="" >
                    </div>    
                    <div class="span6" id="planomg_b"  >
                        <input type="text" name="">
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span2">
                        <label>Sistema:</label>
                    </div>
                    <div class="span9">
                        <select>
                            <option></option>
                            <option></option>
                            <option></option>
                        </select>
                    </div>
                </div>
            </fieldset>
            <div class="row-fluid">
                <fieldset class="table-bordered">
                    <legend> Vacinas </legend>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group">
                                <div class="controls">
                                    <label class="radio">
                                        <input type="radio" value="" name="vacinas" checked="checked">
                                        Despensas do Caixa
                                    </label>
                                    <label class="radio">
                                        <input type="radio" value="o" name="vacinas">
                                        Forma de Pagamento
                                    </label>
                                    <label class="radio">
                                        <input type="radio" value="o" name="vacinas">
                                        Vacinas ou Serviços
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="span5">
                            <label >
                                <input type="checkbox" value="o" name="">
                                Desmarcar
                            </label>
                        </div> 
                    </div>
                    <div class="row-fluid">
                        <textarea id="texareacontabil">

                        </textarea>
                    </div>
                </fieldset><br>
                <div class="row-fluid">
                    <div class="span3">
                        <button class="btn btn-color" >Relacionar</button>
                    </div>

                    <div class="span3">
                        <button class="btn btn-color">Incluir Plano Mestre</button>
                    </div>

                    <div class="span3">
                        <button class="btn btn-color">Alterar descrição</button>
                    </div>

                    <div class="span3">
                        <button class="btn btn-color"><i class="icon-remove"></i> Fechar</button>
                    </div>

                </div>
            </div><br>
        </div>
    </fieldset>
</div><br>

