<link type="text/css" rel="stylesheet" href="view/financeiro/css/index.css" />
<div class="row-fluid">
	<h2 class="titulo">CTREC - Lançamento de Custódia </h2>
	<hr style="margin-top: -5px;">
	<p style="margin-left: 15px;">
		Preencha os campos abaixo e clique em<b> 'Avançar'</b> para iniciar  a digitação de uma nova nota.
	</p>
</div>
<div class="row-fluid">
	<fieldset class="table-bordered">
		  <div class="row-fluid">
			<div class="span2">
				<label>Tipo de Cliente:</label>
			</div>
			<div class="span5">
				<select>
					<option></option>
					<option></option>
					<option></option>
					<option></option>
				</select>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span2">
				<label>Conta Corrente:</label>
			</div>
			<div class="span1">
				<input type="text" name="" />
			</div>
			<div class="span5">
				<input type="text" name="" />
			</div>
		</div>
		<div class="row-fluid">
			<div class="span2">
				<label>Tipo de Operação:</label>
			</div>
			<div class="span1">
				<input type="text" name="" />
			</div>
			<div class="span5">
				<input type="text" name="" />
			</div>
		</div>
		
		<div class="row-fluid">
			<div class="span2">
				<label>Status:</label>
			</div>
			<div class="span3">
				<select>
					<option></option>
					<option></option>
					<option></option>
					<option></option>
				</select>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span2">
				<label>Selecionado Por:</label>
			</div>
			<div class="span3">
				<select>
					<option></option>
					<option></option>
					<option></option>
					<option></option>
				</select>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span2">
				<label>Data Inicial:</label>
			</div>
			<div class="span2">
				<input type="text" name="" />
			</div>
			<div class="span2">
				<label>Data Final:</label>
			</div>
			<div class="span2">
				<input type="text" name="" />
			</div>
		</div>
		<div class="row-fluid">
			<div class="span2">
				<label>Per.Antecipação:</label>
			</div>
			<div class="span2">
				<input type="text" name="" />
			</div>
			<div class="span2">
				<label>Compensação:</label>
			</div>
			<div class="span2">
				<input type="text" name="" />
			</div>
		</div>
		  <div class="row-fluid">
			<div class="span2">
				<label>Observação:</label>
			</div>
			
			<div class="span7">
				<input type="text" name="" />
			</div>
		</div>
		<div class="row-fluid">
			<fieldset class="table-bordered">
				<legend>
					<b>Vencimentos</b>
				</legend>
				<div class="row-fluid">
					<table class="table table-condensed table-bordered table-striped">
						<thead>
							<tr>
								<th> Parcela</th>
								 <th> Cliente</th>
								 <th> Vencimento</th>
								 <th> Valor</th>
							</tr>
							
						</thead>
						
						<tbody>
							<tr>
								<th> j</th>
								<th> j</th>
								<th> j </th>
								<th> j </th>
							</tr>
							<tr>
								<th> j</th>
								<th> j</th>
								<th> j </th>
								<th> j </th>
							</tr>
							<tr>
								<th> j</th>
								<th> j</th>
								<th> j </th>
								<th> j </th>
							</tr>
							<tr>
								<th> j</th>
								<th> j</th>
								<th> j </th>
								<th> j </th>
							</tr>
							<tr>
								<th> j</th>
								<th> j</th>
								<th> j </th>
								<th> j </th>
							</tr>
						</tbody>
					</table>
				</div>
			</fieldset>
		</div><br>
		<div class="row-fluid">
			 <div class="offset7">
				<a href="#" class="btn"><i class="icon-search"></i> Consultar </a>
				<a href="#" class="btn"> Avançar <i class="icon-circle-arrow-right"></i></a>
			</div>
		</div>
	</fieldset>
</div><br>

