<link type="text/css" rel="stylesheet" href="view/financeiro/css/index.css" />

<div class="row-fluid">
<div id="extrato_form" class="row-fluid">
<script async defer language="javascript" src="view/financeiro/js/extrato.js"></script>
<div class="row-fluid">
	<h2 class="titulo">Filtro de Movimento Financeiro</h2>
	<hr style="margin-top: -5px;">
</div>
<div id="extrato_form" class="row-fluid">
	<fieldset class="table-bordered">
		<div class="row-fluid">
			<div class="span2">
				<label>Conta Corrente:</label>
			</div>
			<div class="span5">
				<select name="extrato-conta_corrente">
					<?php
					$contas = buscaTodasContasCorrente();
					foreach ($contas as $conta) {
						?>
						<option value="<?php echo $conta['id']; ?>"> <?php echo $conta['nome']; ?> </option>
						<?php
					}
					?>
				</select>
			</div>
		</div> <br>
		<div class="row-fluid">
			<div class="span2">
				<label>De:</label>
			</div>
			<div class="span2">
				<input data-mask="99/99/9999" type="text" name="extrato-data_inicio"/>
			</div>
			<div class="span1">
				<label>Até:</label>
			</div>
			<div class="span2">
				<input data-mask="99/99/9999" type="text" name="extrato-data_fim"/>
			</div>
		</div>
		<hr>
		<div class="row-fluid">
			<div class="span4">
				<!--<label>
					<input type="checkbox" name="" />
					Somente Lançamentos do usuário
				</label> -->
			</div>
			<div class="offset5">
				<a href="#" onclick="extratoFinanceiro();" class="btn"> Avançar <i class="icon-circle-arrow-right"></i></a>
			</div>
		</div>
	</fieldset>
</div><br>
</div>
</div>

<div id="extrato" class="row-fluid" style="display: none">
    <div class="row-fluid">
        <h2 class="titulo"> Extrato Financeiro</h2>
        <hr style="margin-top: -5px;">
    </div>
    <div class="row-fluid">
        <div class=" span5" style="margin-left: 10px;">
            <a href="#" onclick="voltarExtrato();" class="btn"><i class="icon-circle-arrow-left"></i> Voltar</a>
            <a href="#" onclick="imprimirExtrato()" class="btn"><i class="icon-print"></i> Imprimir</a>
        </div>
        <fieldset class="table-bordered">
            <div class="row-fluid" id="tabelaconsultaduplicata">
                <!--<table class="tablebigfinanceiro table-condensed table-bordered table-striped">-->
                <table >
                    <thead>
                        <tr>
                            <th> DATA </th>
                            <th> DOCUMENTO </th>
                            <th> OPERAÇÃO </th>
                            <th> DEBITO </th>
                            <th> CREDITO </th>
                            <th> SALDO </th>
                        </tr>
                    </thead>

                    <tbody id="extrato-lista_parcelas"> </tbody>
                </table>
            </div>
        </fieldset>
    </div>
</div>
